### ISSUE TITLE
[BUG][Regression] NotImplementedError: A set filter over InfSet[Int] is not implemented)

### ISSUE THREAD

**Issue by lemmy** [informalsystems/apalache#1045]
Regression in 0.16.5! Specs at https://github.com/tlaplus-workshops/ewd998/

```shell
$ apalache-mc check --config=APAsyncTerminationDetection.cfg --length=1 --inv=StableInv --init=Init AsyncTerminationDetection_apalache.tla
# Tool home: /workspaces/ewd998/tools/apalache
# Package:   /workspaces/ewd998/tools/apalache/mod-distribution/target/apalache-pkg-0.16.4-full.jar
# JVM args:  -Xmx4096m -DTLA-Library=/workspaces/ewd998/tools/apalache/src/tla
#
# APALACHE version 0.16.4 build 763d5c4
#
# WARNING: This tool is in the experimental stage.
#          Please report bugs at: [https://github.com/informalsystems/apalache/issues]
# 
# Usage statistics is ON. Thank you!
# If you have changed your mind, disable the statistics with config --enable-stats=false.

Checker options: filename=AsyncTerminationDetection_apalache.tla, init=Init, next=, inv=StableInv I@17:00:47.539
Tuning:                                                           I@17:00:47.906
PASS #0: SanyParser                                               I@17:00:47.907
Parsing file /workspaces/ewd998/AsyncTerminationDetection_apalache.tla
Parsing file /workspaces/ewd998/AsyncTerminationDetection.tla
Parsing file /tmp/Naturals.tla
PASS #1: TypeCheckerSnowcat                                       I@17:00:48.687
 > Running Snowcat .::.                                           I@17:00:48.687
 > Your types are great!                                          I@17:00:49.053
 > All expressions are typed                                      I@17:00:49.053
PASS #2: ConfigurationPass                                        I@17:00:49.105
  > APAsyncTerminationDetection.cfg: Loading TLC configuration    I@17:00:49.108
Fairness constraints are ignored by Apalache: WF_vars()(Next())   W@17:00:49.161
  > APAsyncTerminationDetection.cfg: Using SPECIFICATION Spec     I@17:00:49.161
  > APAsyncTerminationDetection.cfg: Init operator is set in TLC config but overridden via --init command line option; using Init W@17:00:49.161
  > Using the next predicate Next from the TLC config             I@17:00:49.162
  > APAsyncTerminationDetection.cfg: found INVARIANTS: TypeOK     I@17:00:49.162
  > Overriding with command line arguments: --inv StableInv       W@17:00:49.162
  > Set the initialization predicate to Init                      I@17:00:49.163
  > Set the transition predicate to Next                          I@17:00:49.164
  > Set an invariant to StableInv                                 I@17:00:49.165
  > Replaced CONSTANT N with 3                                    I@17:00:49.167
PASS #3: DesugarerPass                                            I@17:00:49.201
  > Desugaring...                                                 I@17:00:49.202
PASS #4: UnrollPass                                               I@17:00:49.236
  > Unroller                                                      I@17:00:49.257
PASS #5: InlinePass                                               I@17:00:49.293
  > InlinerOfUserOper                                             I@17:00:49.296
  > Wrap                                                          I@17:00:49.331
  > CallByNameOperatorEmbedder                                    I@17:00:49.335
  > LetInExpander                                                 I@17:00:49.339
  > Unwrap                                                        I@17:00:49.344
  > InlinerOfUserOper                                             I@17:00:49.346
Leaving only relevant operators: CInitPrimed, Init, InitPrimed, Next, StableInv I@17:00:49.355
PASS #6: PrimingPass                                              I@17:00:49.382
  > Introducing InitPrimed for Init'                              I@17:00:49.384
PASS #7: VCGen                                                    I@17:00:49.411
  > Producing verification conditions from the invariant StableInv I@17:00:49.412
  > VCGen produced 4 verification condition(s)                    I@17:00:49.422
PASS #8: PreprocessingPass                                        I@17:00:49.454
  > Before preprocessing: unique renaming                         I@17:00:49.455
 > Applying standard transformations:                             I@17:00:49.464
  > PrimePropagation                                              I@17:00:49.464
  > Desugarer                                                     I@17:00:49.496
  > UniqueRenamer                                                 I@17:00:49.527
  > Normalizer                                                    I@17:00:49.560
  > Keramelizer                                                   I@17:00:49.594
  > After preprocessing: UniqueRenamer                            I@17:00:49.632
PASS #9: TransitionFinderPass                                     I@17:00:49.666
  > Found 1 initializing transitions                              I@17:00:49.686
  > Found 4 transitions                                           I@17:00:49.699
  > No constant initializer                                       I@17:00:49.699
  > Applying unique renaming                                      I@17:00:49.700
PASS #10: OptimizationPass                                        I@17:00:49.730
 > Applying optimizations:                                        I@17:00:49.736
  > ConstSimplifier                                               I@17:00:49.737
  > ExprOptimizer                                                 I@17:00:49.743
  > ConstSimplifier                                               I@17:00:49.745
PASS #11: AnalysisPass                                            I@17:00:49.769
 > Marking skolemizable existentials and sets to be expanded...   I@17:00:49.774
  > Skolemization                                                 I@17:00:49.774
  > Expansion                                                     I@17:00:49.776
  > Remove unused let-in defs                                     I@17:00:49.780
 > Running analyzers...                                           I@17:00:49.784
  > Introduced expression grades                                  I@17:00:49.820
  > Introduced 5 formula hints                                    I@17:00:49.821
PASS #12: PostTypeCheckerSnowcat                                  I@17:00:49.821
 > Running Snowcat .::.                                           I@17:00:49.821
 > Your types are great!                                          I@17:00:50.208
 > All expressions are typed                                      I@17:00:50.208
PASS #13: BoundedChecker                                          I@17:00:50.239
State 0: Checking 4 state invariants                              I@17:00:50.650
Step 0: picking a transition out of 1 transition(s)               I@17:00:50.689
State 1: Checking 2 state invariants                              I@17:00:50.716
State 1: Checking 3 state invariants                              I@17:00:50.761
State 1: Checking 3 state invariants                              I@17:00:50.802
State 1: Checking 2 state invariants                              I@17:00:50.835
Step 1: picking a transition out of 4 transition(s)               I@17:00:50.850
The outcome is: NoError                                           I@17:00:50.881
PASS #14: Terminal                                                I@17:00:50.882
Checker reports no error up to computation length 1               I@17:00:50.883
It took me 0 days  0 hours  0 min  3 sec                          I@17:00:50.884
Total time: 3.427 sec                                             I@17:00:50.884
EXITCODE: OK


$ apalache-mc check --config=APAsyncTerminationDetection.cfg --length=1 --inv=StableInv --init=Init AsyncTerminationDetection_apalache.tla
# Tool home: /workspaces/ewd998/tools/apalache
# Package:   /workspaces/ewd998/tools/apalache/mod-distribution/target/apalache-pkg-0.16.5-full.jar
# JVM args:  -Xmx4096m -DTLA-Library=/workspaces/ewd998/tools/apalache/src/tla
#
# APALACHE version 0.16.5 build 417cf58
#
# WARNING: This tool is in the experimental stage.
#          Please report bugs at: [https://github.com/informalsystems/apalache/issues]
# 
# Usage statistics is ON. Thank you!
# If you have changed your mind, disable the statistics with config --enable-stats=false.

Checker options: filename=AsyncTerminationDetection_apalache.tla, init=Init, next=, inv=StableInv I@17:01:15.041
Tuning:                                                           I@17:01:15.434
PASS #0: SanyParser                                               I@17:01:15.435
Parsing file /workspaces/ewd998/AsyncTerminationDetection_apalache.tla
Parsing file /workspaces/ewd998/AsyncTerminationDetection.tla
Parsing file /tmp/Naturals.tla
PASS #1: TypeCheckerSnowcat                                       I@17:01:16.228
 > Running Snowcat .::.                                           I@17:01:16.228
 > Your types are great!                                          I@17:01:16.622
 > All expressions are typed                                      I@17:01:16.623
PASS #2: ConfigurationPass                                        I@17:01:16.694
  > APAsyncTerminationDetection.cfg: Loading TLC configuration    I@17:01:16.697
Fairness constraints are ignored by Apalache: WF_vars()(Next())   W@17:01:16.756
  > APAsyncTerminationDetection.cfg: Using SPECIFICATION Spec     I@17:01:16.756
  > APAsyncTerminationDetection.cfg: Init operator is set in TLC config but overridden via --init command line option; using Init W@17:01:16.757
  > Using the next predicate Next from the TLC config             I@17:01:16.757
  > APAsyncTerminationDetection.cfg: found INVARIANTS: TypeOK     I@17:01:16.757
  > Overriding with command line arguments: --inv StableInv       W@17:01:16.758
  > Set the initialization predicate to Init                      I@17:01:16.759
  > Set the transition predicate to Next                          I@17:01:16.759
  > Set an invariant to StableInv                                 I@17:01:16.760
  > Replaced CONSTANT N with 3                                    I@17:01:16.762
PASS #3: DesugarerPass                                            I@17:01:16.805
  > Desugaring...                                                 I@17:01:16.805
PASS #4: UnrollPass                                               I@17:01:16.847
  > Unroller                                                      I@17:01:16.864
PASS #5: InlinePass                                               I@17:01:16.906
  > InlinerOfUserOper                                             I@17:01:16.910
  > Wrap                                                          I@17:01:16.943
  > CallByNameOperatorEmbedder                                    I@17:01:16.947
  > LetInExpander                                                 I@17:01:16.952
  > Unwrap                                                        I@17:01:16.956
  > InlinerOfUserOper                                             I@17:01:16.960
Leaving only relevant operators: CInitPrimed, Init, InitPrimed, Next, StableInv I@17:01:16.969
PASS #6: PrimingPass                                              I@17:01:16.988
  > Introducing InitPrimed for Init'                              I@17:01:16.990
PASS #7: VCGen                                                    I@17:01:17.013
  > Producing verification conditions from the invariant StableInv I@17:01:17.014
  > VCGen produced 4 verification condition(s)                    I@17:01:17.022
PASS #8: PreprocessingPass                                        I@17:01:17.044
  > Before preprocessing: unique renaming                         I@17:01:17.044
 > Applying standard transformations:                             I@17:01:17.052
  > PrimePropagation                                              I@17:01:17.052
  > Desugarer                                                     I@17:01:17.077
  > UniqueRenamer                                                 I@17:01:17.102
  > Normalizer                                                    I@17:01:17.129
  > Keramelizer                                                   I@17:01:17.155
  > After preprocessing: UniqueRenamer                            I@17:01:17.184
PASS #9: TransitionFinderPass                                     I@17:01:17.215
  > Found 1 initializing transitions                              I@17:01:17.235
  > Found 4 transitions                                           I@17:01:17.248
  > No constant initializer                                       I@17:01:17.249
  > Applying unique renaming                                      I@17:01:17.251
PASS #10: OptimizationPass                                        I@17:01:17.285
 > Applying optimizations:                                        I@17:01:17.292
  > ConstSimplifier                                               I@17:01:17.293
  > ExprOptimizer                                                 I@17:01:17.300
  > ConstSimplifier                                               I@17:01:17.302
PASS #11: AnalysisPass                                            I@17:01:17.328
 > Marking skolemizable existentials and sets to be expanded...   I@17:01:17.335
  > Skolemization                                                 I@17:01:17.336
  > Expansion                                                     I@17:01:17.337
  > Remove unused let-in defs                                     I@17:01:17.342
 > Running analyzers...                                           I@17:01:17.346
  > Introduced expression grades                                  I@17:01:17.385
  > Introduced 5 formula hints                                    I@17:01:17.386
PASS #12: PostTypeCheckerSnowcat                                  I@17:01:17.386
 > Running Snowcat .::.                                           I@17:01:17.386
 > Your types are great!                                          I@17:01:17.760
 > All expressions are typed                                      I@17:01:17.761
PASS #13: BoundedChecker                                          I@17:01:17.793
(Please report an issue at: [https://github.com/informalsystems/apalache/issues],scala.NotImplementedError: A set filter over InfSet[Int] is not implemented)
Unhandled exception                                               E@17:01:18.132
scala.NotImplementedError: A set filter over InfSet[Int] is not implemented
        at at.forsyte.apalache.tla.bmcmt.rules.SetFilterRule.apply(SetFilterRule.scala:29)
        at at.forsyte.apalache.tla.bmcmt.SymbStateRewriterImpl.rewriteOnce(SymbStateRewriterImpl.scala:336)
        at at.forsyte.apalache.tla.bmcmt.SymbStateRewriterImpl.doRecursive$1(SymbStateRewriterImpl.scala:367)
        at at.forsyte.apalache.tla.bmcmt.SymbStateRewriterImpl.rewriteUntilDone(SymbStateRewriterImpl.scala:401)
        at at.forsyte.apalache.tla.bmcmt.rules.SetInRule.apply(SetInRule.scala:45)
        at at.forsyte.apalache.tla.bmcmt.SymbStateRewriterImpl.rewriteOnce(SymbStateRewriterImpl.scala:336)
        at at.forsyte.apalache.tla.bmcmt.SymbStateRewriterImpl.doRecursive$1(SymbStateRewriterImpl.scala:367)
        at at.forsyte.apalache.tla.bmcmt.SymbStateRewriterImpl.rewriteUntilDone(SymbStateRewriterImpl.scala:401)
        at at.forsyte.apalache.tla.bmcmt.trex.TransitionExecutorImpl.assertState(TransitionExecutorImpl.scala:198)
        at at.forsyte.apalache.tla.bmcmt.trex.FilteredTransitionExecutor.assertState(FilteredTransitionExecutor.scala:88)
        at at.forsyte.apalache.tla.bmcmt.trex.ConstrainedTransitionExecutor.assertState(ConstrainedTransitionExecutor.scala:102)
        at at.forsyte.apalache.tla.bmcmt.SeqModelChecker.$anonfun$run$1(SeqModelChecker.scala:48)
        at at.forsyte.apalache.tla.bmcmt.SeqModelChecker.$anonfun$run$1$adapted(SeqModelChecker.scala:47)
        at scala.collection.immutable.List.foreach(List.scala:431)
        at at.forsyte.apalache.tla.bmcmt.SeqModelChecker.run(SeqModelChecker.scala:47)
        at at.forsyte.apalache.tla.bmcmt.passes.BoundedCheckerPassImpl.runIncrementalChecker(BoundedCheckerPassImpl.scala:131)
        at at.forsyte.apalache.tla.bmcmt.passes.BoundedCheckerPassImpl.execute(BoundedCheckerPassImpl.scala:98)
        at at.forsyte.apalache.infra.passes.PassChainExecutor.exec$1(PassChainExecutor.scala:22)
        at at.forsyte.apalache.infra.passes.PassChainExecutor.run(PassChainExecutor.scala:37)
        at at.forsyte.apalache.tla.Tool$.runCheck(Tool.scala:187)
        at at.forsyte.apalache.tla.Tool$.$anonfun$run$3(Tool.scala:95)
        at at.forsyte.apalache.tla.Tool$.handleExceptions(Tool.scala:322)
        at at.forsyte.apalache.tla.Tool$.run(Tool.scala:95)
        at at.forsyte.apalache.tla.Tool$.main(Tool.scala:45)
        at at.forsyte.apalache.tla.Tool.main(Tool.scala)
It took me 0 days  0 hours  0 min  3 sec                          I@17:01:18.133
Total time: 3.157 sec                                             I@17:01:18.133
EXITCODE: ERROR (255)
```

**Comment by lemmy** [comment]
Are there plans to fix this regression?

**Comment by konnov** [comment]
Sorry. We've missed this one. Will triage it.

**Comment by konnov** [comment]
Just tried it on version 0.24.2. It all works now.
