### ISSUE TITLE
[BUG] Missing cases for the `\subseteq` rule: Powersets

### ISSUE THREAD

**Issue by Kukovec** [informalsystems/apalache#1103]
## Description

Whenever an unexpanded `SUBSET` expression is on the left-hand-side of `\subseteq` the tool throws.

## Input specification

```tla
---------- MODULE test ----------

EXTENDS Integers

A == {1,2}
B == (SUBSET A) \subseteq SUBSET A
C == (SUBSET A) \subseteq ( { x \in SUBSET A: \A y \in x: y < 5 } )
    
Init == TRUE

Next == TRUE
====================
```

## The command line parameters used to run the tool

`--length=1 --inv=B` or `--length=1 --inv=C`

## Expected behavior

No exception.

## Additional context

Example output for `--inv=B`:
```
test.tla:124:8-124:8: rewriter error: Unexpected set types: PowSet[FinSet[Int]] and PowSet[FinSet[Int]] in SUBSET {1, 2} ⊆ SUBSET {1, 2} E@17:05:03.029
at.forsyte.apalache.tla.bmcmt.RewriterException: Unexpected set types: PowSet[FinSet[Int]] and PowSet[FinSet[Int]] in SUBSET {1, 2} ⊆ SUBSET {1, 2}
	at at.forsyte.apalache.tla.bmcmt.rules.SetInclusionRule.apply(SetInclusionRule.scala:51)
	at at.forsyte.apalache.tla.bmcmt.SymbStateRewriterImpl.rewriteOnce(SymbStateRewriterImpl.scala:336)
	at at.forsyte.apalache.tla.bmcmt.SymbStateRewriterImpl.doRecursive$1(SymbStateRewriterImpl.scala:367)
	at at.forsyte.apalache.tla.bmcmt.SymbStateRewriterImpl.rewriteUntilDone(SymbStateRewriterImpl.scala:401)
	at at.forsyte.apalache.tla.bmcmt.rules.NegRule.apply(NegRule.scala:28)
	at at.forsyte.apalache.tla.bmcmt.SymbStateRewriterImpl.rewriteOnce(SymbStateRewriterImpl.scala:336)
	at at.forsyte.apalache.tla.bmcmt.SymbStateRewriterImpl.doRecursive$1(SymbStateRewriterImpl.scala:367)
	at at.forsyte.apalache.tla.bmcmt.SymbStateRewriterImpl.rewriteUntilDone(SymbStateRewriterImpl.scala:401)
	at at.forsyte.apalache.tla.bmcmt.trex.TransitionExecutorImpl.assertState(TransitionExecutorImpl.scala:198)
	at at.forsyte.apalache.tla.bmcmt.trex.FilteredTransitionExecutor.assertState(FilteredTransitionExecutor.scala:88)
	at at.forsyte.apalache.tla.bmcmt.trex.ConstrainedTransitionExecutor.assertState(ConstrainedTransitionExecutor.scala:102)
	at at.forsyte.apalache.tla.bmcmt.SeqModelChecker.$anonfun$checkInvariants$2(SeqModelChecker.scala:271)
	at at.forsyte.apalache.tla.bmcmt.SeqModelChecker.$anonfun$checkInvariants$2$adapted(SeqModelChecker.scala:259)
	at scala.collection.TraversableLike$WithFilter.$anonfun$foreach$1(TraversableLike.scala:985)
	at scala.collection.immutable.List.foreach(List.scala:431)
	at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:984)
	at at.forsyte.apalache.tla.bmcmt.SeqModelChecker.checkInvariants(SeqModelChecker.scala:259)
	at at.forsyte.apalache.tla.bmcmt.SeqModelChecker.$anonfun$prepareTransitionsAndCheckInvariants$6(SeqModelChecker.scala:181)
	at at.forsyte.apalache.tla.bmcmt.SeqModelChecker.$anonfun$prepareTransitionsAndCheckInvariants$6$adapted(SeqModelChecker.scala:145)
	at scala.collection.TraversableLike$WithFilter.$anonfun$foreach$1(TraversableLike.scala:985)
	at scala.collection.immutable.List.foreach(List.scala:431)
	at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:984)
	at at.forsyte.apalache.tla.bmcmt.SeqModelChecker.prepareTransitionsAndCheckInvariants(SeqModelChecker.scala:145)
	at at.forsyte.apalache.tla.bmcmt.SeqModelChecker.makeStep(SeqModelChecker.scala:67)
	at at.forsyte.apalache.tla.bmcmt.SeqModelChecker.run(SeqModelChecker.scala:51)
	at at.forsyte.apalache.tla.bmcmt.passes.BoundedCheckerPassImpl.runIncrementalChecker(BoundedCheckerPassImpl.scala:140)
	at at.forsyte.apalache.tla.bmcmt.passes.BoundedCheckerPassImpl.execute(BoundedCheckerPassImpl.scala:103)
	at at.forsyte.apalache.infra.passes.PassChainExecutor.exec$1(PassChainExecutor.scala:22)
	at at.forsyte.apalache.infra.passes.PassChainExecutor.run(PassChainExecutor.scala:37)
	at at.forsyte.apalache.tla.Tool$.runCheck(Tool.scala:216)
	at at.forsyte.apalache.tla.Tool$.$anonfun$run$3(Tool.scala:100)
	at at.forsyte.apalache.tla.Tool$.handleExceptions(Tool.scala:354)
	at at.forsyte.apalache.tla.Tool$.run(Tool.scala:100)
	at at.forsyte.apalache.tla.Tool$.main(Tool.scala:46)
	at at.forsyte.apalache.tla.Tool.main(Tool.scala)
```

**Comment by thpani** [comment]
Cannot reproduce this on latest `v0.43.0-36-g2f8848485`. I assume this has been fixed.
