### ISSUE TITLE
[BUG] `apalache check` throws `rewriter error: OrRule is not applicable` with `--view`

### ISSUE THREAD

**Issue by rnbguy** [informalsystems/apalache#1285]
## Input specification

```
------------------------------ MODULE Indices ------------------------------
\* This is the model of Substrate Frame Indices from 
\* https://github.com/paritytech/substrate/tree/master/frame/indices 
\* at this commit: https://git.io/Ju5Jv
\*
\* An index is a short form of an address.
\* This module handles allocation of indices for a newly created accounts.
\*
\* This TLA+ model is created for demostrative purposes of MBT capabilities.
\* s2021 Andrey Kuprianov, Informal Systems

EXTENDS Integers, FiniteSets

CONSTANTS 
  \* @typeAlias: ADDR = Int;
  \* @typeAlias: INDEX = Int;
  \* @typeAlias: BALANCE = Int;
  \* @typeAlias: INDEX_ENTRY = [ addr: ADDR, deposit: Int, perm: Bool ];
  \* @typeAlias: INDICES = INDEX -> INDEX_ENTRY;
  \* @typeAlias: RESERVES = ADDR -> BALANCE;
  \* @typeAlias: ACTION = [type: Str, who: ADDR, new: ADDR, index: INDEX, freeze: Bool];
  \* How many users and indices are there? 
  \* @type: Int;
  NUM_USERS,
  \* @type: Int;
  NUM_INDICES

VARIABLES
 \* @type: INDICES;
  indices,
  \* @type: RESERVES;
  reserved,
  \* @type: ACTION;
  action,
  \* @type: Str;
  actionOutcome

Indices == 1..NUM_INDICES
Addresses == 0..NUM_USERS

\* A non-address
None == -1
\* A root address
Root == 0


\* Possible outcomes

\* Operation successful
OK == "OK"
\* The index was not already assigned.
NotAssigned == "NotAssigned"
\* The index is assigned to another account.
NotOwner == "NotOwner"
\* Only root can do this.
NotRoot == "NotRoot"
\* The index was not available.
InUse == "InUse"
\* The source and destination accounts are identical.
NotTransfer == "NotTransfer"
\* The index is permanent and may not be freed/changed.
Permanent == "Permanent"


ClaimOutcome(who, index) ==
  IF indices[index].who /= None
    THEN InUse
  ELSE OK

\* @type: (ADDR, INDEX) => Bool;
Claim(who, index) ==
  /\ indices' = [indices EXCEPT ![index] = 
       [who |-> who, deposit |-> 1, perm |-> FALSE] ]
  /\ reserved' = [reserved EXCEPT ![who] = @ + 1]


\* @type: (ADDR, ADDR, INDEX) => Str;
TransferOutcome(who, new, index) ==
  IF who = new
    THEN NotTransfer
  ELSE IF indices[index].who = None
    THEN NotAssigned
  ELSE IF indices[index].perm 
    THEN Permanent
  ELSE IF indices[index].who /= who
    THEN NotOwner
  ELSE 
    OK

\* @type: (ADDR, ADDR, INDEX) => Bool;
Transfer(who, new, index)==
  LET amount == indices[index].deposit IN
  /\ indices' = [indices EXCEPT ![index] = [who |-> new, deposit |-> amount, perm |-> FALSE]]
  /\ reserved' = [reserved EXCEPT ![who] = @ - amount, ![new] = @ + amount]


\* @type: (ADDR, INDEX) => Str;
FreeOutcome(who, index) ==
  IF indices[index].who = None
    THEN NotAssigned
  ELSE IF indices[index].perm 
    THEN Permanent
  ELSE IF indices[index].who /= who
    THEN NotOwner
  ELSE 
    OK

\* @type: (ADDR, INDEX) => Bool;
Free(who, index)==
  /\ indices' = [indices EXCEPT ![index] = [who |-> None, deposit |-> 0, perm |-> FALSE]]
  /\ reserved' = [reserved EXCEPT ![who] = @ - indices[index].deposit]


\* @type: (ADDR, ADDR, INDEX, Bool) => Str;
ForceTransferOutcome(who, new, index, freeze) ==
  IF who /= Root
    THEN NotRoot
  ELSE 
    OK

\* @type: (ADDR, ADDR, INDEX, Bool) => Bool;
ForceTransfer(who, new, index, freeze)==
  LET entry == indices[index] IN
    /\ indices' = [indices EXCEPT ![index] = [who |-> new, deposit |-> 0, perm |-> freeze]]
    /\ IF entry.who /= None THEN
         reserved' = [reserved EXCEPT ![who] = @ - indices[index].deposit]
       ELSE
         UNCHANGED reserved

\* @type: (ADDR, INDEX) => Str;
FreezeOutcome(who, index) ==
  IF indices[index].who = None
    THEN NotAssigned
  ELSE IF indices[index].perm
    THEN Permanent
  ELSE IF indices[index].who /= who
    THEN NotOwner
  ELSE OK

\* @type: (ADDR, INDEX) => Bool;
Freeze(who, index) ==
  /\ indices' = [indices EXCEPT ![index] = [who |-> who, deposit |-> 0, perm |-> TRUE]]
  /\ reserved' = [reserved EXCEPT ![who] = @ - indices[index].deposit]


\* Start with no occupied indices, and no reserved coins
Init == 
  /\ indices = [ i \in Indices |-> [ who |-> None, deposit |-> 0, perm |-> FALSE ] ]
  /\ reserved = [ a \in Addresses |-> 0 ]
  /\ action = [ type |-> "None" ]
  /\ actionOutcome = "None"




\* Actions: boilerplate code that checks preconditions, executes updates,
\* and stores action and actionOutcome.
\* This code will be auto-generated in the next versions of Modelator.

ClaimAction ==
  \E who \in Addresses:
  \E index \in Indices:
    /\ action' = [ type |-> "Claim", who |-> who, index |-> index ]
    /\ LET outcome == ClaimOutcome(who, index) IN 
        actionOutcome' = outcome /\
        IF outcome = OK THEN
          Claim(who, index)
        ELSE
          UNCHANGED <<indices, reserved>>

TransferAction ==
  \E who, new \in Addresses:
  \E index \in Indices:
    /\ action' = [ type |-> "Transfer", who |-> who, new |-> new, index |-> index ]
    /\ LET outcome == TransferOutcome(who, new, index) IN 
        actionOutcome' = outcome /\
        IF outcome = OK THEN
          Transfer(who, new, index)
        ELSE
          UNCHANGED <<indices, reserved>>

FreeAction ==
  \E who \in Addresses:
  \E index \in Indices:
    /\ action' = [ type |-> "Free", who |-> who, index |-> index ]
    /\ LET outcome == FreeOutcome(who, index) IN 
        actionOutcome' = outcome /\
        IF outcome = OK THEN
          Free(who, index)
        ELSE
          UNCHANGED <<indices, reserved>>

ForceTransferAction ==
  \E who, new \in Addresses:
  \E index \in Indices:
  \E freeze \in BOOLEAN:
    /\ action' = [ type |-> "ForceTransfer", who |-> who, new |-> new, index |-> index, freeze |-> freeze ]
    /\ LET outcome == ForceTransferOutcome(who, new, index, freeze) IN 
        actionOutcome' = outcome /\
        IF outcome = OK THEN
          ForceTransfer(who, new, index, freeze)
        ELSE
          UNCHANGED <<indices, reserved>>


FreezeAction ==
  \E who \in Addresses:
  \E index \in Indices:
    /\ action' = [ type |-> "Freeze", who |-> who, index |-> index ]
    /\ LET outcome == FreezeOutcome(who, index) IN 
        actionOutcome' = outcome /\
        IF outcome = OK THEN
          Freeze(who, index)
        ELSE
          UNCHANGED <<indices, reserved>>
Next == 
  \/ ClaimAction
  \/ TransferAction
  \/ FreeAction
  \/ ForceTransferAction
  \/ FreezeAction

\* @type: <<Str, Str>>;
View == << action.type, actionOutcome >>

NegInit == ~Init

=============================================================================
```

## Specification configuration

```
CONSTANTS
    NUM_USERS = 4
    NUM_INDICES = 4

INIT Init
NEXT Next

INVARIANT
    NegInit
```

## The command line parameters used to run the tool

```
--view=View
```

## Expected behavior

Prior to ITF (`<0.19.2`), Apalache is executed successfully on this input.

## Log files

```
11:57:54.560 [main] INFO  a.f.a.t.Tool\$ - Checker options: filename=Indices.tla, init=, next=, inv=
11:57:54.561 [main] INFO  a.f.a.t.Tool\$ - Tuning: 
11:57:54.562 [main] INFO  a.f.a.i.p.PassChainExecutor - PASS #0: SanyParser
11:57:54.788 [main] DEBUG a.f.a.i.p.PassChainExecutor - PASS #0: SanyParser [OK]
11:57:54.788 [main] INFO  a.f.a.i.p.PassChainExecutor - PASS #1: TypeCheckerSnowcat
11:57:54.788 [main] INFO  a.f.a.t.t.p.EtcTypeCheckerPassImpl -  > Running Snowcat .::.
11:57:55.116 [main] INFO  a.f.a.t.t.p.EtcTypeCheckerPassImpl -  > Your types are purrfect!
11:57:55.116 [main] INFO  a.f.a.t.t.p.EtcTypeCheckerPassImpl -  > All expressions are typed
11:57:55.116 [main] DEBUG a.f.a.i.p.PassChainExecutor - PASS #1: TypeCheckerSnowcat [OK]
11:57:55.116 [main] INFO  a.f.a.i.p.PassChainExecutor - PASS #2: ConfigurationPass
11:57:55.118 [main] INFO  a.f.a.t.p.p.ConfigurationPassImpl -   > Indices.cfg: Loading TLC configuration
11:57:55.141 [main] INFO  a.f.a.t.p.p.ConfigurationPassImpl -   > Using the init predicate Init from the TLC config
11:57:55.141 [main] INFO  a.f.a.t.p.p.ConfigurationPassImpl -   > Using the next predicate Next from the TLC config
11:57:55.141 [main] INFO  a.f.a.t.p.p.ConfigurationPassImpl -   > Indices.cfg: found INVARIANTS: NegInit
11:57:55.142 [main] INFO  a.f.a.t.p.p.ConfigurationPassImpl -   > Set the initialization predicate to Init
11:57:55.142 [main] INFO  a.f.a.t.p.p.ConfigurationPassImpl -   > Set the transition predicate to Next
11:57:55.142 [main] INFO  a.f.a.t.p.p.ConfigurationPassImpl -   > Set an invariant to NegInit
11:57:55.143 [main] INFO  a.f.a.t.p.ConstAndDefRewriter -   > Replaced CONSTANT NUM_INDICES with 4
11:57:55.145 [main] INFO  a.f.a.t.p.ConstAndDefRewriter -   > Replaced CONSTANT NUM_USERS with 4
11:57:55.153 [main] DEBUG a.f.a.i.p.PassChainExecutor - PASS #2: ConfigurationPass [OK]
11:57:55.153 [main] INFO  a.f.a.i.p.PassChainExecutor - PASS #3: DesugarerPass
11:57:55.154 [main] INFO  a.f.a.t.p.p.DesugarerPassImpl -   > Desugaring...
11:57:55.162 [main] DEBUG a.f.a.i.p.PassChainExecutor - PASS #3: DesugarerPass [OK]
11:57:55.163 [main] INFO  a.f.a.i.p.PassChainExecutor - PASS #4: UnrollPass
11:57:55.184 [main] INFO  a.f.a.t.p.p.UnrollPassImpl -   > Unroller
11:57:55.193 [main] DEBUG a.f.a.i.p.PassChainExecutor - PASS #4: UnrollPass [OK]
11:57:55.193 [main] INFO  a.f.a.i.p.PassChainExecutor - PASS #5: InlinePass
11:57:55.194 [main] INFO  a.f.a.t.p.p.InlinePassImpl -   > InlinerOfUserOper
11:57:55.208 [main] INFO  a.f.a.t.p.p.InlinePassImpl -   > Wrap
11:57:55.210 [main] INFO  a.f.a.t.p.p.InlinePassImpl -   > CallByNameOperatorEmbedder
11:57:55.213 [main] INFO  a.f.a.t.p.p.InlinePassImpl -   > LetInExpander
11:57:55.216 [main] INFO  a.f.a.t.p.p.InlinePassImpl -   > Unwrap
11:57:55.218 [main] INFO  a.f.a.t.p.p.InlinePassImpl -   > InlinerOfUserOper
11:57:55.222 [main] INFO  a.f.a.t.p.p.InlinePassImpl - Leaving only relevant operators: CInitPrimed, Init, InitPrimed, NegInit, Next, View
11:57:55.222 [main] DEBUG a.f.a.i.p.PassChainExecutor - PASS #5: InlinePass [OK]
11:57:55.223 [main] INFO  a.f.a.i.p.PassChainExecutor - PASS #6: PrimingPass
11:57:55.224 [main] INFO  a.f.a.t.a.p.PrimingPassImpl -   > Introducing InitPrimed for Init'
11:57:55.224 [main] DEBUG a.f.a.i.p.PassChainExecutor - PASS #6: PrimingPass [OK]
11:57:55.224 [main] INFO  a.f.a.i.p.PassChainExecutor - PASS #7: VCGen
11:57:55.225 [main] INFO  a.f.a.t.b.p.VCGenPassImpl -   > Producing verification conditions from the invariant NegInit
11:57:55.225 [main] INFO  a.f.a.t.b.p.VCGenPassImpl -   > Using state view View
11:57:55.228 [main] INFO  a.f.a.t.b.VCGenerator -   > VCGen produced 1 verification condition(s)
11:57:55.229 [main] DEBUG a.f.a.i.p.PassChainExecutor - PASS #7: VCGen [OK]
11:57:55.229 [main] INFO  a.f.a.i.p.PassChainExecutor - PASS #8: PreprocessingPass
11:57:55.229 [main] INFO  a.f.a.t.p.p.PreproPassImpl -   > Before preprocessing: unique renaming
11:57:55.232 [main] INFO  a.f.a.t.p.p.PreproPassImpl -  > Applying standard transformations:
11:57:55.232 [main] INFO  a.f.a.t.p.p.PreproPassImpl -   > PrimePropagation
11:57:55.234 [main] INFO  a.f.a.t.p.p.PreproPassImpl -   > Desugarer
11:57:55.237 [main] INFO  a.f.a.t.p.p.PreproPassImpl -   > UniqueRenamer
11:57:55.243 [main] INFO  a.f.a.t.p.p.PreproPassImpl -   > Normalizer
11:57:55.250 [main] INFO  a.f.a.t.p.p.PreproPassImpl -   > Keramelizer
11:57:55.258 [main] INFO  a.f.a.t.p.p.PreproPassImpl -   > After preprocessing: UniqueRenamer
11:57:55.272 [main] DEBUG a.f.a.i.p.PassChainExecutor - PASS #8: PreprocessingPass [OK]
11:57:55.273 [main] INFO  a.f.a.i.p.PassChainExecutor - PASS #9: TransitionFinderPass
11:57:55.289 [main] INFO  a.f.a.t.a.p.TransitionPassImpl -   > Found 1 initializing transitions
11:57:55.302 [main] INFO  a.f.a.t.a.p.TransitionPassImpl -   > Found 11 transitions
11:57:55.302 [main] INFO  a.f.a.t.a.p.TransitionPassImpl -   > No constant initializer
11:57:55.303 [main] INFO  a.f.a.t.a.p.TransitionPassImpl -   > Applying unique renaming
11:57:55.311 [main] DEBUG a.f.a.i.p.PassChainExecutor - PASS #9: TransitionFinderPass [OK]
11:57:55.312 [main] INFO  a.f.a.i.p.PassChainExecutor - PASS #10: OptimizationPass
11:57:55.314 [main] INFO  a.f.a.t.p.p.OptPassImpl -  > Applying optimizations:
11:57:55.315 [main] INFO  a.f.a.t.p.p.OptPassImpl -   > ConstSimplifier
11:57:55.322 [main] INFO  a.f.a.t.p.p.OptPassImpl -   > ExprOptimizer
11:57:55.326 [main] INFO  a.f.a.t.p.p.OptPassImpl -   > ConstSimplifier
11:57:55.334 [main] DEBUG a.f.a.i.p.PassChainExecutor - PASS #10: OptimizationPass [OK]
11:57:55.335 [main] INFO  a.f.a.i.p.PassChainExecutor - PASS #11: AnalysisPass
11:57:55.338 [main] INFO  a.f.a.t.b.p.AnalysisPassImpl -  > Marking skolemizable existentials and sets to be expanded...
11:57:55.338 [main] INFO  a.f.a.t.b.p.AnalysisPassImpl -   > Skolemization
11:57:55.339 [main] INFO  a.f.a.t.b.p.AnalysisPassImpl -   > Expansion
11:57:55.343 [main] INFO  a.f.a.t.b.p.AnalysisPassImpl -   > Remove unused let-in defs
11:57:55.348 [main] INFO  a.f.a.t.b.p.AnalysisPassImpl -  > Running analyzers...
11:57:55.352 [main] INFO  a.f.a.t.b.p.AnalysisPassImpl -   > Introduced expression grades
11:57:55.352 [main] DEBUG a.f.a.i.p.PassChainExecutor - PASS #11: AnalysisPass [OK]
11:57:55.352 [main] INFO  a.f.a.i.p.PassChainExecutor - PASS #12: PostTypeCheckerSnowcat
11:57:55.352 [main] INFO  a.f.a.t.b.p.PostTypeCheckerPassImpl -  > Running Snowcat .::.
11:57:55.981 [main] INFO  a.f.a.t.b.p.PostTypeCheckerPassImpl -  > Your types are purrfect!
11:57:55.982 [main] INFO  a.f.a.t.b.p.PostTypeCheckerPassImpl -  > All expressions are typed
11:57:55.982 [main] DEBUG a.f.a.i.p.PassChainExecutor - PASS #12: PostTypeCheckerSnowcat [OK]
11:57:55.982 [main] INFO  a.f.a.i.p.PassChainExecutor - PASS #13: BoundedChecker
11:57:56.155 [main] DEBUG a.f.a.t.b.t.TransitionExecutorImpl - Step #0, transition #0
11:57:56.155 [main] DEBUG a.f.a.t.b.t.TransitionExecutorImpl - Translating to SMT...
11:57:56.195 [main] DEBUG a.f.a.t.b.SeqModelChecker - Step 0: Transition #0. Is it enabled?
11:57:56.196 [main] DEBUG a.f.a.t.b.SeqModelChecker - Step 0: Transition #0 is enabled
11:57:56.196 [main] INFO  a.f.a.t.b.SeqModelChecker - State 0: Checking 1 state invariants
11:57:56.197 [main] DEBUG a.f.a.t.b.SeqModelChecker - State 0: Checking state invariant 0
11:57:56.326 [main] ERROR a.f.a.t.b.SeqModelChecker - State 0: state invariant 0 violated. Check the counterexample in: 
  /home/ranadeep/projects/test/_apalache-out/Indices.tla/2022-02-03T11-57-54_8408785083697036404/counterexample1.tla
  /home/ranadeep/projects/test/_apalache-out/Indices.tla/2022-02-03T11-57-54_8408785083697036404/MC1.out
  /home/ranadeep/projects/test/_apalache-out/Indices.tla/2022-02-03T11-57-54_8408785083697036404/counterexample1.json
  /home/ranadeep/projects/test/_apalache-out/Indices.tla/2022-02-03T11-57-54_8408785083697036404/counterexample1.itf.json
11:57:56.334 [main] ERROR a.f.a.t.Tool\$ - <unknown>: rewriter error: OrRule is not applicable to ¬((<<(["type" ↦ "None"])["type"], "None">>) = (<<\$C\$37["type"], \$C\$36>>))
at.forsyte.apalache.tla.bmcmt.RewriterException: OrRule is not applicable to ¬((<<(["type" ↦ "None"])["type"], "None">>) = (<<\$C\$37["type"], \$C\$36>>))
	at at.forsyte.apalache.tla.bmcmt.rules.OrRule.apply(OrRule.scala:79)
	at at.forsyte.apalache.tla.bmcmt.SymbStateRewriterImpl.rewriteOnce(SymbStateRewriterImpl.scala:325)
	at at.forsyte.apalache.tla.bmcmt.SymbStateRewriterImpl.doRecursive\$1(SymbStateRewriterImpl.scala:356)
	at at.forsyte.apalache.tla.bmcmt.SymbStateRewriterImpl.rewriteUntilDone(SymbStateRewriterImpl.scala:390)
	at at.forsyte.apalache.tla.bmcmt.trex.TransitionExecutorImpl.assertState(TransitionExecutorImpl.scala:198)
	at at.forsyte.apalache.tla.bmcmt.trex.FilteredTransitionExecutor.assertState(FilteredTransitionExecutor.scala:88)
	at at.forsyte.apalache.tla.bmcmt.trex.ConstrainedTransitionExecutor.assertPathOrConstraint(ConstrainedTransitionExecutor.scala:80)
	at at.forsyte.apalache.tla.bmcmt.trex.ConstrainedTransitionExecutor.addPathOrConstraint(ConstrainedTransitionExecutor.scala:33)
	at at.forsyte.apalache.tla.bmcmt.SeqModelChecker.\$anonfun\$excludePathView\$4(SeqModelChecker.scala:399)
	at at.forsyte.apalache.tla.bmcmt.SeqModelChecker.\$anonfun\$excludePathView\$4\$adapted(SeqModelChecker.scala:394)
	at scala.Option.foreach(Option.scala:407)
	at at.forsyte.apalache.tla.bmcmt.SeqModelChecker.excludePathView(SeqModelChecker.scala:394)
	at at.forsyte.apalache.tla.bmcmt.SeqModelChecker.\$anonfun\$checkInvariants\$2(SeqModelChecker.scala:280)
	at at.forsyte.apalache.tla.bmcmt.SeqModelChecker.\$anonfun\$checkInvariants\$2\$adapted(SeqModelChecker.scala:259)
	at scala.collection.TraversableLike\$WithFilter.\$anonfun\$foreach\$1(TraversableLike.scala:985)
	at scala.collection.immutable.List.foreach(List.scala:431)
	at scala.collection.TraversableLike\$WithFilter.foreach(TraversableLike.scala:984)
	at at.forsyte.apalache.tla.bmcmt.SeqModelChecker.checkInvariants(SeqModelChecker.scala:259)
	at at.forsyte.apalache.tla.bmcmt.SeqModelChecker.\$anonfun\$prepareTransitionsAndCheckInvariants\$6(SeqModelChecker.scala:181)
	at at.forsyte.apalache.tla.bmcmt.SeqModelChecker.\$anonfun\$prepareTransitionsAndCheckInvariants\$6\$adapted(SeqModelChecker.scala:145)
	at scala.collection.TraversableLike\$WithFilter.\$anonfun\$foreach\$1(TraversableLike.scala:985)
	at scala.collection.immutable.List.foreach(List.scala:431)
	at scala.collection.TraversableLike\$WithFilter.foreach(TraversableLike.scala:984)
	at at.forsyte.apalache.tla.bmcmt.SeqModelChecker.prepareTransitionsAndCheckInvariants(SeqModelChecker.scala:145)
	at at.forsyte.apalache.tla.bmcmt.SeqModelChecker.makeStep(SeqModelChecker.scala:67)
	at at.forsyte.apalache.tla.bmcmt.SeqModelChecker.run(SeqModelChecker.scala:51)
	at at.forsyte.apalache.tla.bmcmt.passes.BoundedCheckerPassImpl.runIncrementalChecker(BoundedCheckerPassImpl.scala:136)
	at at.forsyte.apalache.tla.bmcmt.passes.BoundedCheckerPassImpl.execute(BoundedCheckerPassImpl.scala:100)
	at at.forsyte.apalache.infra.passes.PassChainExecutor.exec\$1(PassChainExecutor.scala:22)
	at at.forsyte.apalache.infra.passes.PassChainExecutor.run(PassChainExecutor.scala:37)
	at at.forsyte.apalache.tla.Tool\$.runCheck(Tool.scala:222)
	at at.forsyte.apalache.tla.Tool\$.\$anonfun\$run\$2(Tool.scala:113)
	at at.forsyte.apalache.tla.Tool\$.\$anonfun\$run\$2\$adapted(Tool.scala:113)
	at at.forsyte.apalache.tla.Tool\$.handleExceptions(Tool.scala:360)
	at at.forsyte.apalache.tla.Tool\$.run(Tool.scala:113)
	at at.forsyte.apalache.tla.Tool\$.main(Tool.scala:48)
	at at.forsyte.apalache.tla.Tool.main(Tool.scala)
```

## System information

- Apalache version: `v0.20.0`
- OS: `Linux`
- JDK version: `17.0.1`

**Comment by konnov** [comment]
@gabrielamafra could you have a look at this one? It looks like `simplifyShallow` is producing an expression in `OrRule`, which cannot be processed.
