### ISSUE TITLE
[BUG] Crash with empty set inclusion

### ISSUE THREAD

**Issue by craft095** [informalsystems/apalache#1390]
## Description

Apalache crashes while checking specification

## Input specification

```
---- MODULE Apalache_M0 ----
VARIABLE
    \* @type: Bool;
    x

\* @type: Set(Bool)
ES == {}
Init == x = (ES \in {ES})
Next == x' = x
Spec == Init /\ [][Next]_x
Prop == x => x'
====
```

## The command line parameters used to run the tool

java -jar apalache-pkg-0.20.2-full.jar check Apalache_M0

## Expected behavior

Success/Violation

## Log files

```
# APALACHE
# version: 0.20.2
# build  : 5b59b10
#
# Usage statistics is OFF. We care about your privacy.
# If you want to help our project, consider enabling statistics with config --enable-stats=true.

Output directory: /mnt/c/work/TLA/tlc-qual/bug/_apalache-out/Apalache_M0/2022-02-21T19-49-22_13454564606756709692
Checker options: filename=Apalache_M0, init=, next=, inv=         I@19:49:22.635
Tuning:                                                           I@19:49:22.641
PASS #0: SanyParser                                               I@19:49:22.642
Parsing file /mnt/c/work/TLA/tlc-qual/bug/Apalache_M0.tla
[Apalache_M0:7:1-7:8]: Syntax error in annotation -- Unexpected character. Missing ')' or ';'? W@19:49:22.975
PASS #1: TypeCheckerSnowcat                                       I@19:49:23.034
 > Running Snowcat .::.                                           I@19:49:23.035
 > Your types are purrfect!                                       I@19:49:23.242
 > All expressions are typed                                      I@19:49:23.253
PASS #2: ConfigurationPass                                        I@19:49:23.256
  > Apalache_M0: Loading TLC configuration                        I@19:49:23.260
  > No TLC configuration found. Skipping.                         I@19:49:23.272
  > Command line option --init is not set. Using Init             I@19:49:23.272
  > Command line option --next is not set. Using Next             I@19:49:23.273
  > Set the initialization predicate to Init                      I@19:49:23.273
  > Set the transition predicate to Next                          I@19:49:23.275
PASS #3: DesugarerPass                                            I@19:49:23.284
  > Desugaring...                                                 I@19:49:23.285
PASS #4: UnrollPass                                               I@19:49:23.295
  > Unroller                                                      I@19:49:23.310
PASS #5: InlinePass                                               I@19:49:23.323
  > InlinerOfUserOper                                             I@19:49:23.326
  > Wrap                                                          I@19:49:23.344
  > CallByNameOperatorEmbedder                                    I@19:49:23.348
  > LetInExpander                                                 I@19:49:23.353
  > Unwrap                                                        I@19:49:23.355
  > InlinerOfUserOper                                             I@19:49:23.357
Leaving only relevant operators: CInitPrimed, Init, InitPrimed, Next I@19:49:23.364
PASS #6: PrimingPass                                              I@19:49:23.366
  > Introducing InitPrimed for Init'                              I@19:49:23.370
PASS #7: VCGen                                                    I@19:49:23.373
  > No invariant given. Only deadlocks will be checked            I@19:49:23.374
PASS #8: PreprocessingPass                                        I@19:49:23.376
  > Before preprocessing: unique renaming                         I@19:49:23.377
 > Applying standard transformations:                             I@19:49:23.393
  > PrimePropagation                                              I@19:49:23.393
  > Desugarer                                                     I@19:49:23.395
  > UniqueRenamer                                                 I@19:49:23.398
  > Normalizer                                                    I@19:49:23.400
  > Keramelizer                                                   I@19:49:23.406
  > After preprocessing: UniqueRenamer                            I@19:49:23.411
PASS #9: TransitionFinderPass                                     I@19:49:23.418
  > Found 1 initializing transitions                              I@19:49:23.442
  > Found 1 transitions                                           I@19:49:23.446
  > No constant initializer                                       I@19:49:23.447
  > Applying unique renaming                                      I@19:49:23.449
PASS #10: OptimizationPass                                        I@19:49:23.455
 > Applying optimizations:                                        I@19:49:23.463
  > ConstSimplifier                                               I@19:49:23.464
  > ExprOptimizer                                                 I@19:49:23.467
  > ConstSimplifier                                               I@19:49:23.469
PASS #11: AnalysisPass                                            I@19:49:23.471
 > Marking skolemizable existentials and sets to be expanded...   I@19:49:23.476
  > Skolemization                                                 I@19:49:23.477
  > Expansion                                                     I@19:49:23.478
  > Remove unused let-in defs                                     I@19:49:23.482
 > Running analyzers...                                           I@19:49:23.485
  > Introduced expression grades                                  I@19:49:23.488
PASS #12: PostTypeCheckerSnowcat                                  I@19:49:23.489
 > Running Snowcat .::.                                           I@19:49:23.490
 > Your types are purrfect!                                       I@19:49:23.527
 > All expressions are typed                                      I@19:49:23.527
PASS #13: BoundedChecker                                          I@19:49:23.529
<unknown>: internal error in type checking: Unexpected operator type OperT1 E@19:49:24.099
at.forsyte.apalache.tla.lir.TypingException: Unexpected operator type OperT1
        at at.forsyte.apalache.tla.bmcmt.types.package$CellT$.fromType1(package.scala:185)
        at at.forsyte.apalache.tla.bmcmt.types.package$CellT$.fromType1(package.scala:173)
        at at.forsyte.apalache.tla.bmcmt.types.package$CellT$.fromTypeTag(package.scala:196)
        at at.forsyte.apalache.tla.bmcmt.rules.SetCtorRule.apply(SetCtorRule.scala:31)
        at at.forsyte.apalache.tla.bmcmt.SymbStateRewriterImpl.rewriteOnce(SymbStateRewriterImpl.scala:325)
        at at.forsyte.apalache.tla.bmcmt.SymbStateRewriterImpl.doRecursive$1(SymbStateRewriterImpl.scala:356)
        at at.forsyte.apalache.tla.bmcmt.SymbStateRewriterImpl.rewriteUntilDone(SymbStateRewriterImpl.scala:390)
        at at.forsyte.apalache.tla.bmcmt.rules.SetInRule.apply(SetInRule.scala:45)
        at at.forsyte.apalache.tla.bmcmt.SymbStateRewriterImpl.rewriteOnce(SymbStateRewriterImpl.scala:325)
        at at.forsyte.apalache.tla.bmcmt.SymbStateRewriterImpl.doRecursive$1(SymbStateRewriterImpl.scala:356)
        at at.forsyte.apalache.tla.bmcmt.SymbStateRewriterImpl.rewriteUntilDone(SymbStateRewriterImpl.scala:390)
        at at.forsyte.apalache.tla.bmcmt.rules.AssignmentRule.apply(AssignmentRule.scala:39)
        at at.forsyte.apalache.tla.bmcmt.SymbStateRewriterImpl.rewriteOnce(SymbStateRewriterImpl.scala:325)
        at at.forsyte.apalache.tla.bmcmt.SymbStateRewriterImpl.doRecursive$1(SymbStateRewriterImpl.scala:356)
        at at.forsyte.apalache.tla.bmcmt.SymbStateRewriterImpl.rewriteUntilDone(SymbStateRewriterImpl.scala:390)
        at at.forsyte.apalache.tla.bmcmt.trex.TransitionExecutorImpl.prepareTransition(TransitionExecutorImpl.scala:100)
        at at.forsyte.apalache.tla.bmcmt.trex.FilteredTransitionExecutor.prepareTransition(FilteredTransitionExecutor.scala:34)
        at at.forsyte.apalache.tla.bmcmt.trex.ConstrainedTransitionExecutor.prepareTransition(ConstrainedTransitionExecutor.scala:93)
        at at.forsyte.apalache.tla.bmcmt.SeqModelChecker.$anonfun$prepareTransitionsAndCheckInvariants$6(SeqModelChecker.scala:151)
        at at.forsyte.apalache.tla.bmcmt.SeqModelChecker.$anonfun$prepareTransitionsAndCheckInvariants$6$adapted(SeqModelChecker.scala:145)
        at scala.collection.TraversableLike$WithFilter.$anonfun$foreach$1(TraversableLike.scala:985)
        at scala.collection.immutable.List.foreach(List.scala:431)
        at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:984)
        at at.forsyte.apalache.tla.bmcmt.SeqModelChecker.prepareTransitionsAndCheckInvariants(SeqModelChecker.scala:145)
        at at.forsyte.apalache.tla.bmcmt.SeqModelChecker.makeStep(SeqModelChecker.scala:67)
        at at.forsyte.apalache.tla.bmcmt.SeqModelChecker.run(SeqModelChecker.scala:51)
        at at.forsyte.apalache.tla.bmcmt.passes.BoundedCheckerPassImpl.runIncrementalChecker(BoundedCheckerPassImpl.scala:128)
        at at.forsyte.apalache.tla.bmcmt.passes.BoundedCheckerPassImpl.execute(BoundedCheckerPassImpl.scala:92)
        at at.forsyte.apalache.infra.passes.PassChainExecutor.exec$1(PassChainExecutor.scala:24)
        at at.forsyte.apalache.infra.passes.PassChainExecutor.run(PassChainExecutor.scala:48)
        at at.forsyte.apalache.tla.Tool$.runAndExit(Tool.scala:170)
        at at.forsyte.apalache.tla.Tool$.runCheck(Tool.scala:253)
        at at.forsyte.apalache.tla.Tool$.$anonfun$run$2(Tool.scala:113)
        at at.forsyte.apalache.tla.Tool$.$anonfun$run$2$adapted(Tool.scala:113)
        at at.forsyte.apalache.tla.Tool$.handleExceptions(Tool.scala:400)
        at at.forsyte.apalache.tla.Tool$.run(Tool.scala:113)
        at at.forsyte.apalache.tla.Tool$.main(Tool.scala:52)
        at at.forsyte.apalache.tla.Tool.main(Tool.scala)
Please report an issue at [https://github.com/informalsystems/apalache/issues]: at.forsyte.apalache.tla.lir.TypingException: Unexpected operator type OperT1
A bug report template has been generated at [BugReport.md].
If you choose to use it, please complete the template with a description of the expected behavior.
It took me 0 days  0 hours  0 min  2 sec                          I@19:49:24.140
Total time: 2.186 sec                                             I@19:49:24.140
EXITCODE: ERROR (255)
```

## System information

- Apalache version [`apalache-mc version`]: 0.20.2
- OS [e.g. Ubuntu Linux or Mac OS, and the current version]: Ubuntu 20.04
- JDK version [e.g. OpenJDK 0.8.0]:

**Comment by Kukovec** [comment]
I suspect the problem is this line:
```
\* @type: Set(Bool)
```
It's missing a terminating `;`. so it's not being parsed as a type annotation.

**Comment by craft095** [comment]
Indeed, thank you @Kukovec! Perhaps, better error would be helpful in this case..

**Comment by konnov** [comment]
> Indeed, thank you @Kukovec! Perhaps, better error would be helpful in this case..

True. We had the annotation preprocessor reporting an error in this case. Unfortunately, TLA+ Toolbox is generating `MC.tla` files that contain something like this:

```
\* CONSTANT definitions @modelParameterConstants:0Counter
```

**Comment by konnov** [comment]
It shows that we need a final preprocessing pass that would complain about polymorphic definitions, if they can reach the model checker.
