### ISSUE TITLE
Make does not work on Windows

### ISSUE THREAD

**Issue by p-offtermatt** [informalsystems/apalache#1596]
Running `sbt apalacheCurrentPackage` gives an error on Windows 11:

```[error] java.io.IOException: Cannot run program "ln": CreateProcess error=2, The system cannot find the file specified
[error]         at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1128)
[error]         at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
[error]         at scala.sys.process.ProcessBuilderImpl$Simple.run(ProcessBuilderImpl.scala:75)
[error]         at scala.sys.process.ProcessBuilderImpl$AbstractBuilder.run(ProcessBuilderImpl.scala:106)
[error]         at scala.sys.process.ProcessBuilderImpl$AbstractBuilder.$anonfun$runBuffered$1(ProcessBuilderImpl.scala:154)
[error]         at scala.runtime.java8.JFunction0$mcI$sp.apply(JFunction0$mcI$sp.java:23)
[error]         at sbt.internal.util.BufferedLogger.buffer(BufferedLogger.scala:151)
[error]         at scala.sys.process.ProcessBuilderImpl$AbstractBuilder.runBuffered(ProcessBuilderImpl.scala:154)
[error]         at scala.sys.process.ProcessBuilderImpl$AbstractBuilder.$bang(ProcessBuilderImpl.scala:120)
[error]         at $c13783896b63ff10eb4d$.$anonfun$root$7(build.sbt:295)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error]         at sbt.std.Transform$$anon$4.work(Transform.scala:68)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:282)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
[error]         at sbt.Execute.work(Execute.scala:291)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:282)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:64)
[error]         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error]         at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[error]         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error]         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[error]         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[error]         at java.base/java.lang.Thread.run(Thread.java:829)
[error] Caused by: java.io.IOException: CreateProcess error=2, The system cannot find the file specified
[error]         at java.base/java.lang.ProcessImpl.create(Native Method)
[error]         at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:487)
[error]         at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:154)
[error]         at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1107)
[error]         at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
[error]         at sbt.internal.util.BufferedLogger.buffer(BufferedLogger.scala:151)
[error]         at scala.sys.process.ProcessBuilderImpl$AbstractBuilder.runBuffered(ProcessBuilderImpl.scala:154)
[error]         at scala.sys.process.ProcessBuilderImpl$AbstractBuilder.$bang(ProcessBuilderImpl.scala:120)
[error]         at $c13783896b63ff10eb4d$.$anonfun$root$7(build.sbt:295)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error]         at sbt.std.Transform$$anon$4.work(Transform.scala:68)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:282)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
[error]         at sbt.Execute.work(Execute.scala:291)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:282)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:64)
[error]         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error]         at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[error]         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error]         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[error]         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[error]         at java.base/java.lang.Thread.run(Thread.java:829)
[error] (apalacheCurrentPackage) java.io.IOException: Cannot run program "ln": CreateProcess error=2, The system cannot find the file specified
```

![Screenshot 2022-04-05 142442](https://user-images.githubusercontent.com/57488781/161753408-6a161079-1728-4415-82bd-7181b44b711f.png)

It is caused by the line `s"ln -sfn ${unzipped} ${current_pkg}" ! log`
https://github.com/informalsystems/apalache/blob/c9bc39b9543413c94e38eb349c5a560b8407a28a/build.sbt#L295

On Windows, ln does not exist, see https://superuser.com/questions/182553/does-windows-have-the-ln-s-or-equivalent

Changing the line to this (seems to) work:
`s"cmd /c mklink /D ${current_pkg} ${unzipped}" ! log`

Potentially one could detect the OS and execute a different command depending on it

**Comment by thpani** [comment]
I'm curious, the `tar` command 2 lines above the `ln` worked on Windows?

**Comment by p-offtermatt** [comment]
Yes, tar is available by default on my machine.

**Comment by p-offtermatt** [comment]
Thanks for the pointer!

**Comment by p-offtermatt** [comment]
I was able to run this after disabling UAC, by editing the registry key `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System` and switching `EnableLUA` to 0. This doesn't seem to be very advisable in general, but was the only way I got it to work.
