### ISSUE TITLE
Unhandled exception: Operator Test with arity 0 called with 1 argument(s)

### ISSUE THREAD

**Issue by MirelEthernal** [informalsystems/apalache#1674]
## Description
Generating traces with apalache causes an unhandled exception to occur. Since I'm working on extension of existing TLA+ model that can not be shared publicly, It was agreed with @konnov to send him the TLA+ model if needed. 

## Input specification

 
The actual state invariant that is causing the issue is:
```
Test == 
    outcome_status /= TEST
```
Where: `outcome_status: Str` models different outcome_statuses of executed transactions on cosmos -sdk chain.
Where TEST is defined: `TEST == "TEST"`

With removal of Test invariant from authz_test.tla, apalache  generates traces.

## The command line parameters used to run the tool

Apalache was run with simple input arguments, but it does not make any difference:
 check --max-error=3 --inv=GrantSuccessCEX authz_test.tla

## Expected behavior

Apalache generates traces successfully for desired invariant.

## Log files

Here is [detailed.log](https://github.com/informalsystems/apalache/files/8566982/detailed.log) attached - with stack trace.

<details>
  <summary>CLI Output</summary>
  
  ```
 apalache check --max-error=3 --inv=GrantSuccessCEX  authz_test.tla
# APALACHE
# version: 0.23.1
# build  : eec2386
#
# Usage statistics is OFF. We care about your privacy.
# If you want to help our project, consider enabling statistics with config --enable-stats=true.

Output directory: /home/mirel/Documents/AuditProjects/apalache errors/TLA files for reproduction of Bug/_apalache-out/authz_test.tla/2022-04-26T23-13-54_4382523054180953850
Checker options: check --max-error=3 --inv=GrantSuccessCEX authz_test.tla I@23:13:54.771
Tuning:                                                           I@23:13:54.779
PASS #0: SanyParser                                               I@23:13:54.785
Parsing file /home/mirel/Documents/AuditProjects/apalache errors/TLA files for reproduction of Bug/authz_test.tla
Parsing file /home/mirel/Documents/AuditProjects/apalache errors/TLA files for reproduction of Bug/authz.tla
Parsing file /tmp/Integers.tla
Parsing file /tmp/FiniteSets.tla
Parsing file /tmp/__rewire_sequences_in_apalache.tla
Parsing file /home/mirel/Documents/AuditProjects/apalache errors/TLA files for reproduction of Bug/helper_predicates.tla
Parsing file /tmp/__rewire_tlc_in_apalache.tla
Parsing file /tmp/Naturals.tla
Parsing file /home/mirel/Documents/AuditProjects/apalache errors/TLA files for reproduction of Bug/generic_authz.tla
Parsing file /home/mirel/Documents/AuditProjects/apalache errors/TLA files for reproduction of Bug/stake_authz.tla
Parsing file /home/mirel/Documents/AuditProjects/apalache errors/TLA files for reproduction of Bug/authz_typedefs.tla
Parsing file /home/mirel/Documents/AuditProjects/apalache errors/TLA files for reproduction of Bug/send_authz.tla
Parsing file /home/mirel/Documents/AuditProjects/apalache errors/TLA files for reproduction of Bug/statusCodes.tla
Parsing file /tmp/__apalache_folds.tla
PASS #1: TypeCheckerSnowcat                                       I@23:13:55.901
 > Running Snowcat .::.                                           I@23:13:55.902
 > Your types are purrfect!                                       I@23:13:57.249
 > All expressions are typed                                      I@23:13:57.249
PASS #2: ConfigurationPass                                        I@23:13:57.251
  > authz_test.cfg: Loading TLC configuration                     I@23:13:57.255
TLC config option VIEW identifier 'View' will be ignored          W@23:13:57.330
  > Using the init predicate Init from the TLC config             I@23:13:57.351
  > Using the next predicate Next from the TLC config             I@23:13:57.351
  > authz_test.cfg: found INVARIANTS: GrantSuccessCEX             I@23:13:57.351
  > Overriding with command line arguments: --inv GrantSuccessCEX W@23:13:57.352
  > Set the initialization predicate to Init                      I@23:13:57.354
  > Set the transition predicate to Next                          I@23:13:57.356
  > Set an invariant to GrantSuccessCEX                           I@23:13:57.357
  > Replaced CONSTANT AllSDKMessageTypes with {"msg_send", "msg_delegate", "msg_undelegate", "msg_redelegate", "msg_alpha"} I@23:13:57.361
  > Replaced CONSTANT Validators with {"X", "Y", "Z"}             I@23:13:57.365
  > Replaced CONSTANT MaxPossibleAmount with 10                   I@23:13:57.365
  > Replaced CONSTANT AllAuthorizationLogics with {"send", "stake", "generic"} I@23:13:57.367
  > Replaced CONSTANT Identifiers with {"A", "B", "C"}            I@23:13:57.367
PASS #3: DesugarerPass                                            I@23:13:57.409
  > Desugaring...                                                 I@23:13:57.409
PASS #4: UnrollPass                                               I@23:13:57.431
  > Unroller                                                      I@23:13:57.504
PASS #5: InlinePass                                               I@23:13:57.538
  > InlinerOfUserOper                                             I@23:13:57.539
(Please report an issue at: [https://github.com/informalsystems/apalache/issues],java.lang.IllegalArgumentException: Operator Test with arity 0 called with 1 argument(s).)
Unhandled exception                                               E@23:13:57.580
java.lang.IllegalArgumentException: Operator Test with arity 0 called with 1 argument(s).
        at at.forsyte.apalache.tla.pp.InlinerOfUserOper.$anonfun$transform$1(InlinerOfUserOper.scala:56)
        at at.forsyte.apalache.tla.lir.transformations.impl.TrackerWithListeners.$anonfun$trackEx$1(TrackerWithListeners.scala:18)
        at scala.collection.immutable.List.map(List.scala:293)
        at at.forsyte.apalache.tla.pp.InlinerOfUserOper.$anonfun$transform$1(InlinerOfUserOper.scala:80)
        at at.forsyte.apalache.tla.lir.transformations.impl.TrackerWithListeners.$anonfun$trackEx$1(TrackerWithListeners.scala:18)
        at at.forsyte.apalache.tla.pp.InlinerOfUserOper.$anonfun$transform$2(InlinerOfUserOper.scala:70)
        at at.forsyte.apalache.tla.lir.transformations.impl.TrackerWithListeners.$anonfun$trackOperDecl$1(TrackerWithListeners.scala:71)
        at scala.collection.immutable.List.map(List.scala:293)
        at at.forsyte.apalache.tla.pp.InlinerOfUserOper.$anonfun$transform$1(InlinerOfUserOper.scala:69)
        at at.forsyte.apalache.tla.lir.transformations.impl.TrackerWithListeners.$anonfun$trackEx$1(TrackerWithListeners.scala:18)
        at at.forsyte.apalache.tla.pp.InlinerOfUserOper.apply(InlinerOfUserOper.scala:35)
        at at.forsyte.apalache.tla.pp.InlinerOfUserOper.apply(InlinerOfUserOper.scala:22)
        at at.forsyte.apalache.tla.lir.transformations.standard.ModuleByExTransformer.$anonfun$apply$1(ModuleByExTransformer.scala:19)
        at at.forsyte.apalache.tla.lir.transformations.standard.ModuleByExTransformer.mapIfIncluded$1(ModuleByExTransformer.scala:39)
        at at.forsyte.apalache.tla.lir.transformations.standard.ModuleByExTransformer.$anonfun$apply$2(ModuleByExTransformer.scala:45)
        at scala.collection.immutable.List.map(List.scala:297)
        at at.forsyte.apalache.tla.lir.transformations.standard.ModuleByExTransformer.apply(ModuleByExTransformer.scala:45)
        at at.forsyte.apalache.tla.pp.passes.PartialInlinePassImpl.$anonfun$execute$1(PartialInlinePassImpl.scala:31)
        at scala.collection.LinearSeqOptimized.foldLeft(LinearSeqOptimized.scala:126)
        at scala.collection.LinearSeqOptimized.foldLeft$(LinearSeqOptimized.scala:122)
        at scala.collection.immutable.List.foldLeft(List.scala:91)
        at at.forsyte.apalache.tla.pp.passes.PartialInlinePassImpl.execute(PartialInlinePassImpl.scala:27)
        at at.forsyte.apalache.infra.passes.PassChainExecutor.exec$1(PassChainExecutor.scala:22)
        at at.forsyte.apalache.infra.passes.PassChainExecutor.$anonfun$run$3(PassChainExecutor.scala:44)
        at scala.Option.flatMap(Option.scala:271)
        at at.forsyte.apalache.infra.passes.PassChainExecutor.$anonfun$run$1(PassChainExecutor.scala:43)
        at scala.collection.LinearSeqOptimized.foldLeft(LinearSeqOptimized.scala:126)
        at scala.collection.LinearSeqOptimized.foldLeft$(LinearSeqOptimized.scala:122)
        at scala.collection.immutable.List.foldLeft(List.scala:91)
        at at.forsyte.apalache.infra.passes.PassChainExecutor.run(PassChainExecutor.scala:37)
        at at.forsyte.apalache.tla.Tool$.runAndExit(Tool.scala:169)
        at at.forsyte.apalache.tla.Tool$.runCheck(Tool.scala:248)
        at at.forsyte.apalache.tla.Tool$.$anonfun$run$2(Tool.scala:115)
        at at.forsyte.apalache.tla.Tool$.$anonfun$run$2$adapted(Tool.scala:115)
        at at.forsyte.apalache.tla.Tool$.handleExceptions(Tool.scala:404)
        at at.forsyte.apalache.tla.Tool$.runForModule(Tool.scala:394)
        at at.forsyte.apalache.tla.Tool$.run(Tool.scala:115)
        at at.forsyte.apalache.tla.Tool$.main(Tool.scala:53)
        at at.forsyte.apalache.tla.Tool.main(Tool.scala)
It took me 0 days  0 hours  0 min  3 sec                          I@23:13:57.583
Total time: 3.611 sec                                             I@23:13:57.584
EXITCODE: ERROR (255)

```
</details>

## System information

- Apalache version [`apalache-mc version`]: 0.23.1
- OS [e.g. Ubuntu Linux or Mac OS, and the current version]: Ubuntu Linux
- JDK version [e.g. OpenJDK 0.8.0]: java-8-openjdk
```

**Comment by Kukovec** [comment]
I noticed you're on version `0.23.1` and the source of the exception seems to be `InlinerOfUserOper`, which is no longer in use. There has been a significant change to inlining recently and version `0.24.X` uses a different inliner. Could you please try with the latest version?

**Comment by MirelEthernal** [comment]
It works fine with v0.24.1.
I was looking into release notes for choosing a newer version, but haven't seen the details about inliner rewiring done in the meantime with [PR 1569](https://github.com/informalsystems/apalache/pull/1569) - so I actually downgraded to an older version. Thanks for pointing me to the appropriate version!
