### ISSUE TITLE
Strange counterexample with function with Int domain

### ISSUE THREAD

**Issue by nano-o** [informalsystems/apalache#1798]
Consider the following:
```
----------------------------- MODULE Test -----------------------------
EXTENDS Integers
VARIABLES
    \* @type: Int -> Int;
    f
Init == f = [[i \in Int |-> 0] EXCEPT ![0] = 42]
Next == UNCHANGED f
Inv == f[0]=42
=============================================================================
```
Run Apalache with options `check --inv=Inv --length=0`.
This fails with a strange counterexample:
```
---------------------------- MODULE counterexample ----------------------------

EXTENDS TestGuess

(* Constant initialization state *)
ConstInit == TRUE

(* Initial state *)
State0 == f = SetAsFun({})

(* The following formula holds true in the last state and violates the invariant *)
InvariantViolation == ~(f[0] = 42)

================================================================================
```

**Comment by nano-o** [comment]
And with `--smt-encoding=array` Apalache crashes:
```
PASS #12: BoundedChecker                                          I@16:20:45.591
(Please report an issue at: [https://github.com/informalsystems/apalache/issues],java.lang.ClassCastException: class com.microsoft.z3.Expr cannot be cast to class com.microsoft.z3.ArrayExpr (com.microsoft.z3.Expr and com.microsoft.z3.ArrayExpr are in unnamed module of loader 'app'))
Unhandled exception                                               E@16:20:45.817
java.lang.ClassCastException: class com.microsoft.z3.Expr cannot be cast to class com.microsoft.z3.ArrayExpr (com.microsoft.z3.Expr and com.microsoft.z3.ArrayExpr are in unnamed module of loader 'app')
        at at.forsyte.apalache.tla.bmcmt.smt.Z3SolverContext.mkSelect(Z3SolverContext.scala:227)
        at at.forsyte.apalache.tla.bmcmt.smt.Z3SolverContext.toExpr(Z3SolverContext.scala:698)
        at at.forsyte.apalache.tla.bmcmt.smt.Z3SolverContext.toExpr(Z3SolverContext.scala:672)
        at at.forsyte.apalache.tla.bmcmt.smt.Z3SolverContext.assertGroundExpr(Z3SolverContext.scala:313)
        at at.forsyte.apalache.tla.bmcmt.smt.RecordingSolverContext.assertGroundExpr(RecordingSolverContext.scala:157)
        at at.forsyte.apalache.tla.bmcmt.rules.FunExceptRuleWithArrays.rewriteFun(FunExceptRuleWithArrays.scala:74)
        at at.forsyte.apalache.tla.bmcmt.rules.FunExceptRule.apply(FunExceptRule.scala:48)
        at at.forsyte.apalache.tla.bmcmt.SymbStateRewriterImpl.rewriteOnce(SymbStateRewriterImpl.scala:345)
        at at.forsyte.apalache.tla.bmcmt.SymbStateRewriterImpl.doRecursive$1(SymbStateRewriterImpl.scala:378)
        at at.forsyte.apalache.tla.bmcmt.SymbStateRewriterImpl.rewriteUntilDone(SymbStateRewriterImpl.scala:412)
        at at.forsyte.apalache.tla.bmcmt.rules.AssignmentRule.apply(AssignmentRule.scala:37)
        at at.forsyte.apalache.tla.bmcmt.SymbStateRewriterImpl.rewriteOnce(SymbStateRewriterImpl.scala:345)
        at at.forsyte.apalache.tla.bmcmt.SymbStateRewriterImpl.doRecursive$1(SymbStateRewriterImpl.scala:378)
        at at.forsyte.apalache.tla.bmcmt.SymbStateRewriterImpl.rewriteUntilDone(SymbStateRewriterImpl.scala:412)
        at at.forsyte.apalache.tla.bmcmt.trex.TransitionExecutorImpl.prepareTransition(TransitionExecutorImpl.scala:106)
        at at.forsyte.apalache.tla.bmcmt.trex.FilteredTransitionExecutor.prepareTransition(FilteredTransitionExecutor.scala:41)
        at at.forsyte.apalache.tla.bmcmt.trex.ConstrainedTransitionExecutor.prepareTransition(ConstrainedTransitionExecutor.scala:97)
        at at.forsyte.apalache.tla.bmcmt.SeqModelChecker.$anonfun$prepareTransitionsAndCheckInvariants$6(SeqModelChecker.scala:179)
        at at.forsyte.apalache.tla.bmcmt.SeqModelChecker.$anonfun$prepareTransitionsAndCheckInvariants$6$adapted(SeqModelChecker.scala:173)
        at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:563)
        at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:561)
        at scala.collection.AbstractIterable.foreach(Iterable.scala:926)
        at scala.collection.IterableOps$WithFilter.foreach(Iterable.scala:896)
        at at.forsyte.apalache.tla.bmcmt.SeqModelChecker.prepareTransitionsAndCheckInvariants(SeqModelChecker.scala:173)
        at at.forsyte.apalache.tla.bmcmt.SeqModelChecker.makeStep(SeqModelChecker.scala:95)
        at at.forsyte.apalache.tla.bmcmt.SeqModelChecker.run(SeqModelChecker.scala:56)
        at at.forsyte.apalache.tla.bmcmt.passes.BoundedCheckerPassImpl.runIncrementalChecker(BoundedCheckerPassImpl.scala:128)
        at at.forsyte.apalache.tla.bmcmt.passes.BoundedCheckerPassImpl.execute(BoundedCheckerPassImpl.scala:86)
        at at.forsyte.apalache.infra.passes.PassChainExecutor.exec$1(PassChainExecutor.scala:23)
        at at.forsyte.apalache.infra.passes.PassChainExecutor.$anonfun$run$5(PassChainExecutor.scala:47)
        at scala.util.Either.flatMap(Either.scala:352)
        at at.forsyte.apalache.infra.passes.PassChainExecutor.$anonfun$run$3(PassChainExecutor.scala:46)
        at scala.collection.LinearSeqOps.foldLeft(LinearSeq.scala:169)
        at scala.collection.LinearSeqOps.foldLeft$(LinearSeq.scala:165)
        at scala.collection.immutable.List.foldLeft(List.scala:79)
        at at.forsyte.apalache.infra.passes.PassChainExecutor.run(PassChainExecutor.scala:41)
        at at.forsyte.apalache.tla.Tool$.runAndExit(Tool.scala:187)
        at at.forsyte.apalache.tla.Tool$.runCheck(Tool.scala:266)
        at at.forsyte.apalache.tla.Tool$.$anonfun$run$2(Tool.scala:130)
        at at.forsyte.apalache.tla.Tool$.$anonfun$run$2$adapted(Tool.scala:130)
        at at.forsyte.apalache.tla.Tool$.handleExceptions(Tool.scala:423)
        at at.forsyte.apalache.tla.Tool$.runForModule(Tool.scala:413)
        at at.forsyte.apalache.tla.Tool$.run(Tool.scala:130)
        at at.forsyte.apalache.tla.Tool$.main(Tool.scala:47)
        at at.forsyte.apalache.tla.Tool.main(Tool.scala)
```

**Comment by konnov** [comment]
Hi @nano-o!

In principle, it should not have passed the preprocessor, but it did. We only support `Int` and `Nat` in a Skolemizable `\E x \in S: P`, which essentially introduces a single integer constant in SMT.

In general, the current encoding is working over bounded data structures, whose shape can be statically overapproximated. For instance, `[ x \in { a, b, c } |-> e ]` should pose no problem even when the contents of `a`, `b`, and `c` cannot be statically computed, since we know that the domain contains up to three elements.

Likewise, `M..N` poses no problem, if `M` and `N` are constants or expressions over constants. However, we would not be able to encode `x..y`, as the cardinality is unbounded in general. In this case, one can usually do something `{ x \in M..N: a <= x /\ x <= b }`.

Even though we are experimenting with the arrays encoding, we are not using quantifiers. This is where all these restrictions are coming from.
