### ISSUE TITLE
Trace invariant checking not working as expected

### ISSUE THREAD

**Issue by andrey-kuprianov** [informalsystems/apalache#1827]
## Input specification

```
----- MODULE HourClock -----

EXTENDS Naturals, Sequences
VARIABLES 
  \* @typeAlias: STATE = [ hr: Int ];
  \* @type: Int;
  hr
Init == hr \in (1..12)
Next == hr' = IF hr /= 12 THEN hr + 1 ELSE 1

ExHourDecrease == hr' < hr
InvExHourDecrease == ~ExHourDecrease

\* @type: Seq(STATE) => Bool
ExFullRun(trace) == Len(trace) = 12

\* @type: Seq(STATE) => Bool
InvExFullRun(trace) == ~ExFullRun(trace)

InvNoOverflow  == hr <= 12
InvNoUnderflow  == hr >= 1

=============================
````

## The command line parameters used to run the tool

```
--init=Init --next=Next --inv=InvExFullRun
```

## Expected behavior

An counterexample trace that violates the trace invariant is generated. 

## Log files

```
10:12:38.701 [main] INFO  a.f.a.t.Tool\$ - # APALACHE version: 0.25.3 | build: 72baae9
10:12:39.207 [main] INFO  a.f.a.t.Tool\$ - Checker options: check --init=Init --next=Next --inv=InvExFullRun HourClock.tla
10:12:39.210 [main] INFO  a.f.a.t.Tool\$ - Tuning: 
10:12:39.217 [main] INFO  a.f.a.i.p.PassChainExecutor - PASS #0: SanyParser
10:12:39.681 [main] WARN  a.f.a.t.i.AnnotationExtractor - [HourClock:15:1-15:35]: Syntax error in annotation -- Unexpected character. Missing ')' or ';'?
10:12:39.709 [main] WARN  a.f.a.t.i.AnnotationExtractor - [HourClock:18:1-18:40]: Syntax error in annotation -- Unexpected character. Missing ')' or ';'?
10:12:39.761 [main] DEBUG a.f.a.i.p.PassChainExecutor - PASS #0: SanyParser [OK]
10:12:39.762 [main] INFO  a.f.a.i.p.PassChainExecutor - PASS #1: TypeCheckerSnowcat
10:12:39.762 [main] INFO  a.f.a.t.t.p.EtcTypeCheckerPassImpl -  > Running Snowcat .::.
10:12:40.225 [main] INFO  a.f.a.t.t.p.EtcTypeCheckerPassImpl -  > Your types are purrfect!
10:12:40.226 [main] INFO  a.f.a.t.t.p.EtcTypeCheckerPassImpl -  > All expressions are typed
10:12:40.227 [main] DEBUG a.f.a.i.p.PassChainExecutor - PASS #1: TypeCheckerSnowcat [OK]
10:12:40.228 [main] INFO  a.f.a.i.p.PassChainExecutor - PASS #2: ConfigurationPass
10:12:40.237 [main] INFO  a.f.a.t.p.p.ConfigurationPassImpl -   > Set the initialization predicate to Init
10:12:40.237 [main] INFO  a.f.a.t.p.p.ConfigurationPassImpl -   > Set the transition predicate to Next
10:12:40.238 [main] INFO  a.f.a.t.p.p.ConfigurationPassImpl -   > Set an invariant to InvExFullRun
10:12:40.246 [main] DEBUG a.f.a.i.p.PassChainExecutor - PASS #2: ConfigurationPass [OK]
10:12:40.247 [main] INFO  a.f.a.i.p.PassChainExecutor - PASS #3: DesugarerPass
10:12:40.247 [main] INFO  a.f.a.t.p.p.DesugarerPassImpl -   > Desugaring...
10:12:40.253 [main] DEBUG a.f.a.i.p.PassChainExecutor - PASS #3: DesugarerPass [OK]
10:12:40.254 [main] INFO  a.f.a.i.p.PassChainExecutor - PASS #4: InlinePass
10:12:40.255 [main] INFO  a.f.a.t.p.p.InlinePassImpl - Leaving only relevant operators: CInitPrimed, Init, InitPrimed, InvExFullRun, Next
10:12:40.300 [main] DEBUG a.f.a.i.p.PassChainExecutor - PASS #4: InlinePass [OK]
10:12:40.301 [main] INFO  a.f.a.i.p.PassChainExecutor - PASS #5: PrimingPass
10:12:40.303 [main] INFO  a.f.a.t.a.p.PrimingPassImpl -   > Introducing InitPrimed for Init'
10:12:40.306 [main] DEBUG a.f.a.i.p.PassChainExecutor - PASS #5: PrimingPass [OK]
10:12:40.307 [main] INFO  a.f.a.i.p.PassChainExecutor - PASS #6: VCGen
10:12:40.307 [main] INFO  a.f.a.t.b.p.VCGenPassImpl -   > Producing verification conditions from the invariant InvExFullRun
10:12:40.326 [main] ERROR a.f.a.t.Tool\$ - HourClock.tla:18:24-18:40: unexpected TLA+ expression: Expected the trace invariant InvExFullRun to be a predicate of a sequence of records over the names of state variables
at.forsyte.apalache.tla.lir.MalformedTlaError: Expected the trace invariant InvExFullRun to be a predicate of a sequence of records over the names of state variables
	at at.forsyte.apalache.tla.bmcmt.VCGenerator.assertTraceInvType(VCGenerator.scala:116)
	at at.forsyte.apalache.tla.bmcmt.VCGenerator.gen(VCGenerator.scala:61)
	at at.forsyte.apalache.tla.bmcmt.passes.VCGenPassImpl.\$anonfun\$execute\$1(VCGenPassImpl.scala:33)
	at scala.collection.LinearSeqOps.foldLeft(LinearSeq.scala:169)
	at scala.collection.LinearSeqOps.foldLeft\$(LinearSeq.scala:165)
	at scala.collection.immutable.List.foldLeft(List.scala:79)
	at at.forsyte.apalache.tla.bmcmt.passes.VCGenPassImpl.execute(VCGenPassImpl.scala:27)
	at at.forsyte.apalache.infra.passes.PassChainExecutor.exec\$1(PassChainExecutor.scala:23)
	at at.forsyte.apalache.infra.passes.PassChainExecutor.\$anonfun\$run\$5(PassChainExecutor.scala:47)
	at scala.util.Either.flatMap(Either.scala:352)
	at at.forsyte.apalache.infra.passes.PassChainExecutor.\$anonfun\$run\$3(PassChainExecutor.scala:46)
	at scala.collection.LinearSeqOps.foldLeft(LinearSeq.scala:169)
	at scala.collection.LinearSeqOps.foldLeft\$(LinearSeq.scala:165)
	at scala.collection.immutable.List.foldLeft(List.scala:79)
	at at.forsyte.apalache.infra.passes.PassChainExecutor.run(PassChainExecutor.scala:41)
	at at.forsyte.apalache.tla.Tool\$.runAndExit(Tool.scala:187)
	at at.forsyte.apalache.tla.Tool\$.runCheck(Tool.scala:266)
	at at.forsyte.apalache.tla.Tool\$.\$anonfun\$run\$2(Tool.scala:130)
	at at.forsyte.apalache.tla.Tool\$.\$anonfun\$run\$2\$adapted(Tool.scala:130)
	at at.forsyte.apalache.tla.Tool\$.handleExceptions(Tool.scala:423)
	at at.forsyte.apalache.tla.Tool\$.runForModule(Tool.scala:413)
	at at.forsyte.apalache.tla.Tool\$.run(Tool.scala:130)
	at at.forsyte.apalache.tla.Tool\$.main(Tool.scala:47)
	at at.forsyte.apalache.tla.Tool.main(Tool.scala)
```

## System information

- Apalache version: `0.25.3 build 72baae9`:
- OS: `Mac OS X`:
- JDK version: `15.0.3`:

**Comment by andrey-kuprianov** [comment]
It was missing semicolons in type declarations, sorry for the trouble!
