### ISSUE TITLE
Inliner: Unable to unify generic signature with the concrete type 

### ISSUE THREAD

**Issue by 17451k** [informalsystems/apalache#1885]
## Description

I have created a stripped down version of the model to demonstrate the issue.
It seems that the concrete type of Num ((Int) => Int) does not match to its annotation ([cycle: Int, index: Int]) => Int),
and I don't understand why.

## Impact

I was not able to find a workaround, so I am unable to check my model.

## Input specification

```
-------------------------------- MODULE bug --------------------------------
EXTENDS Integers

\* @type: (Int) => Int;
Cycle(x) == x \div 2

\* @type: (Int, Int) => Int;
Add(x, y) == x + y

\* @type: ([index: Int, cycle: Int]) => Int;
Num(e) ==2 * e.cycle + e.index

\* @type: ([index: Int, cycle: Int], [index: Int, cycle: Int]) => Bool;
OneCycleAhead(x, y) == Cycle(Num(x)) = Cycle(Add(Num(y), 2))

Init == TRUE
Next == TRUE
=============================================================================
````

## The command line parameters used to run the tool

```
apalache-mc check bug.tla
```

## Log files

```
11:59:52.986 [main] INFO  a.f.a.t.Tool\$ - # APALACHE version: 0.25.7 | build: 554bdb5
11:59:53.174 [main] INFO  a.f.a.t.Tool\$ - Checker options: check bug.tla
11:59:53.176 [main] INFO  a.f.a.t.Tool\$ - Tuning:
11:59:53.178 [main] INFO  a.f.a.i.p.PassChainExecutor - PASS #0: SanyParser
11:59:53.388 [main] DEBUG a.f.a.i.p.PassChainExecutor - PASS #0: SanyParser [OK]
11:59:53.389 [main] INFO  a.f.a.i.p.PassChainExecutor - PASS #1: TypeCheckerSnowcat
11:59:53.389 [main] INFO  a.f.a.t.t.p.EtcTypeCheckerPassImpl -  > Running Snowcat .::.
11:59:53.590 [main] INFO  a.f.a.t.t.p.EtcTypeCheckerPassImpl -  > Your types are purrfect!
11:59:53.590 [main] INFO  a.f.a.t.t.p.EtcTypeCheckerPassImpl -  > All expressions are typed
11:59:53.591 [main] DEBUG a.f.a.i.p.PassChainExecutor - PASS #1: TypeCheckerSnowcat [OK]
11:59:53.591 [main] INFO  a.f.a.i.p.PassChainExecutor - PASS #2: ConfigurationPass
11:59:53.596 [main] INFO  a.f.a.t.p.p.ConfigurationPassImpl -   > Command line option --init is not set. Using Init
11:59:53.596 [main] INFO  a.f.a.t.p.p.ConfigurationPassImpl -   > Command line option --next is not set. Using Next
11:59:53.596 [main] INFO  a.f.a.t.p.p.ConfigurationPassImpl -   > Set the initialization predicate to Init
11:59:53.597 [main] INFO  a.f.a.t.p.p.ConfigurationPassImpl -   > Set the transition predicate to Next
11:59:53.600 [main] DEBUG a.f.a.i.p.PassChainExecutor - PASS #2: ConfigurationPass [OK]
11:59:53.601 [main] INFO  a.f.a.i.p.PassChainExecutor - PASS #3: DesugarerPass
11:59:53.601 [main] INFO  a.f.a.t.p.p.DesugarerPassImpl -   > Desugaring...
11:59:53.607 [main] DEBUG a.f.a.i.p.PassChainExecutor - PASS #3: DesugarerPass [OK]
11:59:53.607 [main] INFO  a.f.a.i.p.PassChainExecutor - PASS #4: InlinePass
11:59:53.608 [main] INFO  a.f.a.t.p.p.InlinePassImpl - Leaving only relevant operators: CInitPrimed, Init, InitPrimed, Next
11:59:53.643 [main] ERROR a.f.a.t.Tool\$ - <unknown>: internal error in type checking: Inliner: Unable to unify generic signature (([cycle: Int, index: Int]) => Int) of Num with the concrete type ((Int) => Int)
at.forsyte.apalache.tla.lir.TypingException: Inliner: Unable to unify generic signature (([cycle: Int, index: Int]) => Int) of Num with the concrete type ((Int) => Int)
	at at.forsyte.apalache.tla.pp.Inliner.getSubstitution(Inliner.scala:98)
	at at.forsyte.apalache.tla.pp.Inliner.instantiateWithArgs(Inliner.scala:133)
	at at.forsyte.apalache.tla.pp.Inliner.\$anonfun\$transform\$1(Inliner.scala:168)
	at at.forsyte.apalache.tla.lir.transformations.impl.TrackerWithListeners.\$anonfun\$trackEx\$1(TrackerWithListeners.scala:18)
	at scala.collection.immutable.List.map(List.scala:246)
	at scala.collection.immutable.List.map(List.scala:79)
	at at.forsyte.apalache.tla.pp.Inliner.\$anonfun\$transform\$1(Inliner.scala:206)
	at at.forsyte.apalache.tla.lir.transformations.impl.TrackerWithListeners.\$anonfun\$trackEx\$1(TrackerWithListeners.scala:18)
	at at.forsyte.apalache.tla.pp.Inliner.instantiateWithArgs(Inliner.scala:124)
	at at.forsyte.apalache.tla.pp.Inliner.\$anonfun\$transform\$1(Inliner.scala:168)
	at at.forsyte.apalache.tla.lir.transformations.impl.TrackerWithListeners.\$anonfun\$trackEx\$1(TrackerWithListeners.scala:18)
	at scala.collection.immutable.List.map(List.scala:246)
	at scala.collection.immutable.List.map(List.scala:79)
	at at.forsyte.apalache.tla.pp.Inliner.\$anonfun\$transform\$1(Inliner.scala:206)
	at at.forsyte.apalache.tla.lir.transformations.impl.TrackerWithListeners.\$anonfun\$trackEx\$1(TrackerWithListeners.scala:18)
	at at.forsyte.apalache.tla.pp.Inliner.instantiateWithArgs(Inliner.scala:124)
	at at.forsyte.apalache.tla.pp.Inliner.\$anonfun\$transform\$1(Inliner.scala:168)
	at at.forsyte.apalache.tla.lir.transformations.impl.TrackerWithListeners.\$anonfun\$trackEx\$1(TrackerWithListeners.scala:18)
	at scala.collection.immutable.List.map(List.scala:250)
	at scala.collection.immutable.List.map(List.scala:79)
	at at.forsyte.apalache.tla.pp.Inliner.\$anonfun\$transform\$1(Inliner.scala:206)
	at at.forsyte.apalache.tla.lir.transformations.impl.TrackerWithListeners.\$anonfun\$trackEx\$1(TrackerWithListeners.scala:18)
	at at.forsyte.apalache.tla.pp.Inliner.\$anonfun\$pushDeclsIntoScope\$1(Inliner.scala:65)
	at scala.collection.LinearSeqOps.foldLeft(LinearSeq.scala:169)
	at scala.collection.LinearSeqOps.foldLeft\$(LinearSeq.scala:165)
	at scala.collection.immutable.List.foldLeft(List.scala:79)
	at at.forsyte.apalache.tla.pp.Inliner.pushDeclsIntoScope(Inliner.scala:61)
	at at.forsyte.apalache.tla.pp.Inliner.transformModule(Inliner.scala:224)
	at at.forsyte.apalache.tla.pp.passes.InlinePassImpl.execute(InlinePassImpl.scala:55)
	at at.forsyte.apalache.infra.passes.PassChainExecutor.exec\$1(PassChainExecutor.scala:23)
	at at.forsyte.apalache.infra.passes.PassChainExecutor.\$anonfun\$run\$5(PassChainExecutor.scala:47)
	at scala.util.Either.flatMap(Either.scala:352)
	at at.forsyte.apalache.infra.passes.PassChainExecutor.\$anonfun\$run\$3(PassChainExecutor.scala:46)
	at scala.collection.LinearSeqOps.foldLeft(LinearSeq.scala:169)
	at scala.collection.LinearSeqOps.foldLeft\$(LinearSeq.scala:165)
	at scala.collection.immutable.List.foldLeft(List.scala:79)
	at at.forsyte.apalache.infra.passes.PassChainExecutor.run(PassChainExecutor.scala:41)
	at at.forsyte.apalache.tla.Tool\$.runAndExit(Tool.scala:193)
	at at.forsyte.apalache.tla.Tool\$.runCheck(Tool.scala:282)
	at at.forsyte.apalache.tla.Tool\$.\$anonfun\$run\$3(Tool.scala:136)
	at at.forsyte.apalache.tla.Tool\$.\$anonfun\$run\$3\$adapted(Tool.scala:136)
	at at.forsyte.apalache.tla.Tool\$.handleExceptions(Tool.scala:440)
	at at.forsyte.apalache.tla.Tool\$.runForModule(Tool.scala:430)
	at at.forsyte.apalache.tla.Tool\$.run(Tool.scala:136)
	at at.forsyte.apalache.tla.Tool\$.main(Tool.scala:48)
	at at.forsyte.apalache.tla.Tool.main(Tool.scala)
```

## System information

- Apalache version: `0.25.7 build 554bdb5`:
- OS: `Linux`:
- JDK version: `17.0.3`:

**Comment by Kukovec** [comment]
Hi, thanks for submitting!
It just so happens that this gets fixed in a bugfix for another related issue, so you should be able to pull once https://github.com/informalsystems/apalache/pull/1886 has been merged in.
