### ISSUE TITLE
[BUG] Running check on a module without an Init operator raises an unhandeled exception

### ISSUE THREAD

**Issue by shonfeder** [informalsystems/apalache#193]
Running `check` on a `tla` file that doesn't define an `Init` operator results in an unhandeled exception:

**To Reproduce**

Create an empty module:

In `M.tla`:

```tla
---- MODULE M -----------------------------------------------------
================================================================================
```

Check it with apalache

```sh
$ apalache-mc check M.tla
```

**Expected behavior**

A user-friendly error message describing what's missing, with reference to documentation.

**Log files**

```
Checker options: filename=test/tla/tla-path-tests/ImportingModule.tla, init=, next=, inv= I@18:35:40.984
PASS #0: SanyParser                                               I@18:35:41.457
Parsing file /home/sf/Sync/informal-systems/apalache/apalache-core/test/tla/tla-path-tests/ImportingModule.tla
Parsing file /home/sf/Sync/informal-systems/apalache/apalache-core/test/tla/tla-path-tests/ImportedModule.tla
PASS #1: ConfigurationPass                                        I@18:35:41.746
  > Loading TLC configuration from ImportingModule.cfg            I@18:35:41.748
  > No TLC configuration found; skipping                          I@18:35:41.756
PASS #2: UnrollPass                                               I@18:35:41.769
  > Unroller                                                      I@18:35:41.774
PASS #3: InlinePass                                               I@18:35:41.791
  > InlinerOfUserOper                                             I@18:35:41.794
  > LetInExpander                                                 I@18:35:41.795
PASS #4: PrimingPass                                              I@18:35:41.798
  > Introducing InitPrimed for Init'                              I@18:35:41.803
(Please report an issue at: [https://github.com/informalsystems/apalache/issues],java.util.NoSuchElementException: key not found: Init)
Unhandled exception                                               E@18:35:41.811
java.util.NoSuchElementException: key not found: Init
	at scala.collection.MapLike.default(MapLike.scala:232)
	at scala.collection.MapLike.default$(MapLike.scala:231)
	at scala.collection.AbstractMap.default(Map.scala:59)
	at scala.collection.MapLike.apply(MapLike.scala:141)
	at scala.collection.MapLike.apply$(MapLike.scala:140)
	at scala.collection.AbstractMap.apply(Map.scala:59)
	at at.forsyte.apalache.tla.assignments.passes.PrimingPassImpl.execute(PrimingPassImpl.scala:63)
	at at.forsyte.apalache.infra.passes.PassChainExecutor.exec$1(PassChainExecutor.scala:23)
	at at.forsyte.apalache.infra.passes.PassChainExecutor.run(PassChainExecutor.scala:38)
	at at.forsyte.apalache.tla.Tool$.runCheck(Tool.scala:147)
	at at.forsyte.apalache.tla.Tool$.$anonfun$run$2(Tool.scala:81)
	at at.forsyte.apalache.tla.Tool$.$anonfun$run$2$adapted(Tool.scala:81)
	at at.forsyte.apalache.tla.Tool$.handleExceptions(Tool.scala:196)
	at at.forsyte.apalache.tla.Tool$.run(Tool.scala:81)
	at at.forsyte.apalache.tla.Tool$.main(Tool.scala:42)
	at at.forsyte.apalache.tla.Tool.main(Tool.scala)
```

**Desktop (please complete the following information):**
 - OS: Arch
 - JDK version "1.8.0_252"
 - Version 0.7.0

This should be a relatively easy beginner issue for the code bas, so I'll take this if no one objects.

**Comment by shonfeder** [comment]
We can probably also improve the user error produced when `Next` is missing. Currently it gives us `Assignment error: Failed to find assignments and symbolic transitions in Next`, but it would be more helpful if it tells the user something like `No 'Next' operator was defined. All models must define a 'Next' operator specifying the transition between states`.

**Comment by konnov** [comment]
I am actually fixing that, so do not start working on this issue
