### ISSUE TITLE
ClassCastException when checking a temporal property

### ISSUE THREAD

**Issue by konnov** [informalsystems/apalache#2107]
## Impact

This is not blocking. This bug appears when I am trying to check the temporal property `Validity0`.

## Input specification

```
------------------------- MODULE MC_4_1_1_edac ------------------------------
EXTENDS edac_typedefs, edac_vars

Values == { 0, 1 }
N == 4
T == 1
F == 1

INSTANCE edac

Validity0 ==
    (\A p \in P : state[p].W = {0})
      => [](\A q \in P:
              (q \notin failed /\ state[q].decision # Nil)
                => state[q].decision = 0)

=============================================================================

--------------------------- MODULE edac_typedefs ------------------------------
EXTENDS Variants

(*
  @typeAlias: procstate = { W: Set(Int), halt: Bool, decision: Int };
  @typeAlias: msg = W(Set(Int)) | D(Int) | None(UNIT);
 *)
edac_typedefs == TRUE

\* @type: Set(Int) => $msg;
W(values) == Variant("W", values)

\* @type: Int => $msg;
D(value) == Variant("D", value)

\* @type: () => $msg;
NilMsg == Variant("None", "unit_OF_UNIT")
==============================================================================

------------------------- MODULE edac_vars ----------------------------------
EXTENDS edac_typedefs

VARIABLES
    \* @type: Int -> $procstate;
    state,
    \* @type: Int -> (Int -> $msg);
    msgs,
    \* @type: Int -> Set(Int);
    previous,
    \* @type: Int;
    round,
    \* @type: Str;
    phase,
    \* @type: Set(Int);
    crash,
    \* @type: Set(Int);
    failed,
    \* @type: Int -> Set(Int);
    receivers

=============================================================================

-------------------------------- MODULE edac --------------------------------

EXTENDS Integers, FiniteSets, TLC, edac_typedefs, Variants

CONSTANTS
    \* @type: Set(Int);
    Values,
    \* @type: Int;
    N,
    \* @type: Int;
    T,
    \* @type: Int;
    F

VARIABLES
    \* @type: Int -> $procstate;
    state,
    \* @type: Int -> (Int -> $msg);
    msgs,
    \* @type: Int -> Set(Int);
    previous,
    \* @type: Int;
    round,
    \* @type: Str;
    phase,
    \* @type: Set(Int);
    crash,
    \* @type: Set(Int);
    failed,
    \* @type: Int -> Set(Int);
    receivers
      
vars == <<state, previous, msgs, round, phase, crash, failed, receivers>>

P == 1 .. N \* set of processes
Nil == -1
V == {0, 1}
M == {"W", "D"} \* message type

Messages ==
    { W(S): S \in SUBSET(V) }
        \union
    { D(v): v \in V }
        \union
    { NilMsg }

C == [ W : {{0}, {1}, {0, 1}},  halt : {FALSE}, decision : {0, 1, Nil}]
InitC == [ W : {{0}, {1}},  halt : {FALSE}, decision : {Nil}]

InitEnvironment ==
    /\ phase = "msgs"
    /\ round = 0
    /\ crash \in SUBSET(P)  
    /\ failed = {}
    /\ Cardinality(failed \cup crash) <= F
    /\ receivers \in [crash -> SUBSET(P)]
    
InitAlgorithm ==
    /\ state \in [P -> InitC]
    /\ msgs = [p \in P |-> [q \in P |-> NilMsg]] \* two-dimensional messages array
    /\ previous = [p \in P |-> P]
    
NRcv(p) == {q \in P : msgs[q][p] = NilMsg}

Msgs(p) == IF p \in failed
        THEN {}
        ELSE UNION {U \in SUBSET(V): \E q \in P : msgs[q][p] = W(U) }
    
SendMessage(p, q) ==  
    IF state[p].decision # Nil
    THEN D(state[p].decision)
    ELSE W(state[p].W)

EnvSemMsg(m, p, q) ==
    IF \/ p \in failed
       \/ state[p].halt
       \/ (p \in crash /\ q \notin receivers[p])
    THEN NilMsg
    ELSE m
         
\* @type: (Int, $procstate, $procstate) => $procstate;
EnvSemState(p, s1, s2) == 
    IF p \in failed \/ p \in crash \/ s2.halt
    THEN s2 
    ELSE s1             

Update(p, X) == 
    LET arrived == { x \in V : \E q \in P: msgs[q][p] = D(x) } IN
    LET w == state[p].W \cup Msgs(p) IN
    LET dec == IF arrived = {0}
               THEN 0
               ELSE IF arrived = {1}
                    THEN 1
                    ELSE IF previous[p] = NRcv(p)
                         THEN IF 0 \in w
                              THEN 0
                              ELSE 1
                         ELSE state[p].decision IN
    LET h == state[p].decision # Nil IN
    [W |-> w, halt |-> h, decision |-> dec]

MsgsStep ==
    IF \A p \in P \ failed : state[p].halt
    THEN UNCHANGED vars
    ELSE
        \* the step by the environment
        /\ phase' = "trans"
        /\ round' = round+1
        /\ UNCHANGED <<crash, failed, receivers>>
        \* the step by the algorithm
        /\ msgs' = [p \in P |-> [q \in P |-> EnvSemMsg(SendMessage(p, q), p, q)]]
        /\ UNCHANGED <<state, previous>>

TransStep ==
    \* the step by the environment
    /\ phase' = "msgs"
    /\ failed' = failed \cup crash
    /\ crash' \in SUBSET(P \ failed')
    /\ Cardinality(failed' \cup crash') <= F
    /\ receivers' \in [crash' -> SUBSET(P)]
    /\ UNCHANGED round
    \* the step by the algorithm
    /\ state' = [p \in P |-> EnvSemState(p, Update(p, Msgs(p)), state[p])]
    /\ previous' = [p \in P |-> IF ~state[p].halt THEN NRcv(p) ELSE previous[p]]
    /\ msgs' = [p \in P |-> [q \in P |-> NilMsg]]

\* next state action predicates
 
Init ==
    InitAlgorithm /\ InitEnvironment

Next ==
    \/ phase = "msgs" /\ MsgsStep
    \/ phase = "trans" /\ TransStep

\* fairness constraint
Fairness == WF_vars(Next)

\* specification
Spec == Init /\ [][Next]_vars /\ Fairness
                 
\* safety properties 
Validity ==
  \A v \in V:
    (\A p \in P : state[p].W = {v})
      => [](\A q \in P:
              (q \notin failed /\ state[q].decision # Nil)
                => state[q].decision = v)

Agreement ==
  [](\A p \in P:
       \A q \in P:
         ((/\ p \notin failed /\ state[p].decision # Nil
           /\ q \notin failed /\ state[q].decision # Nil)
             => state[p].decision = state[q].decision))

\* safety as invariants
AgreementInv ==
  \A p \in P:
    \A q \in P:
      ((/\ p \notin failed /\ state[p].decision # Nil
        /\ q \notin failed /\ state[q].decision # Nil)
           => state[p].decision = state[q].decision)


\* liveness property
Termination == <>(\A p \in P : p \in failed \/ state[p].decision # Nil) 


=============================================================================
\* Modification History
\* Last modified Thu Sep 28 18:50:35 CEST 2017 by stoilkov
\* Created Thu Sep 28 18:35:23 CEST 2017 by stoilkov

````

## The command line parameters used to run the tool

```
--temporal=Validity0
```

## Log files

<details>
```
2022-08-26T10:52:10,063 [main] INFO  a.f.a.t.Tool\$ - # APALACHE version: v0.28.0-47-ge40e227fd | build: v0.28.0-47-ge40e227fd
2022-08-26T10:52:10,066 [main] INFO  a.f.a.t.t.o.CheckCmd - Tuning: search.outputTraces=false
2022-08-26T10:52:10,067 [main] INFO  a.f.a.t.t.o.CheckCmd - Checker options: check --temporal=Validity0 MC_4_1_1_edac.tla
2022-08-26T10:52:10,070 [main] INFO  a.f.a.i.p.PassChainExecutor - PASS #0: SanyParser
2022-08-26T10:52:10,692 [main] DEBUG a.f.a.i.p.PassChainExecutor - PASS #0: SanyParser [OK]
2022-08-26T10:52:10,692 [main] INFO  a.f.a.i.p.PassChainExecutor - PASS #1: TypeCheckerSnowcat
2022-08-26T10:52:10,692 [main] INFO  a.f.a.t.t.p.EtcTypeCheckerPassImpl -  > Running Snowcat .::.
2022-08-26T10:52:11,413 [main] INFO  a.f.a.t.t.p.EtcTypeCheckerPassImpl -  > Your types are purrfect!
2022-08-26T10:52:11,414 [main] INFO  a.f.a.t.t.p.EtcTypeCheckerPassImpl -  > All expressions are typed
2022-08-26T10:52:11,474 [main] DEBUG a.f.a.i.p.PassChainExecutor - PASS #1: TypeCheckerSnowcat [OK]
2022-08-26T10:52:11,474 [main] INFO  a.f.a.i.p.PassChainExecutor - PASS #2: ConfigurationPass
2022-08-26T10:52:11,479 [main] INFO  a.f.a.t.p.p.ConfigurationPassImpl -   > Command line option --init is not set. Using Init
2022-08-26T10:52:11,479 [main] INFO  a.f.a.t.p.p.ConfigurationPassImpl -   > Command line option --next is not set. Using Next
2022-08-26T10:52:11,479 [main] INFO  a.f.a.t.p.p.ConfigurationPassImpl -   > Set the initialization predicate to Init
2022-08-26T10:52:11,480 [main] INFO  a.f.a.t.p.p.ConfigurationPassImpl -   > Set the transition predicate to Next
2022-08-26T10:52:11,480 [main] INFO  a.f.a.t.p.p.ConfigurationPassImpl -   > Set a temporal property to Validity0
2022-08-26T10:52:11,534 [main] DEBUG a.f.a.i.p.PassChainExecutor - PASS #2: ConfigurationPass [OK]
2022-08-26T10:52:11,535 [main] INFO  a.f.a.i.p.PassChainExecutor - PASS #3: DesugarerPass
2022-08-26T10:52:11,535 [main] INFO  a.f.a.t.p.p.DesugarerPassImpl -   > Desugaring...
2022-08-26T10:52:11,766 [main] DEBUG a.f.a.i.p.PassChainExecutor - PASS #3: DesugarerPass [OK]
2022-08-26T10:52:11,766 [main] INFO  a.f.a.i.p.PassChainExecutor - PASS #4: InlinePass
2022-08-26T10:52:11,767 [main] INFO  a.f.a.t.p.p.InlinePassImpl - Leaving only relevant operators: CInitPrimed, Init, InitPrimed, Next, Validity0
2022-08-26T10:52:11,847 [main] DEBUG a.f.a.i.p.PassChainExecutor - PASS #4: InlinePass [OK]
2022-08-26T10:52:11,847 [main] INFO  a.f.a.i.p.PassChainExecutor - PASS #5: TemporalPass
2022-08-26T10:52:11,847 [main] INFO  a.f.a.t.p.p.TemporalPassImpl -   > Rewriting temporal operators...
2022-08-26T10:52:11,851 [main] INFO  a.f.a.t.p.p.TemporalPassImpl -   > Found 1 temporal properties
2022-08-26T10:52:11,852 [main] INFO  a.f.a.t.p.p.TemporalPassImpl -   > Adding logic for loop finding
2022-08-26T10:52:11,924 [main] DEBUG a.f.a.i.p.PassChainExecutor - PASS #5: TemporalPass [OK]
2022-08-26T10:52:11,924 [main] INFO  a.f.a.i.p.PassChainExecutor - PASS #6: InlinePass
2022-08-26T10:52:11,924 [main] INFO  a.f.a.t.p.p.InlinePassImpl - Leaving only relevant operators: CInitPrimed, Init, InitPrimed, Next, Validity0
2022-08-26T10:52:11,968 [main] DEBUG a.f.a.i.p.PassChainExecutor - PASS #6: InlinePass [OK]
2022-08-26T10:52:11,968 [main] INFO  a.f.a.i.p.PassChainExecutor - PASS #7: PrimingPass
2022-08-26T10:52:11,970 [main] INFO  a.f.a.t.a.p.PrimingPassImpl -   > Introducing InitPrimed for Init'
2022-08-26T10:52:12,008 [main] DEBUG a.f.a.i.p.PassChainExecutor - PASS #7: PrimingPass [OK]
2022-08-26T10:52:12,008 [main] INFO  a.f.a.i.p.PassChainExecutor - PASS #8: VCGen
2022-08-26T10:52:12,009 [main] INFO  a.f.a.t.b.p.VCGenPassImpl -   > Producing verification conditions from the invariant Validity0
2022-08-26T10:52:12,010 [main] INFO  a.f.a.t.b.VCGenerator -   > VCGen produced 1 verification condition(s)
2022-08-26T10:52:12,050 [main] DEBUG a.f.a.i.p.PassChainExecutor - PASS #8: VCGen [OK]
2022-08-26T10:52:12,050 [main] INFO  a.f.a.i.p.PassChainExecutor - PASS #9: PreprocessingPass
2022-08-26T10:52:12,050 [main] INFO  a.f.a.t.p.p.PreproPassImpl -   > Before preprocessing: unique renaming
2022-08-26T10:52:12,056 [main] INFO  a.f.a.t.p.p.PreproPassImpl -  > Applying standard transformations:
2022-08-26T10:52:12,056 [main] INFO  a.f.a.t.p.p.PreproPassImpl -   > PrimePropagation
2022-08-26T10:52:12,096 [main] INFO  a.f.a.t.p.p.PreproPassImpl -   > Desugarer
2022-08-26T10:52:12,127 [main] INFO  a.f.a.t.p.p.PreproPassImpl -   > UniqueRenamer
2022-08-26T10:52:12,159 [main] INFO  a.f.a.t.p.p.PreproPassImpl -   > Normalizer
2022-08-26T10:52:12,190 [main] INFO  a.f.a.t.p.p.PreproPassImpl -   > Keramelizer
2022-08-26T10:52:12,228 [main] INFO  a.f.a.t.p.p.PreproPassImpl -   > After preprocessing: UniqueRenamer
2022-08-26T10:52:12,261 [main] DEBUG a.f.a.i.p.PassChainExecutor - PASS #9: PreprocessingPass [OK]
2022-08-26T10:52:12,261 [main] INFO  a.f.a.i.p.PassChainExecutor - PASS #10: TransitionFinderPass
2022-08-26T10:52:12,275 [main] INFO  a.f.a.t.a.p.TransitionPassImpl -   > Found 1 initializing transitions
2022-08-26T10:52:12,291 [main] INFO  a.f.a.t.a.p.TransitionPassImpl -   > Found 6 transitions
2022-08-26T10:52:12,292 [main] INFO  a.f.a.t.a.p.TransitionPassImpl -   > No constant initializer
2022-08-26T10:52:12,293 [main] INFO  a.f.a.t.a.p.TransitionPassImpl -   > Applying unique renaming
2022-08-26T10:52:12,353 [main] DEBUG a.f.a.i.p.PassChainExecutor - PASS #10: TransitionFinderPass [OK]
2022-08-26T10:52:12,353 [main] INFO  a.f.a.i.p.PassChainExecutor - PASS #11: OptimizationPass
2022-08-26T10:52:12,358 [main] INFO  a.f.a.t.p.p.OptPassImpl -  > Applying optimizations:
2022-08-26T10:52:12,359 [main] INFO  a.f.a.t.p.p.OptPassImpl -   > ConstSimplifier
2022-08-26T10:52:12,374 [main] INFO  a.f.a.t.p.p.OptPassImpl -   > ExprOptimizer
2022-08-26T10:52:12,381 [main] INFO  a.f.a.t.p.p.OptPassImpl -   > SetMembershipSimplifier
2022-08-26T10:52:12,385 [main] INFO  a.f.a.t.p.p.OptPassImpl -   > ConstSimplifier
2022-08-26T10:52:12,448 [main] DEBUG a.f.a.i.p.PassChainExecutor - PASS #11: OptimizationPass [OK]
2022-08-26T10:52:12,449 [main] INFO  a.f.a.i.p.PassChainExecutor - PASS #12: AnalysisPass
2022-08-26T10:52:12,451 [main] INFO  a.f.a.t.b.p.AnalysisPassImpl -  > Marking skolemizable existentials and sets to be expanded...
2022-08-26T10:52:12,451 [main] INFO  a.f.a.t.b.p.AnalysisPassImpl -   > Skolemization
2022-08-26T10:52:12,453 [main] INFO  a.f.a.t.b.p.AnalysisPassImpl -   > Expansion
2022-08-26T10:52:12,459 [main] INFO  a.f.a.t.b.p.AnalysisPassImpl -   > Remove unused let-in defs
2022-08-26T10:52:12,467 [main] INFO  a.f.a.t.b.p.AnalysisPassImpl -  > Running analyzers...
2022-08-26T10:52:12,522 [main] INFO  a.f.a.t.b.p.AnalysisPassImpl -   > Introduced expression grades
2022-08-26T10:52:12,522 [main] DEBUG a.f.a.i.p.PassChainExecutor - PASS #12: AnalysisPass [OK]
2022-08-26T10:52:12,523 [main] INFO  a.f.a.i.p.PassChainExecutor - PASS #13: BoundedChecker
2022-08-26T10:52:13,047 [main] DEBUG a.f.a.t.b.t.TransitionExecutorImpl - Step #0, transition #0
2022-08-26T10:52:13,048 [main] DEBUG a.f.a.t.b.t.TransitionExecutorImpl - Translating to SMT...
2022-08-26T10:52:13,189 [main] DEBUG a.f.a.t.b.SeqModelChecker - Step 0: Transition #0. Is it enabled?
2022-08-26T10:52:13,191 [main] DEBUG a.f.a.t.b.SeqModelChecker - Step 0: Transition #0 is enabled
2022-08-26T10:52:13,191 [main] INFO  a.f.a.t.b.SeqModelChecker - State 0: Checking 1 state invariants
2022-08-26T10:52:13,192 [main] DEBUG a.f.a.t.b.SeqModelChecker - State 0: Checking state invariant 0
2022-08-26T10:52:13,199 [main] INFO  a.f.a.t.b.t.TransitionExecutorImpl - Step 0: picking a transition out of 1 transition(s)
2022-08-26T10:52:13,200 [main] DEBUG a.f.a.t.b.t.TransitionExecutorImpl - Step #1, transition #0
2022-08-26T10:52:13,200 [main] DEBUG a.f.a.t.b.t.TransitionExecutorImpl - Translating to SMT...
2022-08-26T10:52:13,234 [main] DEBUG a.f.a.t.b.SeqModelChecker - Step 1: Transition #0. Is it enabled?
2022-08-26T10:52:13,234 [main] INFO  a.f.a.t.b.SeqModelChecker - Step 1: Transition #0 is disabled
2022-08-26T10:52:13,235 [main] DEBUG a.f.a.t.b.t.TransitionExecutorImpl - Step #1, transition #1
2022-08-26T10:52:13,235 [main] DEBUG a.f.a.t.b.t.TransitionExecutorImpl - Translating to SMT...
2022-08-26T10:52:13,337 [main] DEBUG a.f.a.t.b.SeqModelChecker - Step 1: Transition #1. Is it enabled?
2022-08-26T10:52:13,338 [main] DEBUG a.f.a.t.b.SeqModelChecker - Step 1: Transition #1 is enabled
2022-08-26T10:52:13,339 [main] INFO  a.f.a.t.b.SeqModelChecker - State 1: Checking 1 state invariants
2022-08-26T10:52:13,339 [main] DEBUG a.f.a.t.b.SeqModelChecker - State 1: Checking state invariant 0
2022-08-26T10:52:13,531 [main] DEBUG a.f.a.t.b.t.TransitionExecutorImpl - Step #1, transition #2
2022-08-26T10:52:13,532 [main] DEBUG a.f.a.t.b.t.TransitionExecutorImpl - Translating to SMT...
2022-08-26T10:52:13,540 [main] ERROR a.f.a.t.Tool\$ - Unhandled exception
java.lang.ClassCastException: class at.forsyte.apalache.tla.lir.BoolT1\$ cannot be cast to class at.forsyte.apalache.tla.lir.FunT1 (at.forsyte.apalache.tla.lir.BoolT1\$ and at.forsyte.apalache.tla.lir.FunT1 are in unnamed module of loader 'app')
	at at.forsyte.apalache.tla.bmcmt.rules.FunCtorRule.apply(FunCtorRule.scala:30)
	at at.forsyte.apalache.tla.bmcmt.SymbStateRewriterImpl.rewriteOnce(SymbStateRewriterImpl.scala:355)
	at at.forsyte.apalache.tla.bmcmt.SymbStateRewriterImpl.doRecursive\$1(SymbStateRewriterImpl.scala:388)
	at at.forsyte.apalache.tla.bmcmt.SymbStateRewriterImpl.rewriteUntilDone(SymbStateRewriterImpl.scala:422)
	at at.forsyte.apalache.tla.bmcmt.rules.AssignmentRule.apply(AssignmentRule.scala:37)
	at at.forsyte.apalache.tla.bmcmt.SymbStateRewriterImpl.rewriteOnce(SymbStateRewriterImpl.scala:355)
	at at.forsyte.apalache.tla.bmcmt.SymbStateRewriterImpl.doRecursive\$1(SymbStateRewriterImpl.scala:388)
	at at.forsyte.apalache.tla.bmcmt.SymbStateRewriterImpl.rewriteUntilDone(SymbStateRewriterImpl.scala:422)
	at at.forsyte.apalache.tla.bmcmt.rules.AndRule.mapArg\$1(AndRule.scala:62)
	at at.forsyte.apalache.tla.bmcmt.rules.AndRule.\$anonfun\$apply\$2(AndRule.scala:66)
	at scala.collection.immutable.List.map(List.scala:250)
	at scala.collection.immutable.List.map(List.scala:79)
	at at.forsyte.apalache.tla.bmcmt.rules.AndRule.apply(AndRule.scala:66)
	at at.forsyte.apalache.tla.bmcmt.SymbStateRewriterImpl.rewriteOnce(SymbStateRewriterImpl.scala:355)
	at at.forsyte.apalache.tla.bmcmt.SymbStateRewriterImpl.doRecursive\$1(SymbStateRewriterImpl.scala:388)
	at at.forsyte.apalache.tla.bmcmt.SymbStateRewriterImpl.rewriteUntilDone(SymbStateRewriterImpl.scala:422)
	at at.forsyte.apalache.tla.bmcmt.rules.AndRule.mapArg\$1(AndRule.scala:62)
	at at.forsyte.apalache.tla.bmcmt.rules.AndRule.\$anonfun\$apply\$2(AndRule.scala:66)
	at scala.collection.immutable.List.map(List.scala:246)
	at scala.collection.immutable.List.map(List.scala:79)
	at at.forsyte.apalache.tla.bmcmt.rules.AndRule.apply(AndRule.scala:66)
	at at.forsyte.apalache.tla.bmcmt.SymbStateRewriterImpl.rewriteOnce(SymbStateRewriterImpl.scala:355)
	at at.forsyte.apalache.tla.bmcmt.SymbStateRewriterImpl.doRecursive\$1(SymbStateRewriterImpl.scala:388)
	at at.forsyte.apalache.tla.bmcmt.SymbStateRewriterImpl.rewriteUntilDone(SymbStateRewriterImpl.scala:422)
	at at.forsyte.apalache.tla.bmcmt.trex.TransitionExecutorImpl.prepareTransition(TransitionExecutorImpl.scala:106)
	at at.forsyte.apalache.tla.bmcmt.trex.FilteredTransitionExecutor.prepareTransition(FilteredTransitionExecutor.scala:48)
	at at.forsyte.apalache.tla.bmcmt.trex.ConstrainedTransitionExecutor.prepareTransition(ConstrainedTransitionExecutor.scala:98)
	at at.forsyte.apalache.tla.bmcmt.SeqModelChecker.\$anonfun\$prepareTransitionsAndCheckInvariants\$5(SeqModelChecker.scala:221)
	at scala.runtime.java8.JFunction1\$mcVI\$sp.apply(JFunction1\$mcVI\$sp.scala:18)
	at scala.collection.immutable.Range.foreach(Range.scala:190)
	at at.forsyte.apalache.tla.bmcmt.SeqModelChecker.prepareTransitionsAndCheckInvariants(SeqModelChecker.scala:215)
	at at.forsyte.apalache.tla.bmcmt.SeqModelChecker.makeStep(SeqModelChecker.scala:133)
	at at.forsyte.apalache.tla.bmcmt.SeqModelChecker.run(SeqModelChecker.scala:67)
	at at.forsyte.apalache.tla.bmcmt.passes.BoundedCheckerPassImpl.runIncrementalChecker(BoundedCheckerPassImpl.scala:132)
	at at.forsyte.apalache.tla.bmcmt.passes.BoundedCheckerPassImpl.execute(BoundedCheckerPassImpl.scala:88)
	at at.forsyte.apalache.infra.passes.PassChainExecutor.exec\$1(PassChainExecutor.scala:23)
	at at.forsyte.apalache.infra.passes.PassChainExecutor.\$anonfun\$run\$5(PassChainExecutor.scala:47)
	at scala.util.Either.flatMap(Either.scala:352)
	at at.forsyte.apalache.infra.passes.PassChainExecutor.\$anonfun\$run\$3(PassChainExecutor.scala:46)
	at scala.collection.LinearSeqOps.foldLeft(LinearSeq.scala:169)
	at scala.collection.LinearSeqOps.foldLeft\$(LinearSeq.scala:165)
	at scala.collection.immutable.List.foldLeft(List.scala:79)
	at at.forsyte.apalache.infra.passes.PassChainExecutor.run(PassChainExecutor.scala:41)
	at at.forsyte.apalache.infra.Executor.run(Executor.scala:35)
	at at.forsyte.apalache.tla.tooling.opt.CheckCmd.run(CheckCmd.scala:109)
	at at.forsyte.apalache.tla.Tool\$.runCommand(Tool.scala:139)
	at at.forsyte.apalache.tla.Tool\$.run(Tool.scala:119)
	at at.forsyte.apalache.tla.Tool\$.main(Tool.scala:36)
	at at.forsyte.apalache.tla.Tool.main(Tool.scala)
```
</details>

## System information

- Apalache version: `v0.28.0-47-ge40e227fd build v0.28.0-47-ge40e227fd`
- OS: `Mac OS X`
- JDK version: `18.0.2`

## Triage checklist (for maintainers)

- [ ] Reproduce the bug on the main development branch.
- [ ] Add the issue to the apalache GitHub project.
- [ ] If the bug is high impact, ensure someone available is assigned to fix it.

**Comment by rodrigo7491** [comment]
@konnov it seems I run into the exact same error you got when working on a spec on my side (together with @daviderovell0). We cannot release the spec at the moment, but I was able to produce a minimal(?) example, shown below. 

```
------------------------------- MODULE test -------------------------------

VARIABLES
    \* @type: Int -> Bool;
    flag

Init == flag = [p \in {1} |-> FALSE]

Next == flag' = [p \in {1} |-> IF TRUE /\ TRUE /\ TRUE THEN FALSE ELSE FALSE]

P1 == <>(TRUE)
P2 == [](TRUE)
P3 == TRUE

=============================================================================
```

With Apalache v0.47.2 (on a Linux machine) both `--temporal=P1` and `--temporal=P2` trigger the exception. The curious thing is that the exception only happens with three terms in the IF condition. If I change `TRUE /\ TRUE /\ TRUE` to `TRUE /\ TRUE` it goes through.

**Comment by konnov** [comment]
That is indeed quite strange!

**Comment by lemmy** [comment]
Fix in https://github.com/apalache-mc/apalache/pull/3354 is quite simple. :-)
