### ISSUE TITLE
Unable to unify generic signature (() => Set(Int)) with Set(a4621)

### ISSUE THREAD

**Issue by michwqy** [informalsystems/apalache#2452]
## Description

I found a error when checking TLA+ specification of the IBC Core protocols with Apalache. I noticed that a potentially similar bug was fixed in version 0.25.8, but I tried four versions and they all had the same problem. I don't know whether this is due to the problem of TLA + specification or Apalache, or simply my wrong.

## Impact

I can't check the TLA+ specification.

## Input specification

[The TLA+ specification in hermes master branch](https://github.com/informalsystems/hermes/tree/master/docs/spec/tla/ibc-core)

I didn't change anything.

## The command line parameters used to run the tool

java.exe -jar ./lib/apalache.jar --features=no-rows check PATH/IBCCore.tla

## Log files
```
2023-03-03T15:59:09,084 [main] INFO  a.f.a.t.Tool\$ - # APALACHE version: 0.30.2 | build: 333cdce
2023-03-03T15:59:09,104 [main] INFO  a.f.a.t.t.o.CheckCmd - Tuning: search.outputTraces=false
2023-03-03T15:59:09,262 [main] INFO  a.f.a.i.p.PassChainExecutor\$ - PASS #0: SanyParser
2023-03-03T15:59:10,209 [main] DEBUG a.f.a.i.p.PassChainExecutor\$ - PASS #0: SanyParser [OK]
2023-03-03T15:59:10,210 [main] INFO  a.f.a.i.p.PassChainExecutor\$ - PASS #1: TypeCheckerSnowcat
2023-03-03T15:59:10,211 [main] INFO  a.f.a.t.p.t.EtcTypeCheckerPassImpl -  > Running Snowcat .::.
2023-03-03T15:59:10,371 [main] WARN  a.f.a.t.t.TypeCheckerTool - Operator ChainIDs: Deprecated syntax in type alias CHAN. Use camelCase of Type System 1.2.
2023-03-03T15:59:10,394 [main] WARN  a.f.a.t.t.TypeCheckerTool - Operator ChainIDs: Deprecated syntax in type alias CONN. Use camelCase of Type System 1.2.
2023-03-03T15:59:10,397 [main] WARN  a.f.a.t.t.TypeCheckerTool - Operator ChainIDs: Deprecated syntax in type alias PACKET. Use camelCase of Type System 1.2.
2023-03-03T15:59:10,398 [main] WARN  a.f.a.t.t.TypeCheckerTool - Operator ChainIDs: Deprecated syntax in type alias PACKETCOMM. Use camelCase of Type System 1.2.
2023-03-03T15:59:10,400 [main] WARN  a.f.a.t.t.TypeCheckerTool - Operator ChainIDs: Deprecated syntax in type alias PACKETREC. Use camelCase of Type System 1.2.
2023-03-03T15:59:10,403 [main] WARN  a.f.a.t.t.TypeCheckerTool - Operator ChainIDs: Deprecated syntax in type alias PACKETACK. Use camelCase of Type System 1.2.
2023-03-03T15:59:10,425 [main] WARN  a.f.a.t.t.TypeCheckerTool - Operator ChainIDs: Deprecated syntax in type alias CHAINSTORE. Use camelCase of Type System 1.2.
2023-03-03T15:59:10,431 [main] WARN  a.f.a.t.t.TypeCheckerTool - Operator ChainIDs: Deprecated syntax in type alias DATAGRAM. Use camelCase of Type System 1.2.
2023-03-03T15:59:10,434 [main] WARN  a.f.a.t.t.TypeCheckerTool - Operator ChainIDs: Deprecated syntax in type alias LOGENTRY. Use camelCase of Type System 1.2.
2023-03-03T15:59:10,436 [main] WARN  a.f.a.t.t.TypeCheckerTool - Operator ChainIDs: Deprecated syntax in type alias HISTORY. Use camelCase of Type System 1.2.
2023-03-03T15:59:10,439 [main] WARN  a.f.a.t.t.TypeCheckerTool - Operator Relayer1!ChainIDs: Deprecated syntax in type alias CHAN. Use camelCase of Type System 1.2.
2023-03-03T15:59:10,444 [main] WARN  a.f.a.t.t.TypeCheckerTool - Operator Relayer1!ChainIDs: Deprecated syntax in type alias CONN. Use camelCase of Type System 1.2.
2023-03-03T15:59:10,447 [main] WARN  a.f.a.t.t.TypeCheckerTool - Operator Relayer1!ChainIDs: Deprecated syntax in type alias PACKET. Use camelCase of Type System 1.2.
2023-03-03T15:59:10,448 [main] WARN  a.f.a.t.t.TypeCheckerTool - Operator Relayer1!ChainIDs: Deprecated syntax in type alias PACKETCOMM. Use camelCase of Type System 1.2.
2023-03-03T15:59:10,449 [main] WARN  a.f.a.t.t.TypeCheckerTool - Operator Relayer1!ChainIDs: Deprecated syntax in type alias PACKETREC. Use camelCase of Type System 1.2.
2023-03-03T15:59:10,450 [main] WARN  a.f.a.t.t.TypeCheckerTool - Operator Relayer1!ChainIDs: Deprecated syntax in type alias PACKETACK. Use camelCase of Type System 1.2.
2023-03-03T15:59:10,468 [main] WARN  a.f.a.t.t.TypeCheckerTool - Operator Relayer1!ChainIDs: Deprecated syntax in type alias CHAINSTORE. Use camelCase of Type System 1.2.
2023-03-03T15:59:10,473 [main] WARN  a.f.a.t.t.TypeCheckerTool - Operator Relayer1!ChainIDs: Deprecated syntax in type alias DATAGRAM. Use camelCase of Type System 1.2.
2023-03-03T15:59:10,475 [main] WARN  a.f.a.t.t.TypeCheckerTool - Operator Relayer1!ChainIDs: Deprecated syntax in type alias LOGENTRY. Use camelCase of Type System 1.2.
2023-03-03T15:59:10,476 [main] WARN  a.f.a.t.t.TypeCheckerTool - Operator Relayer1!ChainIDs: Deprecated syntax in type alias HISTORY. Use camelCase of Type System 1.2.
2023-03-03T15:59:10,477 [main] WARN  a.f.a.t.t.TypeCheckerTool - Operator Relayer2!ChainIDs: Deprecated syntax in type alias CHAN. Use camelCase of Type System 1.2.
2023-03-03T15:59:10,482 [main] WARN  a.f.a.t.t.TypeCheckerTool - Operator Relayer2!ChainIDs: Deprecated syntax in type alias CONN. Use camelCase of Type System 1.2.
2023-03-03T15:59:10,483 [main] WARN  a.f.a.t.t.TypeCheckerTool - Operator Relayer2!ChainIDs: Deprecated syntax in type alias PACKET. Use camelCase of Type System 1.2.
2023-03-03T15:59:10,484 [main] WARN  a.f.a.t.t.TypeCheckerTool - Operator Relayer2!ChainIDs: Deprecated syntax in type alias PACKETCOMM. Use camelCase of Type System 1.2.
2023-03-03T15:59:10,485 [main] WARN  a.f.a.t.t.TypeCheckerTool - Operator Relayer2!ChainIDs: Deprecated syntax in type alias PACKETREC. Use camelCase of Type System 1.2.
2023-03-03T15:59:10,486 [main] WARN  a.f.a.t.t.TypeCheckerTool - Operator Relayer2!ChainIDs: Deprecated syntax in type alias PACKETACK. Use camelCase of Type System 1.2.
2023-03-03T15:59:10,503 [main] WARN  a.f.a.t.t.TypeCheckerTool - Operator Relayer2!ChainIDs: Deprecated syntax in type alias CHAINSTORE. Use camelCase of Type System 1.2.
2023-03-03T15:59:10,509 [main] WARN  a.f.a.t.t.TypeCheckerTool - Operator Relayer2!ChainIDs: Deprecated syntax in type alias DATAGRAM. Use camelCase of Type System 1.2.
2023-03-03T15:59:10,510 [main] WARN  a.f.a.t.t.TypeCheckerTool - Operator Relayer2!ChainIDs: Deprecated syntax in type alias LOGENTRY. Use camelCase of Type System 1.2.
2023-03-03T15:59:10,512 [main] WARN  a.f.a.t.t.TypeCheckerTool - Operator Relayer2!ChainIDs: Deprecated syntax in type alias HISTORY. Use camelCase of Type System 1.2.
2023-03-03T15:59:10,514 [main] WARN  a.f.a.t.t.TypeCheckerTool - Operator ChainA!ChainIDs: Deprecated syntax in type alias CHAN. Use camelCase of Type System 1.2.
2023-03-03T15:59:10,516 [main] WARN  a.f.a.t.t.TypeCheckerTool - Operator ChainA!ChainIDs: Deprecated syntax in type alias CONN. Use camelCase of Type System 1.2.
2023-03-03T15:59:10,518 [main] WARN  a.f.a.t.t.TypeCheckerTool - Operator ChainA!ChainIDs: Deprecated syntax in type alias PACKET. Use camelCase of Type System 1.2.
2023-03-03T15:59:10,519 [main] WARN  a.f.a.t.t.TypeCheckerTool - Operator ChainA!ChainIDs: Deprecated syntax in type alias PACKETCOMM. Use camelCase of Type System 1.2.
2023-03-03T15:59:10,520 [main] WARN  a.f.a.t.t.TypeCheckerTool - Operator ChainA!ChainIDs: Deprecated syntax in type alias PACKETREC. Use camelCase of Type System 1.2.
2023-03-03T15:59:10,521 [main] WARN  a.f.a.t.t.TypeCheckerTool - Operator ChainA!ChainIDs: Deprecated syntax in type alias PACKETACK. Use camelCase of Type System 1.2.
2023-03-03T15:59:10,547 [main] WARN  a.f.a.t.t.TypeCheckerTool - Operator ChainA!ChainIDs: Deprecated syntax in type alias CHAINSTORE. Use camelCase of Type System 1.2.
2023-03-03T15:59:10,553 [main] WARN  a.f.a.t.t.TypeCheckerTool - Operator ChainA!ChainIDs: Deprecated syntax in type alias DATAGRAM. Use camelCase of Type System 1.2.
2023-03-03T15:59:10,555 [main] WARN  a.f.a.t.t.TypeCheckerTool - Operator ChainA!ChainIDs: Deprecated syntax in type alias LOGENTRY. Use camelCase of Type System 1.2.
2023-03-03T15:59:10,556 [main] WARN  a.f.a.t.t.TypeCheckerTool - Operator ChainA!ChainIDs: Deprecated syntax in type alias HISTORY. Use camelCase of Type System 1.2.
2023-03-03T15:59:10,559 [main] WARN  a.f.a.t.t.TypeCheckerTool - Operator ChainB!ChainIDs: Deprecated syntax in type alias CHAN. Use camelCase of Type System 1.2.
2023-03-03T15:59:10,564 [main] WARN  a.f.a.t.t.TypeCheckerTool - Operator ChainB!ChainIDs: Deprecated syntax in type alias CONN. Use camelCase of Type System 1.2.
2023-03-03T15:59:10,565 [main] WARN  a.f.a.t.t.TypeCheckerTool - Operator ChainB!ChainIDs: Deprecated syntax in type alias PACKET. Use camelCase of Type System 1.2.
2023-03-03T15:59:10,566 [main] WARN  a.f.a.t.t.TypeCheckerTool - Operator ChainB!ChainIDs: Deprecated syntax in type alias PACKETCOMM. Use camelCase of Type System 1.2.
2023-03-03T15:59:10,568 [main] WARN  a.f.a.t.t.TypeCheckerTool - Operator ChainB!ChainIDs: Deprecated syntax in type alias PACKETREC. Use camelCase of Type System 1.2.
2023-03-03T15:59:10,569 [main] WARN  a.f.a.t.t.TypeCheckerTool - Operator ChainB!ChainIDs: Deprecated syntax in type alias PACKETACK. Use camelCase of Type System 1.2.
2023-03-03T15:59:10,584 [main] WARN  a.f.a.t.t.TypeCheckerTool - Operator ChainB!ChainIDs: Deprecated syntax in type alias CHAINSTORE. Use camelCase of Type System 1.2.
2023-03-03T15:59:10,588 [main] WARN  a.f.a.t.t.TypeCheckerTool - Operator ChainB!ChainIDs: Deprecated syntax in type alias DATAGRAM. Use camelCase of Type System 1.2.
2023-03-03T15:59:10,590 [main] WARN  a.f.a.t.t.TypeCheckerTool - Operator ChainB!ChainIDs: Deprecated syntax in type alias LOGENTRY. Use camelCase of Type System 1.2.
2023-03-03T15:59:10,590 [main] WARN  a.f.a.t.t.TypeCheckerTool - Operator ChainB!ChainIDs: Deprecated syntax in type alias HISTORY. Use camelCase of Type System 1.2.
2023-03-03T15:59:18,227 [main] INFO  a.f.a.t.p.t.EtcTypeCheckerPassImpl -  > Your types are purrfect!
2023-03-03T15:59:18,227 [main] INFO  a.f.a.t.p.t.EtcTypeCheckerPassImpl -  > All expressions are typed
2023-03-03T15:59:18,228 [main] DEBUG a.f.a.i.p.PassChainExecutor\$ - PASS #1: TypeCheckerSnowcat [OK]
2023-03-03T15:59:18,228 [main] INFO  a.f.a.i.p.PassChainExecutor\$ - PASS #2: ConfigurationPass
2023-03-03T15:59:18,237 [main] INFO  a.f.a.t.p.p.ConfigurationPassImpl -   > Set the initialization predicate to Init
2023-03-03T15:59:18,239 [main] INFO  a.f.a.t.p.p.ConfigurationPassImpl -   > Set the transition predicate to Next
2023-03-03T15:59:18,257 [main] DEBUG a.f.a.i.p.PassChainExecutor\$ - PASS #2: ConfigurationPass [OK]
2023-03-03T15:59:18,258 [main] INFO  a.f.a.i.p.PassChainExecutor\$ - PASS #3: DesugarerPass
2023-03-03T15:59:18,258 [main] INFO  a.f.a.t.p.p.DesugarerPassImpl -   > Desugaring...
2023-03-03T15:59:18,511 [main] DEBUG a.f.a.i.p.PassChainExecutor\$ - PASS #3: DesugarerPass [OK]
2023-03-03T15:59:18,511 [main] INFO  a.f.a.i.p.PassChainExecutor\$ - PASS #4: InlinePass
2023-03-03T15:59:18,512 [main] INFO  a.f.a.t.p.p.InlinePassImpl - Leaving only relevant operators: CInitPrimed, Init, InitPrimed, Next
2023-03-03T15:59:18,609 [main] DEBUG a.f.a.i.p.PassChainExecutor\$ - Adapted exception intercepted: 
at.forsyte.apalache.tla.lir.TypingException: Inliner: Unable to unify generic signature (() => Set(Int)) of Heights with the concrete type Set(a4621)
	at at.forsyte.apalache.tla.pp.Inliner.getSubstitution(Inliner.scala:106)
	at at.forsyte.apalache.tla.pp.Inliner.embedPassByName(Inliner.scala:162)
	at at.forsyte.apalache.tla.pp.Inliner.\$anonfun\$transform\$1(Inliner.scala:217)
	at at.forsyte.apalache.tla.lir.transformations.impl.TrackerWithListeners.\$anonfun\$trackEx\$1(TrackerWithListeners.scala:18)
	at scala.collection.immutable.List.map(List.scala:250)
	at scala.collection.immutable.List.map(List.scala:79)
	at at.forsyte.apalache.tla.pp.Inliner.\$anonfun\$transform\$1(Inliner.scala:221)
	at at.forsyte.apalache.tla.lir.transformations.impl.TrackerWithListeners.\$anonfun\$trackEx\$1(TrackerWithListeners.scala:18)
	at at.forsyte.apalache.tla.pp.Inliner.\$anonfun\$pushDeclsIntoScope\$1(Inliner.scala:66)
	at scala.collection.LinearSeqOps.foldLeft(LinearSeq.scala:183)
	at scala.collection.LinearSeqOps.foldLeft\$(LinearSeq.scala:179)
	at scala.collection.immutable.List.foldLeft(List.scala:79)
	at at.forsyte.apalache.tla.pp.Inliner.pushDeclsIntoScope(Inliner.scala:62)
	at at.forsyte.apalache.tla.pp.Inliner.transformModule(Inliner.scala:239)
	at at.forsyte.apalache.tla.passes.pp.InlinePassImpl.execute(InlinePassImpl.scala:55)
	at at.forsyte.apalache.infra.passes.PassChainExecutor\$.exec(PassChainExecutor.scala:64)
	at at.forsyte.apalache.infra.passes.PassChainExecutor\$.\$anonfun\$runPassOnModule\$3(PassChainExecutor.scala:53)
	at scala.util.Either.flatMap(Either.scala:352)
	at at.forsyte.apalache.infra.passes.PassChainExecutor\$.\$anonfun\$runPassOnModule\$1(PassChainExecutor.scala:51)
	at scala.collection.LinearSeqOps.foldLeft(LinearSeq.scala:183)
	at scala.collection.LinearSeqOps.foldLeft\$(LinearSeq.scala:179)
	at scala.collection.immutable.List.foldLeft(List.scala:79)
	at at.forsyte.apalache.infra.passes.PassChainExecutor\$.runOnPasses(PassChainExecutor.scala:44)
	at at.forsyte.apalache.infra.passes.PassChainExecutor\$.run(PassChainExecutor.scala:34)
	at at.forsyte.apalache.tla.tooling.opt.CheckCmd.run(CheckCmd.scala:132)
	at at.forsyte.apalache.tla.Tool\$.runCommand(Tool.scala:138)
	at at.forsyte.apalache.tla.Tool\$.run(Tool.scala:118)
	at at.forsyte.apalache.tla.Tool\$.main(Tool.scala:40)
	at at.forsyte.apalache.tla.Tool.main(Tool.scala)
2023-03-03T15:59:18,769 [main] ERROR a.f.a.t.Tool\$ - <unknown>: internal error in type checking: Inliner: Unable to unify generic signature (() => Set(Int)) of Heights with the concrete type Set(a4621)
at.forsyte.apalache.infra.AdaptedException: <unknown>: internal error in type checking: Inliner: Unable to unify generic signature (() => Set(Int)) of Heights with the concrete type Set(a4621)
	at at.forsyte.apalache.infra.passes.PassChainExecutor\$.run(PassChainExecutor.scala:39)
	at at.forsyte.apalache.tla.tooling.opt.CheckCmd.run(CheckCmd.scala:132)
	at at.forsyte.apalache.tla.Tool\$.runCommand(Tool.scala:138)
	at at.forsyte.apalache.tla.Tool\$.run(Tool.scala:118)
	at at.forsyte.apalache.tla.Tool\$.main(Tool.scala:40)
	at at.forsyte.apalache.tla.Tool.main(Tool.scala)
```

## System information

- Apalache version: `0.30.2 build 333cdce`/`0.29.2 build 8a342d2`/`0.25.10 build 202d216`/`0.25.3 build 72baae9`
- OS: `Windows 11`
- JDK version: `17.0.4.1`

**Comment by Kukovec** [comment]
Hi @michwqy, thanks for submitting, we'll take a look at this ASAP.

**Comment by Kukovec** [comment]
Just to confirm, are you sure you're running `check IBCCore.tla`, and not `check MC_IBCCore.tla`? Shouldn't affect typechecking, but the former has undefined constants, so `check` shouldn't work, even in the absence of this behavior.

**Comment by Kukovec** [comment]
Alright, I've identified the issue. There seems to be a type collision between the _operator_ `Heights` in [IBCCore.tla](https://github.com/informalsystems/hermes/blob/master/docs/spec/tla/ibc-core/IBCCore.tla) and the _parameter_ `Heights` used in various methods in [IBCCoreDefinitions.tla](https://github.com/informalsystems/hermes/blob/master/docs/spec/tla/ibc-core/IBCCoreDefinitions.tla).

**Comment by Kukovec** [comment]
If you're looking for a short-term fix, you can circumvent this by renaming either the parameter(s) or the nullary operators. In the meantime, I'll try to open a PR in the Hermes repo, which removes the collision. It's not clear yet whether we plan on supporting this in Apalache, since this is somewhat of a parsing and language-design problem, but we _are_ going to roll out a warning.

**Comment by Kukovec** [comment]
Related: #2135, #2132

**Comment by michwqy** [comment]
Thanks for your help. I renamed all the parameter ```Heights``` in the ```IBCCoreDefinitions.tla```, modified the parts about ```Versions``` in the same file and solved a series of problems. I don't know if my modification is correct, but it eventually runs to ```PASS #13: BoundedChecker```. However I met a new error: 
```
PASS #13: BoundedChecker                                          I@16:21:42.998
State 0: Checking 2 state invariants                              I@16:21:43.669
Step 0: picking a transition out of 1 transition(s)               I@16:21:43.692
Step 1: Transition #6 is disabled                                 I@16:21:43.776
<unknown>: checker error: Unexpected equality test over types CellTFrom(Int) and CellTFrom(Str) E@16:21:43.904
at.forsyte.apalache.infra.AdaptedException: <unknown>: checker error: Unexpected equality test over types CellTFrom(Int) and CellTFrom(Str)
        at at.forsyte.apalache.infra.Executor.run(Executor.scala:37)
        at at.forsyte.apalache.tla.tooling.opt.CheckCmd.run(CheckCmd.scala:87)
        at at.forsyte.apalache.tla.Tool$.runCommand(Tool.scala:135)
        at at.forsyte.apalache.tla.Tool$.run(Tool.scala:115)
        at at.forsyte.apalache.tla.Tool$.main(Tool.scala:36)
        at at.forsyte.apalache.tla.Tool.main(Tool.scala)
Please report an issue at [https://github.com/informalsystems/apalache/issues]: at.forsyte.apalache.infra.AdaptedException: <unknown>: checker error: Unexpected equality test over types CellTFrom(Int) and CellTFrom(Str)
```
Since it has no specific location, I don't know where to start debugging. Do you have any suggestions or the modified spec that can successfully run on apalache?

**Comment by Kukovec** [comment]
> Since it has no specific location, I don't know where to start debugging. Do you have any suggestions or the modified spec that can successfully run on apalache?

I've just opened a PR: https://github.com/informalsystems/hermes/pull/3137. You can use the spec from there. I've checked that it passes at least 1 step against `MC_IBCCore.tla`.

**Comment by michwqy** [comment]
Thanks a lot. It works. But what puzzles me is why do both ```Heights``` and ```Versions``` appear in the ```IBCCore.tla``` and parameters in ```IBCCoreDefinitions.tla```, but ```Heights``` need to be modified while ```Versions``` not?

**Comment by Kukovec** [comment]
> Thanks a lot. It works. But what puzzles me is why do both `Heights` and `Versions` appear in the `IBCCore.tla` and parameters in `IBCCoreDefinitions.tla`, but `Heights` need to be modified while `Versions` not?

They're not actually used in the same way though. `Versions` exists only inside e.g. `Chain`, but not also in `IBCCore`, whereas the latter defines its own global operator named `Heights`.
So an operator named `Versions`, which could clash with a parameter named `Versions` does not exist in the `IBCCore` namespace (only `Chain!Versions`).

**Comment by Kukovec** [comment]
I'm going to mark this issue closed via https://github.com/informalsystems/hermes/pull/3137. We are aware that the underlying problem persists, but there's other GH issues to track that and potential workarounds.
