### ISSUE TITLE
`at.forsyte.apalache.tla.lir.MalformedTlaError` thrown by pretty printer on safely constructed IR

### ISSUE THREAD

**Issue by shonfeder** [informalsystems/apalache#2511]
## Impact

Breaks conversion of Quint `replaceAt`

## Input specification

```
module lists {
  var n: int
  var l: List[int]

  action Init = all {
    n' = 0,
    l' = List(0),
  }

  def r = l.replaceAt(0, n)

  action Next = all {
    n' = n + 1,
    l' = l.append(n + 1),
  }
}
```

## The command line parameters used to run the tool

```
--write-intermediate
```

## Expected behavior

Parsed the spec.

## Log files

Note that I've extended the error message from the pretty printer exception to
show what it is choking on: `Malformed expression '0 + 1':: [l EXCEPT ![(0 + 1)] = n]`

<details>

```
2023-03-29T15:08:20,892 [main] INFO  a.f.a.t.Tool\$ - # APALACHE version: v0.30.5-23-g6f76c3768 | build: v0.30.5-23-g6f76c3768
2023-03-29T15:08:20,932 [main] INFO  a.f.a.t.t.o.CheckCmd - Tuning: search.outputTraces=false
2023-03-29T15:08:21,269 [main] INFO  a.f.a.i.p.PassChainExecutor\$ - PASS #0: SanyParser
2023-03-29T15:08:21,921 [main] DEBUG a.f.a.i.p.PassChainExecutor\$ - Adapted exception intercepted: 
at.forsyte.apalache.tla.lir.MalformedTlaError: 1 Malformed expression '0 + 1':
	at at.forsyte.apalache.io.lir.PrettyWriter\$\$anonfun\$1.applyOrElse(PrettyWriter.scala:363)
	at at.forsyte.apalache.io.lir.PrettyWriter\$\$anonfun\$1.applyOrElse(PrettyWriter.scala:357)
	at scala.collection.immutable.List.collect(List.scala:267)
	at scala.collection.immutable.List.collect(List.scala:79)
	at at.forsyte.apalache.io.lir.PrettyWriter.exToDoc(PrettyWriter.scala:357)
	at at.forsyte.apalache.io.lir.PrettyWriter.declToDoc(PrettyWriter.scala:618)
	at at.forsyte.apalache.io.lir.PrettyWriter.\$anonfun\$modToDoc\$1(PrettyWriter.scala:121)
	at scala.collection.immutable.List.map(List.scala:250)
	at at.forsyte.apalache.io.lir.PrettyWriter.modToDoc(PrettyWriter.scala:121)
	at at.forsyte.apalache.io.lir.PrettyWriter.write(PrettyWriter.scala:44)
	at at.forsyte.apalache.io.annotations.PrettyWriterWithAnnotations.write(PrettyWriterWithAnnotations.scala:59)
	at at.forsyte.apalache.io.lir.TlaWriterFactory.\$anonfun\$writeModuleWithFormatWriter\$3(TlaWriterFactory.scala:46)
	at at.forsyte.apalache.io.lir.TlaWriterFactory.\$anonfun\$writeModuleWithFormatWriter\$3\$adapted(TlaWriterFactory.scala:46)
	at at.forsyte.apalache.io.OutputManager\$.withWriter(OutputManager.scala:186)
	at at.forsyte.apalache.io.OutputManager\$.\$anonfun\$withWriterInIntermediateDir\$1(OutputManager.scala:220)
	at at.forsyte.apalache.io.OutputManager\$.\$anonfun\$withWriterInIntermediateDir\$1\$adapted(OutputManager.scala:220)
	at at.forsyte.apalache.io.OutputManager\$.\$anonfun\$withWriterInIntermediateDir\$2(OutputManager.scala:223)
	at at.forsyte.apalache.io.OutputManager\$.\$anonfun\$withWriterInIntermediateDir\$2\$adapted(OutputManager.scala:222)
	at scala.Option.map(Option.scala:242)
	at at.forsyte.apalache.io.OutputManager\$.withWriterInIntermediateDir(OutputManager.scala:222)
	at at.forsyte.apalache.io.lir.TlaWriterFactory.\$anonfun\$writeModuleWithFormatWriter\$2(TlaWriterFactory.scala:44)
	at at.forsyte.apalache.io.lir.TlaWriterFactory.\$anonfun\$writeModuleWithFormatWriter\$2\$adapted(TlaWriterFactory.scala:44)
	at at.forsyte.apalache.io.lir.TlaWriterFactory.writeModuleWithFormatWriter(TlaWriterFactory.scala:46)
	at at.forsyte.apalache.io.lir.TlaWriterFactory.writeModuleWithFormatWriter\$(TlaWriterFactory.scala:36)
	at at.forsyte.apalache.io.annotations.PrettyWriterWithAnnotationsFactory.writeModuleWithFormatWriter(PrettyWriterWithAnnotationsFactory.scala:13)
	at at.forsyte.apalache.io.lir.TlaWriterFactory.writeModuleToTla(TlaWriterFactory.scala:62)
	at at.forsyte.apalache.io.lir.TlaWriterFactory.writeModuleToTla\$(TlaWriterFactory.scala:58)
	at at.forsyte.apalache.io.annotations.PrettyWriterWithAnnotationsFactory.writeModuleToTla(PrettyWriterWithAnnotationsFactory.scala:13)
	at at.forsyte.apalache.io.lir.TlaWriterFactory.writeModuleAllFormats(TlaWriterFactory.scala:27)
	at at.forsyte.apalache.io.lir.TlaWriterFactory.writeModuleAllFormats\$(TlaWriterFactory.scala:26)
	at at.forsyte.apalache.io.annotations.PrettyWriterWithAnnotationsFactory.writeModuleAllFormats(PrettyWriterWithAnnotationsFactory.scala:13)
	at at.forsyte.apalache.tla.passes.imp.PassWithOutputs.writeOut(PassWithOutputs.scala:18)
	at at.forsyte.apalache.tla.passes.imp.PassWithOutputs.writeOut\$(PassWithOutputs.scala:16)
	at at.forsyte.apalache.tla.passes.imp.SanyParserPassImpl.writeOut(SanyParserPassImpl.scala:32)
	at at.forsyte.apalache.tla.passes.imp.SanyParserPassImpl.saveLoadedModule(SanyParserPassImpl.scala:87)
	at at.forsyte.apalache.tla.passes.imp.SanyParserPassImpl.\$anonfun\$parseSource\$2(SanyParserPassImpl.scala:130)
	at scala.util.Either.flatMap(Either.scala:352)
	at at.forsyte.apalache.tla.passes.imp.SanyParserPassImpl.\$anonfun\$parseSource\$1(SanyParserPassImpl.scala:129)
	at scala.util.Either.flatMap(Either.scala:352)
	at at.forsyte.apalache.tla.passes.imp.SanyParserPassImpl.parseSource(SanyParserPassImpl.scala:124)
	at at.forsyte.apalache.tla.passes.imp.SanyParserPassImpl.execute(SanyParserPassImpl.scala:109)
	at at.forsyte.apalache.infra.passes.PassChainExecutor\$.exec(PassChainExecutor.scala:64)
	at at.forsyte.apalache.infra.passes.PassChainExecutor\$.\$anonfun\$runPassOnModule\$3(PassChainExecutor.scala:53)
	at scala.util.Either.flatMap(Either.scala:352)
	at at.forsyte.apalache.infra.passes.PassChainExecutor\$.\$anonfun\$runPassOnModule\$1(PassChainExecutor.scala:51)
	at scala.collection.LinearSeqOps.foldLeft(LinearSeq.scala:183)
	at scala.collection.LinearSeqOps.foldLeft\$(LinearSeq.scala:179)
	at scala.collection.immutable.List.foldLeft(List.scala:79)
	at at.forsyte.apalache.infra.passes.PassChainExecutor\$.runOnPasses(PassChainExecutor.scala:44)
	at at.forsyte.apalache.infra.passes.PassChainExecutor\$.run(PassChainExecutor.scala:34)
	at at.forsyte.apalache.tla.tooling.opt.CheckCmd.run(CheckCmd.scala:132)
	at at.forsyte.apalache.tla.Tool\$.runCommand(Tool.scala:138)
	at at.forsyte.apalache.tla.Tool\$.run(Tool.scala:118)
	at at.forsyte.apalache.tla.Tool\$.main(Tool.scala:40)
	at at.forsyte.apalache.tla.Tool.main(Tool.scala)
2023-03-29T15:08:21,927 [main] ERROR a.f.a.t.Tool\$ - <unknown>: unexpected TLA+ expression: 1 Malformed expression '0 + 1':: [l EXCEPT ![(0 + 1)] = n]
at.forsyte.apalache.infra.AdaptedException: <unknown>: unexpected TLA+ expression: 1 Malformed expression '0 + 1':: [l EXCEPT ![(0 + 1)] = n]
	at at.forsyte.apalache.infra.passes.PassChainExecutor\$.run(PassChainExecutor.scala:39)
	at at.forsyte.apalache.tla.tooling.opt.CheckCmd.run(CheckCmd.scala:132)
	at at.forsyte.apalache.tla.Tool\$.runCommand(Tool.scala:138)
	at at.forsyte.apalache.tla.Tool\$.run(Tool.scala:118)
	at at.forsyte.apalache.tla.Tool\$.main(Tool.scala:40)
	at at.forsyte.apalache.tla.Tool.main(Tool.scala)
```
</details>

## System information

- Apalache version: `v0.30.5-23-g6f76c3768 build v0.30.5-23-g6f76c3768`
- OS: `Linux`
- JDK version: `19.0.2`

## Triage checklist (for maintainers)

- [ ] Reproduce the bug on the main development branch.
- [ ] Add the issue to the apalache GitHub project.
- [ ] If the bug is high impact, ensure someone available is assigned to fix it.

**Comment by konnov** [comment]
As always, `TestSanyImporter` shows how it works precisely:

https://github.com/informalsystems/apalache/blob/8c5e1575d585d95bef24ebd2585773353153be20/tla-io/src/test/scala/at/forsyte/apalache/tla/imp/TestSanyImporter.scala#L932-L1004

**Comment by shonfeder** [comment]
As discussed in slack, the short term fix is to adapt the builder to account for this quirky behavior. @Kukovec will help with this! 🙏
