### ISSUE TITLE
Shai fails with RESOURCE_EXHAUSTED: gRPC message exceeds maximum size

### ISSUE THREAD

**Issue by thpani** [informalsystems/apalache#2622]
On a sufficiently large Quint spec (e.g., [ics20](https://github.com/informalsystems/quint/blob/89506049fd9a1b75998106a187566ed258b64c23/examples/cosmos/ics20/ics20.qnt)), Shai fails with

```
io.grpc.StatusRuntimeException: RESOURCE_EXHAUSTED: gRPC message exceeds maximum size 4194304: 5177182
	at io.grpc.Status.asRuntimeException(Status.java:530)
	at io.grpc.internal.MessageDeframer.processHeader(MessageDeframer.java:392)
	at io.grpc.internal.MessageDeframer.deliver(MessageDeframer.java:272)
	at io.grpc.internal.MessageDeframer.request(MessageDeframer.java:162)
	at io.grpc.internal.AbstractStream$TransportState$1RequestRunnable.run(AbstractStream.java:233)
	at io.grpc.netty.NettyServerStream$TransportState$1.run(NettyServerStream.java:188)
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:566)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by shonfeder** [comment]
Yup. This is the error @rnbguy has hit trying to use quint `verify`
