### ISSUE TITLE
Exception when checking invariant with `--max-error` and `--view` options specified

### ISSUE THREAD

**Issue by will62794** [informalsystems/apalache#2683]
## Impact

Apalache throws an exception when trying to generate multiple counterexamples for an invariant when using a `--max-error` and a specified `--view` expression. Possibly related to #1004 and/or #2139.

## Input specification

```tla
------------------------------- MODULE TwoPhase ----------------------------- 
\* benchmark: tla-twophase
EXTENDS TLC, Naturals

CONSTANT 
    \* @type: Set(RM);
    RM \* The set of resource managers
    
VARIABLES
  \* @type: RM -> Str;
  rmState,       \* $rmState[rm]$ is the state of resource manager RM.
  \* @type: Str;
  tmState,       \* The state of the transaction manager.
  \* @type: Set(RM);
  tmPrepared,    \* The set of RMs from which the TM has received "Prepared" messages
  \* @type: Set( { type: Str, rm: RM } );
  msgsPrepared,
  \* @type: Set( { type: Str } );
  msgsAbortCommit

vars == <<rmState, tmState, tmPrepared, msgsPrepared, msgsAbortCommit>>

TypeOK ==  
  /\ rmState \in [RM -> {"working", "prepared", "committed", "aborted"}]
  /\ tmState \in {"init", "committed", "aborted"}
  /\ tmPrepared \in SUBSET RM
  /\ msgsPrepared \in SUBSET [type : {"Prepared"}, rm : RM]
  /\ msgsAbortCommit \in SUBSET [type : {"Commit", "Abort"}]

Init ==   
  /\ rmState = [rm \in RM |-> "working"]
  /\ tmState = "init"
  /\ tmPrepared   = {}
  /\ msgsPrepared = {}
  /\ msgsAbortCommit = {}
-----------------------------------------------------------------------------

TMRcvPrepared(rm) ==
  (*************************************************************************)
  (* The TM receives a $"Prepared"$ message from resource manager $rm$.    *)
  (*************************************************************************)
  /\ tmState = "init"
  /\ [type |-> "Prepared", rm |-> rm] \in msgsPrepared
  /\ tmPrepared' = tmPrepared \cup {rm}
  /\ UNCHANGED <<rmState, tmState, msgsPrepared, msgsAbortCommit>>

TMCommit ==
  (*************************************************************************)
  (* The TM commits the transaction; enabled iff the TM is in its initial  *)
  (* state and every RM has sent a $"Prepared"$ message.                   *)
  (*************************************************************************)
  /\ tmState = "init"
  /\ tmPrepared = RM
  /\ tmState' = "committed"
  /\ msgsAbortCommit' = msgsAbortCommit \cup {[type |-> "Commit"]}
  /\ UNCHANGED <<rmState, tmPrepared, msgsPrepared>>

TMAbort ==
  (*************************************************************************)
  (* The TM spontaneously aborts the transaction.                          *)
  (*************************************************************************)
  /\ tmState = "init"
  /\ tmState' = "aborted"
  /\ msgsAbortCommit' = msgsAbortCommit \cup {[type |-> "Abort"]}
  /\ UNCHANGED <<rmState, tmPrepared, msgsPrepared>>

RMPrepare(rm) == 
  (*************************************************************************)
  (* Resource manager $rm$ prepares.                                       *)
  (*************************************************************************)
  /\ rmState[rm] = "working"
  /\ rmState' = [rmState EXCEPT ![rm] = "prepared"]
  /\ msgsPrepared' = msgsPrepared \cup {[type |-> "Prepared", rm |-> rm]}
  /\ UNCHANGED <<tmState, tmPrepared, msgsAbortCommit>>
  
RMChooseToAbort(rm) ==
  (*************************************************************************)
  (* Resource manager $rm$ spontaneously decides to abort.  As noted       *)
  (* above, $rm$ does not send any message in our simplified spec.         *)
  (*************************************************************************)
  /\ rmState[rm] = "working"
  /\ rmState' = [rmState EXCEPT ![rm] = "aborted"]
  /\ UNCHANGED <<tmState, tmPrepared, msgsPrepared, msgsAbortCommit>>

RMRcvCommitMsg(rm) ==
  (*************************************************************************)
  (* Resource manager $rm$ is told by the TM to commit.                    *)
  (*************************************************************************)
  /\ [type |-> "Commit"] \in msgsAbortCommit
  /\ rmState[rm] # "committed" \* no need to commit twice.
  /\ rmState' = [rmState EXCEPT ![rm] = "committed"]
  /\ UNCHANGED <<tmState, tmPrepared, msgsPrepared, msgsAbortCommit>>

RMRcvAbortMsg(rm) ==
  (*************************************************************************)
  (* Resource manager $rm$ is told by the TM to abort.                     *)
  (*************************************************************************)
  /\ [type |-> "Abort"] \in msgsAbortCommit
  /\ rmState[rm] # "aborted" \* no need to abort twice.
  /\ rmState' = [rmState EXCEPT ![rm] = "aborted"]
  /\ UNCHANGED <<tmState, tmPrepared, msgsPrepared, msgsAbortCommit>>

Next ==
  \/ TMCommit 
  \/ TMAbort
  \/ \E rm \in RM : TMRcvPrepared(rm) 
  \/ \E rm \in RM : RMPrepare(rm) 
  \/ \E rm \in RM : RMChooseToAbort(rm)
  \/ \E rm \in RM : RMRcvCommitMsg(rm) 
  \/ \E rm \in RM : RMRcvAbortMsg(rm)
-----------------------------------------------------------------------------
TPSpec == Init /\ [][Next]_<<rmState, tmState, tmPrepared, msgsPrepared, msgsAbortCommit>>

NextUnchanged == UNCHANGED vars

Symmetry == Permutations(RM)

TCConsistent ==  
  \A rm1, rm2 \in RM : ~ (rmState[rm1] = "aborted" /\ rmState[rm2] = "committed")

\* Constant initialization for model checking with Apalache.
CInit == RM = {"1_OF_RM", "2_OF_RM", "3_OF_RM"}

InvStrengthened ==
    /\ TCConsistent

IndCand ==
    /\ TypeOK
    /\ InvStrengthened

=============================================================================
````

## The command line parameters used to run the tool

```
--out-dir=gen_tla/apalache_ctigen --max-error=10 --view=vars --run-dir=gen_tla/apalache_ctigen --cinit=CInit --init=IndCand --next=Next --inv=InvStrengthened --length=1
```

## Expected behavior

I expected Apalache to succeed and generate multiple counterexamples for the invariant specified. Note that it succeeds on the same spec if run without the `--max-error` or `--view` flags i.e. running
```
apalache/bin/apalache-mc check --out-dir=gen_tla/apalache_ctigen --run-dir=gen_tla/apalache_ctigen --cinit=CInit --init=IndCand --next=Next --inv=InvStrengthened --length=1 TwoPhase.tla
```
completes successfully and correctly generates 1 error.

## Log files

<details>

```
2023-08-01T01:22:39,905 [main] INFO  a.f.a.t.Tool\$ - # APALACHE version: 0.40.6 | build: 626668c
2023-08-01T01:22:39,935 [main] INFO  a.f.a.t.t.o.CheckCmd - Tuning: search.outputTraces=false
2023-08-01T01:22:40,130 [main] INFO  a.f.a.i.p.PassChainExecutor\$ - PASS #0: SanyParser
2023-08-01T01:22:40,586 [main] DEBUG a.f.a.i.p.PassChainExecutor\$ - PASS #0: SanyParser [OK]
2023-08-01T01:22:40,587 [main] INFO  a.f.a.i.p.PassChainExecutor\$ - PASS #1: TypeCheckerSnowcat
2023-08-01T01:22:40,587 [main] INFO  a.f.a.t.p.t.EtcTypeCheckerPassImpl -  > Running Snowcat .::.
2023-08-01T01:22:41,204 [main] INFO  a.f.a.t.p.t.EtcTypeCheckerPassImpl -  > Your types are purrfect!
2023-08-01T01:22:41,205 [main] INFO  a.f.a.t.p.t.EtcTypeCheckerPassImpl -  > All expressions are typed
2023-08-01T01:22:41,205 [main] DEBUG a.f.a.i.p.PassChainExecutor\$ - PASS #1: TypeCheckerSnowcat [OK]
2023-08-01T01:22:41,206 [main] INFO  a.f.a.i.p.PassChainExecutor\$ - PASS #2: ConfigurationPass
2023-08-01T01:22:41,212 [main] INFO  a.f.a.t.p.p.ConfigurationPassImpl -   > Set the initialization predicate to IndCand
2023-08-01T01:22:41,213 [main] INFO  a.f.a.t.p.p.ConfigurationPassImpl -   > Set the transition predicate to Next
2023-08-01T01:22:41,214 [main] INFO  a.f.a.t.p.p.ConfigurationPassImpl -   > Set the constant initialization predicate to CInit
2023-08-01T01:22:41,215 [main] INFO  a.f.a.t.p.p.ConfigurationPassImpl -   > Set an invariant to InvStrengthened
2023-08-01T01:22:41,223 [main] DEBUG a.f.a.i.p.PassChainExecutor\$ - PASS #2: ConfigurationPass [OK]
2023-08-01T01:22:41,224 [main] INFO  a.f.a.i.p.PassChainExecutor\$ - PASS #3: DesugarerPass
2023-08-01T01:22:41,224 [main] INFO  a.f.a.t.p.p.DesugarerPassImpl -   > Desugaring...
2023-08-01T01:22:41,479 [main] DEBUG a.f.a.i.p.PassChainExecutor\$ - PASS #3: DesugarerPass [OK]
2023-08-01T01:22:41,481 [main] INFO  a.f.a.i.p.PassChainExecutor\$ - PASS #4: InlinePass
2023-08-01T01:22:41,482 [main] INFO  a.f.a.t.p.p.InlinePassImpl - Leaving only relevant operators: CInit, CInitPrimed, IndCand, IndCandPrimed, InvStrengthened, Next, vars
2023-08-01T01:22:41,556 [main] DEBUG a.f.a.i.p.PassChainExecutor\$ - PASS #4: InlinePass [OK]
2023-08-01T01:22:41,556 [main] INFO  a.f.a.i.p.PassChainExecutor\$ - PASS #5: TemporalPass
2023-08-01T01:22:41,557 [main] INFO  a.f.a.t.p.p.TemporalPassImpl -   > Rewriting temporal operators...
2023-08-01T01:22:41,557 [main] INFO  a.f.a.t.p.p.TemporalPassImpl -   > No temporal property specified, nothing to encode
2023-08-01T01:22:41,558 [main] DEBUG a.f.a.i.p.PassChainExecutor\$ - PASS #5: TemporalPass [OK]
2023-08-01T01:22:41,558 [main] INFO  a.f.a.i.p.PassChainExecutor\$ - PASS #6: InlinePass
2023-08-01T01:22:41,558 [main] INFO  a.f.a.t.p.p.InlinePassImpl - Leaving only relevant operators: CInit, CInitPrimed, IndCand, IndCandPrimed, InvStrengthened, Next, vars
2023-08-01T01:22:41,566 [main] DEBUG a.f.a.i.p.PassChainExecutor\$ - PASS #6: InlinePass [OK]
2023-08-01T01:22:41,567 [main] INFO  a.f.a.i.p.PassChainExecutor\$ - PASS #7: PrimingPass
2023-08-01T01:22:41,570 [main] INFO  a.f.a.t.p.a.PrimingPassImpl -   > Introducing CInitPrimed for CInit'
2023-08-01T01:22:41,571 [main] INFO  a.f.a.t.p.a.PrimingPassImpl -   > Introducing IndCandPrimed for IndCand'
2023-08-01T01:22:41,572 [main] DEBUG a.f.a.i.p.PassChainExecutor\$ - PASS #7: PrimingPass [OK]
2023-08-01T01:22:41,573 [main] INFO  a.f.a.i.p.PassChainExecutor\$ - PASS #8: VCGen
2023-08-01T01:22:41,574 [main] INFO  a.f.a.t.b.p.VCGenPassImpl -   > Producing verification conditions from the invariant InvStrengthened
2023-08-01T01:22:41,574 [main] INFO  a.f.a.t.b.p.VCGenPassImpl -   > Using state view vars
2023-08-01T01:22:41,584 [main] INFO  a.f.a.t.b.VCGenerator -   > VCGen produced 1 verification condition(s)
2023-08-01T01:22:41,586 [main] DEBUG a.f.a.i.p.PassChainExecutor\$ - PASS #8: VCGen [OK]
2023-08-01T01:22:41,587 [main] INFO  a.f.a.i.p.PassChainExecutor\$ - PASS #9: PreprocessingPass
2023-08-01T01:22:41,587 [main] INFO  a.f.a.t.p.p.PreproPassImpl -   > Before preprocessing: unique renaming
2023-08-01T01:22:41,603 [main] INFO  a.f.a.t.p.p.PreproPassImpl -  > Applying standard transformations:
2023-08-01T01:22:41,608 [main] INFO  a.f.a.t.p.p.PreproPassImpl -   > PrimePropagation
2023-08-01T01:22:41,612 [main] INFO  a.f.a.t.p.p.PreproPassImpl -   > Desugarer
2023-08-01T01:22:41,618 [main] INFO  a.f.a.t.p.p.PreproPassImpl -   > UniqueRenamer
2023-08-01T01:22:41,624 [main] INFO  a.f.a.t.p.p.PreproPassImpl -   > Normalizer
2023-08-01T01:22:41,629 [main] INFO  a.f.a.t.p.p.PreproPassImpl -   > Keramelizer
2023-08-01T01:22:41,646 [main] INFO  a.f.a.t.p.p.PreproPassImpl -   > After preprocessing: UniqueRenamer
2023-08-01T01:22:41,658 [main] DEBUG a.f.a.i.p.PassChainExecutor\$ - PASS #9: PreprocessingPass [OK]
2023-08-01T01:22:41,658 [main] INFO  a.f.a.i.p.PassChainExecutor\$ - PASS #10: TransitionFinderPass
2023-08-01T01:22:41,690 [main] INFO  a.f.a.t.p.a.TransitionPassImpl -   > Found 1 initializing transitions
2023-08-01T01:22:41,703 [main] INFO  a.f.a.t.p.a.TransitionPassImpl -   > Found 7 transitions
2023-08-01T01:22:41,704 [main] INFO  a.f.a.t.p.a.TransitionPassImpl -   > Found constant initializer CInit
2023-08-01T01:22:41,711 [main] INFO  a.f.a.t.p.a.TransitionPassImpl -   > Applying unique renaming
2023-08-01T01:22:41,716 [main] DEBUG a.f.a.i.p.PassChainExecutor\$ - PASS #10: TransitionFinderPass [OK]
2023-08-01T01:22:41,717 [main] INFO  a.f.a.i.p.PassChainExecutor\$ - PASS #11: OptimizationPass
2023-08-01T01:22:41,727 [main] INFO  a.f.a.t.p.p.OptPassImpl -  > Applying optimizations:
2023-08-01T01:22:41,728 [main] INFO  a.f.a.t.p.p.OptPassImpl -   > ConstSimplifier
2023-08-01T01:22:41,736 [main] INFO  a.f.a.t.p.p.OptPassImpl -   > ExprOptimizer
2023-08-01T01:22:41,741 [main] INFO  a.f.a.t.p.p.OptPassImpl -   > SetMembershipSimplifier
2023-08-01T01:22:41,743 [main] INFO  a.f.a.t.p.p.OptPassImpl -   > ConstSimplifier
2023-08-01T01:22:41,748 [main] DEBUG a.f.a.i.p.PassChainExecutor\$ - PASS #11: OptimizationPass [OK]
2023-08-01T01:22:41,748 [main] INFO  a.f.a.i.p.PassChainExecutor\$ - PASS #12: AnalysisPass
2023-08-01T01:22:41,750 [main] INFO  a.f.a.t.b.p.AnalysisPassImpl -  > Marking skolemizable existentials and sets to be expanded...
2023-08-01T01:22:41,752 [main] INFO  a.f.a.t.b.p.AnalysisPassImpl -   > Skolemization
2023-08-01T01:22:41,753 [main] INFO  a.f.a.t.b.p.AnalysisPassImpl -   > Expansion
2023-08-01T01:22:41,757 [main] INFO  a.f.a.t.b.p.AnalysisPassImpl -   > Remove unused let-in defs
2023-08-01T01:22:41,761 [main] INFO  a.f.a.t.b.p.AnalysisPassImpl -  > Running analyzers...
2023-08-01T01:22:41,765 [main] INFO  a.f.a.t.b.p.AnalysisPassImpl -   > Introduced expression grades
2023-08-01T01:22:41,766 [main] DEBUG a.f.a.i.p.PassChainExecutor\$ - PASS #12: AnalysisPass [OK]
2023-08-01T01:22:41,766 [main] INFO  a.f.a.i.p.PassChainExecutor\$ - PASS #13: BoundedChecker
2023-08-01T01:22:41,784 [main] DEBUG a.f.a.t.b.s.Z3SolverContext - Creating Z3 solver context 0
2023-08-01T01:22:42,031 [main] DEBUG a.f.a.t.b.t.TransitionExecutorImpl - Initializing CONSTANTS
2023-08-01T01:22:42,067 [main] DEBUG a.f.a.t.b.t.TransitionExecutorImpl - Step #0, transition #0
2023-08-01T01:22:42,067 [main] DEBUG a.f.a.t.b.t.TransitionExecutorImpl - Translating to SMT
2023-08-01T01:22:42,254 [main] DEBUG a.f.a.t.b.SeqModelChecker - Step 0: Transition #0. Is it enabled?
2023-08-01T01:22:42,259 [main] DEBUG a.f.a.t.b.SeqModelChecker - Step 0: Transition #0 is enabled
2023-08-01T01:22:42,259 [main] INFO  a.f.a.t.b.SeqModelChecker - State 0: Checking 1 state invariants
2023-08-01T01:22:42,260 [main] DEBUG a.f.a.t.b.SeqModelChecker - State 0: Checking state invariant 0
2023-08-01T01:22:42,287 [main] INFO  a.f.a.t.b.SeqModelChecker - State 0: state invariant 0 holds.
2023-08-01T01:22:42,295 [main] INFO  a.f.a.t.b.t.TransitionExecutorImpl - Step 0: picking a transition out of 1 transition(s)
2023-08-01T01:22:42,299 [main] DEBUG a.f.a.t.b.t.TransitionExecutorImpl - Step #1, transition #0
2023-08-01T01:22:42,300 [main] DEBUG a.f.a.t.b.t.TransitionExecutorImpl - Translating to SMT
2023-08-01T01:22:42,322 [main] DEBUG a.f.a.t.b.SeqModelChecker - Step 1: Transition #0. Is it enabled?
2023-08-01T01:22:42,323 [main] DEBUG a.f.a.t.b.SeqModelChecker - Step 1: Transition #0 is enabled
2023-08-01T01:22:42,325 [main] DEBUG a.f.a.t.b.t.TransitionExecutorImpl - Step #1, transition #1
2023-08-01T01:22:42,326 [main] DEBUG a.f.a.t.b.t.TransitionExecutorImpl - Translating to SMT
2023-08-01T01:22:42,332 [main] DEBUG a.f.a.t.b.SeqModelChecker - Step 1: Transition #1. Is it enabled?
2023-08-01T01:22:42,333 [main] DEBUG a.f.a.t.b.SeqModelChecker - Step 1: Transition #1 is enabled
2023-08-01T01:22:42,333 [main] DEBUG a.f.a.t.b.t.TransitionExecutorImpl - Step #1, transition #2
2023-08-01T01:22:42,334 [main] DEBUG a.f.a.t.b.t.TransitionExecutorImpl - Translating to SMT
2023-08-01T01:22:42,348 [main] DEBUG a.f.a.t.b.SeqModelChecker - Step 1: Transition #2. Is it enabled?
2023-08-01T01:22:42,350 [main] DEBUG a.f.a.t.b.SeqModelChecker - Step 1: Transition #2 is enabled
2023-08-01T01:22:42,350 [main] DEBUG a.f.a.t.b.t.TransitionExecutorImpl - Step #1, transition #3
2023-08-01T01:22:42,351 [main] DEBUG a.f.a.t.b.t.TransitionExecutorImpl - Translating to SMT
2023-08-01T01:22:42,372 [main] DEBUG a.f.a.t.b.SeqModelChecker - Step 1: Transition #3. Is it enabled?
2023-08-01T01:22:42,373 [main] DEBUG a.f.a.t.b.SeqModelChecker - Step 1: Transition #3 is enabled
2023-08-01T01:22:42,374 [main] INFO  a.f.a.t.b.SeqModelChecker - State 1: Checking 1 state invariants
2023-08-01T01:22:42,374 [main] DEBUG a.f.a.t.b.SeqModelChecker - State 1: Checking state invariant 0
2023-08-01T01:22:42,389 [main] INFO  a.f.a.t.b.SeqModelChecker - State 1: state invariant 0 holds.
2023-08-01T01:22:42,391 [main] DEBUG a.f.a.t.b.t.TransitionExecutorImpl - Step #1, transition #4
2023-08-01T01:22:42,391 [main] DEBUG a.f.a.t.b.t.TransitionExecutorImpl - Translating to SMT
2023-08-01T01:22:42,410 [main] DEBUG a.f.a.t.b.SeqModelChecker - Step 1: Transition #4. Is it enabled?
2023-08-01T01:22:42,411 [main] DEBUG a.f.a.t.b.SeqModelChecker - Step 1: Transition #4 is enabled
2023-08-01T01:22:42,411 [main] INFO  a.f.a.t.b.SeqModelChecker - State 1: Checking 1 state invariants
2023-08-01T01:22:42,412 [main] DEBUG a.f.a.t.b.SeqModelChecker - State 1: Checking state invariant 0
2023-08-01T01:22:42,669 [main] INFO  a.f.a.t.b.DumpFilesModelCheckerListener\$ - Check the trace in: /home/willyschultz/endive/benchmarks/gen_tla/apalache_ctigen/TwoPhase.tla/2023-08-01T01-22-39_12516981999867565060/violation1.tla, /home/willyschultz/endive/benchmarks/gen_tla/apalache_ctigen/TwoPhase.tla/2023-08-01T01-22-39_12516981999867565060/MCviolation1.out, /home/willyschultz/endive/benchmarks/gen_tla/apalache_ctigen/TwoPhase.tla/2023-08-01T01-22-39_12516981999867565060/violation1.json, /home/willyschultz/endive/benchmarks/gen_tla/apalache_ctigen/TwoPhase.tla/2023-08-01T01-22-39_12516981999867565060/violation1.itf.json
2023-08-01T01:22:42,670 [main] INFO  a.f.a.t.b.SeqModelChecker - State 1: state invariant 0 violated.
2023-08-01T01:22:42,701 [main] DEBUG a.f.a.i.p.PassChainExecutor\$ - Adapted exception intercepted: 
at.forsyte.apalache.tla.bmcmt.CheckerException: Unexpected equality test over types CellTFrom([rm: RM, type: Str]) and CellTFrom({ rm: RM, type: Str })
	at at.forsyte.apalache.tla.bmcmt.LazyEquality.cacheOneEqConstraint(LazyEquality.scala:172)
	at at.forsyte.apalache.tla.bmcmt.LazyEquality.makeOne\$1(LazyEquality.scala:108)
	at at.forsyte.apalache.tla.bmcmt.LazyEquality.\$anonfun\$cacheEqConstraints\$2(LazyEquality.scala:111)
	at scala.collection.LinearSeqOps.foldLeft(LinearSeq.scala:183)
	at scala.collection.LinearSeqOps.foldLeft\$(LinearSeq.scala:179)
	at scala.collection.immutable.List.foldLeft(List.scala:79)
	at at.forsyte.apalache.tla.bmcmt.LazyEquality.cacheEqConstraints(LazyEquality.scala:111)
	at at.forsyte.apalache.tla.bmcmt.LazyEquality.subsetEq(LazyEquality.scala:316)
	at at.forsyte.apalache.tla.bmcmt.LazyEquality.mkSetEq(LazyEquality.scala:248)
	at at.forsyte.apalache.tla.bmcmt.LazyEquality.cacheOneEqConstraint(LazyEquality.scala:146)
	at at.forsyte.apalache.tla.bmcmt.LazyEquality.elemEq\$1(LazyEquality.scala:573)
	at at.forsyte.apalache.tla.bmcmt.LazyEquality.\$anonfun\$mkTupleEq\$1(LazyEquality.scala:580)
	at scala.collection.immutable.List.map(List.scala:250)
	at scala.collection.immutable.List.map(List.scala:79)
	at at.forsyte.apalache.tla.bmcmt.LazyEquality.mkTupleEq(LazyEquality.scala:580)
	at at.forsyte.apalache.tla.bmcmt.LazyEquality.cacheOneEqConstraint(LazyEquality.scala:163)
	at at.forsyte.apalache.tla.bmcmt.rules.EqRule.apply(EqRule.scala:55)
	at at.forsyte.apalache.tla.bmcmt.SymbStateRewriterImpl.rewriteOnce(SymbStateRewriterImpl.scala:355)
	at at.forsyte.apalache.tla.bmcmt.SymbStateRewriterImpl.doRecursive\$1(SymbStateRewriterImpl.scala:388)
	at at.forsyte.apalache.tla.bmcmt.SymbStateRewriterImpl.rewriteUntilDone(SymbStateRewriterImpl.scala:422)
	at at.forsyte.apalache.tla.bmcmt.rules.NegRule.apply(NegRule.scala:27)
	at at.forsyte.apalache.tla.bmcmt.SymbStateRewriterImpl.rewriteOnce(SymbStateRewriterImpl.scala:355)
	at at.forsyte.apalache.tla.bmcmt.SymbStateRewriterImpl.doRecursive\$1(SymbStateRewriterImpl.scala:388)
	at at.forsyte.apalache.tla.bmcmt.SymbStateRewriterImpl.rewriteUntilDone(SymbStateRewriterImpl.scala:422)
	at at.forsyte.apalache.tla.bmcmt.rules.OrRule.mapArg\$1(OrRule.scala:58)
	at at.forsyte.apalache.tla.bmcmt.rules.OrRule.\$anonfun\$apply\$2(OrRule.scala:62)
	at scala.collection.immutable.List.map(List.scala:246)
	at scala.collection.immutable.List.map(List.scala:79)
	at at.forsyte.apalache.tla.bmcmt.rules.OrRule.apply(OrRule.scala:62)
	at at.forsyte.apalache.tla.bmcmt.SymbStateRewriterImpl.rewriteOnce(SymbStateRewriterImpl.scala:355)
	at at.forsyte.apalache.tla.bmcmt.SymbStateRewriterImpl.doRecursive\$1(SymbStateRewriterImpl.scala:388)
	at at.forsyte.apalache.tla.bmcmt.SymbStateRewriterImpl.rewriteUntilDone(SymbStateRewriterImpl.scala:422)
	at at.forsyte.apalache.tla.bmcmt.trex.TransitionExecutorImpl.assertState(TransitionExecutorImpl.scala:216)
	at at.forsyte.apalache.tla.bmcmt.trex.FilteredTransitionExecutor.assertState(FilteredTransitionExecutor.scala:123)
	at at.forsyte.apalache.tla.bmcmt.trex.ConstrainedTransitionExecutor.assertPathOrConstraint(ConstrainedTransitionExecutor.scala:85)
	at at.forsyte.apalache.tla.bmcmt.trex.ConstrainedTransitionExecutor.addPathOrConstraint(ConstrainedTransitionExecutor.scala:38)
	at at.forsyte.apalache.tla.bmcmt.SeqModelChecker.\$anonfun\$excludePathView\$4(SeqModelChecker.scala:486)
	at at.forsyte.apalache.tla.bmcmt.SeqModelChecker.\$anonfun\$excludePathView\$4\$adapted(SeqModelChecker.scala:481)
	at scala.Option.foreach(Option.scala:437)
	at at.forsyte.apalache.tla.bmcmt.SeqModelChecker.excludePathView(SeqModelChecker.scala:481)
	at at.forsyte.apalache.tla.bmcmt.SeqModelChecker.\$anonfun\$checkInvariants\$2(SeqModelChecker.scala:360)
	at at.forsyte.apalache.tla.bmcmt.SeqModelChecker.\$anonfun\$checkInvariants\$2\$adapted(SeqModelChecker.scala:340)
	at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:576)
	at scala.collection.IterableOnceOps.foreach\$(IterableOnce.scala:574)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:933)
	at scala.collection.IterableOps\$WithFilter.foreach(Iterable.scala:903)
	at at.forsyte.apalache.tla.bmcmt.SeqModelChecker.checkInvariants(SeqModelChecker.scala:340)
	at at.forsyte.apalache.tla.bmcmt.SeqModelChecker.\$anonfun\$prepareTransitionsAndCheckInvariants\$5(SeqModelChecker.scala:243)
	at scala.runtime.java8.JFunction1\$mcVI\$sp.apply(JFunction1\$mcVI\$sp.scala:18)
	at scala.collection.immutable.Range.foreach(Range.scala:190)
	at at.forsyte.apalache.tla.bmcmt.SeqModelChecker.prepareTransitionsAndCheckInvariants(SeqModelChecker.scala:207)
	at at.forsyte.apalache.tla.bmcmt.SeqModelChecker.makeStep(SeqModelChecker.scala:123)
	at at.forsyte.apalache.tla.bmcmt.SeqModelChecker.run(SeqModelChecker.scala:66)
	at at.forsyte.apalache.tla.bmcmt.passes.BoundedCheckerPassImpl.runIncrementalChecker(BoundedCheckerPassImpl.scala:135)
	at at.forsyte.apalache.tla.bmcmt.passes.BoundedCheckerPassImpl.execute(BoundedCheckerPassImpl.scala:88)
	at at.forsyte.apalache.infra.passes.PassChainExecutor\$.exec(PassChainExecutor.scala:64)
	at at.forsyte.apalache.infra.passes.PassChainExecutor\$.\$anonfun\$runPassOnModule\$3(PassChainExecutor.scala:53)
	at scala.util.Either.flatMap(Either.scala:352)
	at at.forsyte.apalache.infra.passes.PassChainExecutor\$.\$anonfun\$runPassOnModule\$1(PassChainExecutor.scala:51)
	at scala.collection.LinearSeqOps.foldLeft(LinearSeq.scala:183)
	at scala.collection.LinearSeqOps.foldLeft\$(LinearSeq.scala:179)
	at scala.collection.immutable.List.foldLeft(List.scala:79)
	at at.forsyte.apalache.infra.passes.PassChainExecutor\$.runOnPasses(PassChainExecutor.scala:44)
	at at.forsyte.apalache.infra.passes.PassChainExecutor\$.run(PassChainExecutor.scala:34)
	at at.forsyte.apalache.tla.tooling.opt.CheckCmd.run(CheckCmd.scala:132)
	at at.forsyte.apalache.tla.Tool\$.runCommand(Tool.scala:138)
	at at.forsyte.apalache.tla.Tool\$.run(Tool.scala:118)
	at at.forsyte.apalache.tla.Tool\$.main(Tool.scala:40)
	at at.forsyte.apalache.tla.Tool.main(Tool.scala)
2023-08-01T01:22:42,710 [main] ERROR a.f.a.t.Tool\$ - <unknown>: checker error: Unexpected equality test over types CellTFrom([rm: RM, type: Str]) and CellTFrom({ rm: RM, type: Str })
at.forsyte.apalache.infra.AdaptedException: <unknown>: checker error: Unexpected equality test over types CellTFrom([rm: RM, type: Str]) and CellTFrom({ rm: RM, type: Str })
	at at.forsyte.apalache.infra.passes.PassChainExecutor\$.run(PassChainExecutor.scala:39)
	at at.forsyte.apalache.tla.tooling.opt.CheckCmd.run(CheckCmd.scala:132)
	at at.forsyte.apalache.tla.Tool\$.runCommand(Tool.scala:138)
	at at.forsyte.apalache.tla.Tool\$.run(Tool.scala:118)
	at at.forsyte.apalache.tla.Tool\$.main(Tool.scala:40)
	at at.forsyte.apalache.tla.Tool.main(Tool.scala)
```
</details>

## System information

- Apalache version: `0.40.6 build 626668c`
- OS: `Linux`
- JDK version: `17.0.7`

## Triage checklist (for maintainers)

- [ ] Reproduce the bug on the main development branch.
- [ ] Add the issue to the apalache GitHub project.
- [ ] If the bug is high impact, ensure someone available is assigned to fix it.

**Comment by thpani** [comment]
Thanks for the report!

I will leave some notes here on my debugging process:

So the issue is that we're hitting `LazyEquality` with a `RecT1` LHS and a `RecRowT1` RHS. Question is where these get constructed.

**Comment by will62794** [comment]
Note: updated the spec shown in the bug report above since it was missing the definition
```
\* Constant initialization for model checking with Apalache.
CInit == RM = {"1_OF_RM", "2_OF_RM", "3_OF_RM"}
```
that was included in the original spec and passed to the `--cinit` command line flag.

**Comment by shonfeder** [comment]
Thanks to @thpani work, this is fixed in the latest release: https://github.com/informalsystems/apalache/releases/tag/v0.41.3

thanks again for the report, @will62794!
