### ISSUE TITLE
Typechecking crashes

### ISSUE THREAD

**Issue by nano-o** [informalsystems/apalache#2816]
## Description

I am trying to set things up to model-check [Voting.tla](https://github.com/nano-o/TLA--Examples/blob/ApaVoting_with_cfg/specifications/Paxos/Voting.tla) with Apalache. I would like to reuse Voting.tla as much as possible, so I created [ApaVoting.tla](https://github.com/nano-o/TLA--Examples/blob/ApaVoting_with_cfg/specifications/Paxos/ApaVoting.tla), which instantiates Voting.tla, and [ApaVoting.cfg](https://github.com/nano-o/TLA--Examples/blob/ApaVoting_with_cfg/specifications/Paxos/ApaVoting.cfg), which substitutes 2 definitions of Voting.tla that are problematic for Apalache. However Apalache crashes as below.

See this PR for context: https://github.com/tlaplus/Examples/pull/112

## Impact

I have to duplicate most of Voting.tla in order to analyze with Apalache instead of being able to reuse it. See Voting2.tla and ApaVoting2.tla

## The command line parameters used to run the tool

```
script/run-docker.sh typecheck  ApaVoting.tla
```

## Expected behavior

No error

## Log files

<details>

```
2024-01-22T23:36:12,394 [main] INFO  a.f.a.t.Tool\$ - # APALACHE version: 0.44.2 | build: v0.44.2
2024-01-22T23:36:12,401 [main] INFO  a.f.a.t.t.o.TypeCheckCmd - Type checking ApaVoting.tla
2024-01-22T23:36:12,491 [main] INFO  a.f.a.i.p.PassChainExecutor\$ - PASS #0: SanyParser
2024-01-22T23:36:12,822 [main] DEBUG a.f.a.i.p.PassChainExecutor\$ - PASS #0: SanyParser [OK]
2024-01-22T23:36:12,823 [main] INFO  a.f.a.i.p.PassChainExecutor\$ - PASS #1: TypeCheckerSnowcat
2024-01-22T23:36:12,823 [main] INFO  a.f.a.t.p.t.EtcTypeCheckerPassImpl -  > Running Snowcat .::.
2024-01-22T23:36:13,037 [main] ERROR a.f.a.t.Tool\$ - Unhandled exception
java.lang.IllegalArgumentException: Unsupported expression: ∀g: (∀h: (((C!WFInductiveDefines(g, S, Def)) ∧ (C!WFInductiveDefines(h, S, Def))) ⇒ (g = h)))
	at at.forsyte.apalache.tla.typecheck.etc.ToEtcExpr.transform(ToEtcExpr.scala:896)
	at at.forsyte.apalache.tla.typecheck.etc.ToEtcExpr.apply(ToEtcExpr.scala:162)
	at at.forsyte.apalache.tla.typecheck.etc.ToEtcExpr.operDefToDecl(ToEtcExpr.scala:90)
	at at.forsyte.apalache.tla.typecheck.etc.ToEtcExpr.apply(ToEtcExpr.scala:52)
	at at.forsyte.apalache.tla.typecheck.TypeCheckerTool.\$anonfun\$check\$1(TypeCheckerTool.scala:46)
	at scala.collection.immutable.List.foldRight(List.scala:352)
	at at.forsyte.apalache.tla.typecheck.TypeCheckerTool.check(TypeCheckerTool.scala:45)
	at at.forsyte.apalache.tla.passes.typecheck.EtcTypeCheckerPassImpl.execute(EtcTypeCheckerPassImpl.scala:54)
	at at.forsyte.apalache.infra.passes.PassChainExecutor\$.exec(PassChainExecutor.scala:64)
	at at.forsyte.apalache.infra.passes.PassChainExecutor\$.\$anonfun\$runPassOnModule\$3(PassChainExecutor.scala:53)
	at scala.util.Either.flatMap(Either.scala:352)
	at at.forsyte.apalache.infra.passes.PassChainExecutor\$.\$anonfun\$runPassOnModule\$1(PassChainExecutor.scala:51)
	at scala.collection.LinearSeqOps.foldLeft(LinearSeq.scala:183)
	at scala.collection.LinearSeqOps.foldLeft\$(LinearSeq.scala:179)
	at scala.collection.immutable.List.foldLeft(List.scala:79)
	at at.forsyte.apalache.infra.passes.PassChainExecutor\$.runOnPasses(PassChainExecutor.scala:44)
	at at.forsyte.apalache.infra.passes.PassChainExecutor\$.run(PassChainExecutor.scala:34)
	at at.forsyte.apalache.tla.tooling.opt.TypeCheckCmd.run(TypeCheckCmd.scala:41)
	at at.forsyte.apalache.tla.Tool\$.runCommand(Tool.scala:138)
	at at.forsyte.apalache.tla.Tool\$.run(Tool.scala:118)
	at at.forsyte.apalache.tla.Tool\$.main(Tool.scala:40)
	at at.forsyte.apalache.tla.Tool.main(Tool.scala)
```
</details>

## System information

- Apalache version: `0.44.2 build v0.44.2`
- OS: `Linux`
- JDK version: `17.0.9`

## Triage checklist (for maintainers)

- [ ] Reproduce the bug on the main development branch.
- [ ] Add the issue to the apalache GitHub project.
- [ ] If the bug is high impact, ensure someone available is assigned to fix it.

**Comment by shonfeder** [comment]
Thank you for the report! Any chance you could provide a minimal reproduction? That would help expedite debugging.

**Comment by shonfeder** [comment]
Nevermind! I can reproduce this on

https://github.com/tlaplus/Examples/blob/adccef97931d44120a64ba88054b5ab085f8c50d/specifications/lamport_mutex/WellFoundedInduction.tla#L151

with


```
$  apalache-mc typecheck WellFoundedInduction.tla 
```

The type checker is chocking on the second formula of

```
WFInductiveDefines(f, S, Def(_,_)) ==
     f = [x \in S |-> Def(f, x)]
                      
                    
WFInductiveUnique(S, Def(_,_)) ==
  \A g, h : /\ WFInductiveDefines(g, S, Def)
            /\ WFInductiveDefines(h, S, Def)
            => (g = h)
```

**Comment by nano-o** [comment]
Yes, sorry I should have dug a little deeper here. A simpler example is to run `apalach-mc typecheck WellFoundedInduction.tla` ([WellFoundedInduction.tla](https://github.com/nano-o/TLA--Examples/blob/ApaVoting_with_cfg/specifications/Paxos/WellFoundedInduction.tla)). Are you able to reproduce that?

**Comment by shonfeder** [comment]
No worries! I found it quickly. This is a great report as is, I was just being greedy in asking for more :D

**Comment by shonfeder** [comment]
Got it, the minimal repro is

```tla
---------------------------- MODULE test --------------------------
Foo == \A g: TRUE
=================================================================
```

And the diagnosis:

The crash is an error in the type checker, as the offending case says it should not be reachable:

https://github.com/informalsystems/apalache/blob/99fb4d288aff9a7b19079366e9c09b033058f8e4/tla-typechecker/src/main/scala/at/forsyte/apalache/tla/typecheck/etc/ToEtcExpr.scala#L894-L896

But the root cause of the impact on your work is the fact that we do not support unbounded quantification. See https://apalache.informal.systems/docs/lang/logic.html#unbounded-universal-quantifier. So, e.g., if we add a bound to the quantified `g in `Foo == \A g \in S: TRUE`, we don't hit this problem.

`Voting.tla` is picking up its dependency on this formula (in the `WellFoundedInduction` module) only via the instantiation of `Consensus` in

https://github.com/nano-o/TLA--Examples/blob/43c2814b56af9a3e5d3ee7f6663a72be94f9ca48/specifications/Paxos/Voting.tla#L187-L193

To unblock your work, aiming to reuse as much of `Voting.tla` as possible, could you move that instantiation and the final theorem that depends on it into an extension of `Voting.tla`?

**Comment by shonfeder** [comment]
@nano-o Sorry there isn't an easy fix to allow you to use `Voting.tla` as is, but hopefully the needed changes could be small enough it would be accepted into the Examples?

**Comment by nano-o** [comment]
It looks to me like the problematic definitions are only used in TLAPS proofs. So could Apalache just ignore them?

**Comment by nano-o** [comment]
Ah sorry that's what you are suggesting in Item 2 above.

**Comment by shalashaska117** [comment]
I took a look at this and opened #3383 implementing option (c) from your triage: `ToEtcExpr` was missing cases for `forallUnbounded`/`existsUnbounded`, so `\A x: P` / `\E x: P` fell through to the unreachable branch. The PR type-checks them like unbounded `CHOOSE`, and the model checker now reports a proper source-located `unsupported expression` error instead of crashing. Happy to adjust the approach if you'd prefer (a) or (b) instead.
