### ISSUE TITLE
[BUG] at.forsyte.apalache.tla.pp.OverridingError

### ISSUE THREAD

**Issue by lemmy** [informalsystems/apalache#285]
```bash
markus@avocado:~/src/TLA/_specs/models/mine/PageQueue/PageQueue.toolbox/w19(master)$ /opt/apalache/bin/apalache-mc --cinit=ConstInit --init=Init --next=Next --length=50 check /home/markus/src/TLA/_specs/models/mine/PageQueue/PageQueue.toolbox/w19/MC.tla
# Tool home: /opt/apalache
# Package:   /opt/apalache/mod-distribution/target/apalache-pkg-0.7.2-RELEASE-full.jar
# JVM args: -Xmx4096m -Djava.library.path=/usr/lib/x86_64-linux-gnu/jni/  -DTLA-Library=
#
# APALACHE version 0.7.2-RELEASE build v0.7.1-5-g5b85083
#
# WARNING: This tool is in the experimental stage.
#          Please report bugs at: [https://github.com/informalsystems/apalache/issues]

Checker options: filename=/home/markus/src/TLA/_specs/models/mine/PageQueue/PageQueue.toolbox/w19/MC.tla, init=Init, next=Next, inv= I@16:58:02.799
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.inject.internal.cglib.core.$ReflectUtils$1 (file:/opt/apalache/mod-distribution/target/apalache-pkg-0.7.2-RELEASE-full.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of com.google.inject.internal.cglib.core.$ReflectUtils$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
PASS #0: SanyParser                                               I@16:58:03.180
Parsing file /home/markus/src/TLA/_specs/models/mine/PageQueue/PageQueue.toolbox/w19/MC.tla
Parsing file /home/markus/src/TLA/_specs/models/mine/PageQueue/PageQueue.toolbox/w19/PageQueue.tla
Parsing file /tmp/TLC.tla
Parsing file /tmp/Integers.tla
Parsing file /tmp/Sequences.tla
Parsing file /home/markus/src/TLA/_specs/models/mine/PageQueue/PageQueue.toolbox/w19/SequencesExt.tla
Parsing file /home/markus/src/TLA/_specs/models/mine/PageQueue/PageQueue.toolbox/w19/Functions.tla
Parsing file /tmp/FiniteSets.tla
Parsing file /home/markus/src/TLA/_specs/models/mine/PageQueue/PageQueue.toolbox/w19/TLCExt.tla
Parsing file /tmp/Randomization.tla
Parsing file /tmp/Naturals.tla
Parsing file /home/markus/src/TLA/_specs/models/mine/PageQueue/PageQueue.toolbox/w19/FiniteSetsExt.tla
PASS #1: ConfigurationPass                                        I@16:58:04.181
  > Loading TLC configuration from MC.cfg                         I@16:58:04.182
  > Temporal spec found in MC.cfg, which is not yet supported. Skipping. W@16:58:04.313
  > Replaced CONSTANT Workers                                     I@16:58:04.316
  > Replaced CONSTANT Pages                                       I@16:58:04.317
  > Replaced CONSTANT w10                                         I@16:58:04.317
  > Replaced CONSTANT w11                                         I@16:58:04.317
  > Replaced CONSTANT w12                                         I@16:58:04.317
  > Replaced CONSTANT w13                                         I@16:58:04.317
  > Replaced CONSTANT w14                                         I@16:58:04.317
  > Replaced CONSTANT w15                                         I@16:58:04.318
  > Replaced CONSTANT w16                                         I@16:58:04.318
  > Replaced CONSTANT w17                                         I@16:58:04.318
  > Replaced CONSTANT w18                                         I@16:58:04.318
  > Replaced CONSTANT w19                                         I@16:58:04.318
  > Replaced CONSTANT w1                                          I@16:58:04.318
  > Replaced CONSTANT w2                                          I@16:58:04.318
  > Replaced CONSTANT w3                                          I@16:58:04.318
  > Replaced CONSTANT w4                                          I@16:58:04.318
  > Replaced CONSTANT w5                                          I@16:58:04.318
  > Replaced CONSTANT w6                                          I@16:58:04.318
  > Replaced CONSTANT w7                                          I@16:58:04.318
  > Replaced CONSTANT w8                                          I@16:58:04.318
  > Replaced CONSTANT w9                                          I@16:58:04.318
(Please report an issue at: [https://github.com/informalsystems/apalache/issues],at.forsyte.apalache.tla.pp.OverridingError:   > Replacing operator SetOfRandomElement (1) with an operator OVERRIDE_SetOfRandomElement that has 0 parameters)
<unknown>: unexpected TLA+ expression:   > Replacing operator SetOfRandomElement (1) with an operator OVERRIDE_SetOfRandomElement that has 0 parameters E@16:58:04.435
at.forsyte.apalache.tla.pp.OverridingError:   > Replacing operator SetOfRandomElement (1) with an operator OVERRIDE_SetOfRandomElement that has 0 parameters
	at at.forsyte.apalache.tla.pp.ConstAndDefRewriter.$anonfun$apply$1(ConstAndDefRewriter.scala:44)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
	at scala.collection.immutable.List.foreach(List.scala:378)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:234)
	at scala.collection.immutable.List.map(List.scala:284)
	at at.forsyte.apalache.tla.pp.ConstAndDefRewriter.apply(ConstAndDefRewriter.scala:58)
	at at.forsyte.apalache.tla.pp.passes.ConfigurationPassImpl.tryConfigureFromTlcConfig(ConfigurationPassImpl.scala:133)
	at at.forsyte.apalache.tla.pp.passes.ConfigurationPassImpl.execute(ConfigurationPassImpl.scala:49)
	at at.forsyte.apalache.infra.passes.PassChainExecutor.exec$1(PassChainExecutor.scala:23)
	at at.forsyte.apalache.infra.passes.PassChainExecutor.run(PassChainExecutor.scala:38)
	at at.forsyte.apalache.tla.Tool$.runCheck(Tool.scala:147)
	at at.forsyte.apalache.tla.Tool$.$anonfun$run$2(Tool.scala:81)
	at at.forsyte.apalache.tla.Tool$.$anonfun$run$2$adapted(Tool.scala:81)
	at at.forsyte.apalache.tla.Tool$.handleExceptions(Tool.scala:196)
	at at.forsyte.apalache.tla.Tool$.run(Tool.scala:81)
	at at.forsyte.apalache.tla.Tool$.main(Tool.scala:42)
	at at.forsyte.apalache.tla.Tool.main(Tool.scala)
It took me 0 days  0 hours  0 min  1 sec                          I@16:58:04.436
Total time: 1.698 sec                                             I@16:58:04.436
EXITCODE: ERROR (99)
```

```tla
----------------------------- MODULE PageQueue -----------------------------
EXTENDS Integers, Sequences, SequencesExt, Functions, FiniteSets, TLC, TLCExt,
        Randomization

NatP == Nat \ {0}

Max(S) == CHOOSE s \in S : \A e \in S : s >= e

Reduce(seq, i) == [ idx \in 1..Len(seq) |-> seq[idx][i] ]

Op(o, p) == [ oper |-> o, page |-> p ]

-----------------------------------------------------------------------------

CONSTANT Workers,
         Pages                
                              
ASSUME /\ Workers # {}
       /\ Pages \in NatP


SetOfRandomElement(S) == 
   S 

SetOfInitialDisks == { 1..i : i \in 1..Pages }

w2i == CHOOSE mapping \in RandomSubset(Cardinality(Workers),
                               [ Workers -> 1..Cardinality(Workers) ]): TRUE

ASSUME Cardinality(Workers) < 20
InitializeStats ==
   \A n \in (20..22): TLCSet(n, [ i \in 1..Pages+20 |-> 0 ])

PrintStats == 
     /\ \A n \in 20..22 : PrintT(<<n, TLCGet(n)>>)

IncrementStats(n, i) == 
    TLCDefer(
         TLCSet(n, [ TLCGet(n) EXCEPT ![i] = @ + 1 ]))

-----------------------------------------------------------------------------

fin == CHOOSE fin : fin \notin Nat
vio == CHOOSE vio : vio \notin Nat \cup {fin}
np  == CHOOSE np  : np  \notin Nat \cup {fin,vio}
sus == CHOOSE sus : sus \notin Nat \cup {fin,vio,np}

\* BEGIN TRANSLATION (chksum(pcal) = "7d7ae302" /\ chksum(tla) = "79f27a1")
VARIABLES tail, disk, head, enqHistory, deqHistory, pc

(* define statement *)
TotalWork(h,t) == h > Pages

TypeOK ==
      /\ tail \in (Nat \cup {fin,vio,sus})
      /\ head \in NatP
      /\ disk \subseteq NatP

WSafety ==
         /\ (\A p \in Workers : pc[p] = "Done") =>
            \/ tail = vio
            \/ /\ tail = fin
               /\ disk = {}
               /\ enqHistory = deqHistory

VARIABLES terminated, phaser, condition, tmp, result, t, h

vars == << tail, disk, head, enqHistory, deqHistory, pc, terminated, phaser, 
           condition, tmp, result, t, h >>

ProcSet == {"main"} \cup (Workers)

Init == (* Global variables *)
        /\ tail = 0
        /\ disk \in SetOfInitialDisks
        /\ head = Max(disk)
        /\ enqHistory = 1..Cardinality(disk)
        /\ deqHistory = {}
        (* Process ProcName *)
        /\ terminated = FALSE
        /\ phaser = 0
        /\ condition = FALSE
        /\ tmp = tail
        (* Process worker *)
        /\ result = [self \in Workers |-> FALSE]
        /\ t = [self \in Workers |-> 0]
        /\ h = [self \in Workers |-> np]
        /\ pc = [self \in ProcSet |-> CASE self = "main" -> "m0"
                                        [] self \in Workers -> "deq"]

m0 == /\ pc["main"] = "m0"
      /\ IF ~terminated
            THEN /\ pc' = [pc EXCEPT !["main"] = "m1"]
            ELSE /\ pc' = [pc EXCEPT !["main"] = "Done"]
      /\ UNCHANGED << tail, disk, head, enqHistory, deqHistory, terminated, 
                      phaser, condition, tmp, result, t, h >>

m1 == /\ pc["main"] = "m1"
      /\ tail # tmp
      /\ phaser = 0
      /\ condition' = FALSE
      /\ tmp' = tail
      /\ IF tmp' = vio \/ tmp' = fin
            THEN /\ tail' = tmp'
                 /\ pc' = [pc EXCEPT !["main"] = "Done"]
            ELSE /\ pc' = [pc EXCEPT !["main"] = "m2"]
                 /\ tail' = tail
      /\ UNCHANGED << disk, head, enqHistory, deqHistory, terminated, phaser, 
                      result, t, h >>

m2 == /\ pc["main"] = "m2"
      /\ IF tail = tmp
            THEN /\ tail' = sus
                 /\ pc' = [pc EXCEPT !["main"] = "m3"]
            ELSE /\ pc' = [pc EXCEPT !["main"] = "m0"]
                 /\ tail' = tail
      /\ UNCHANGED << disk, head, enqHistory, deqHistory, terminated, phaser, 
                      condition, tmp, result, t, h >>

m3 == /\ pc["main"] = "m3"
      /\ phaser = Cardinality(Workers) \/ terminated
      /\ IF terminated
            THEN /\ condition' = TRUE
                 /\ pc' = [pc EXCEPT !["main"] = "Done"]
            ELSE /\ pc' = [pc EXCEPT !["main"] = "m4"]
                 /\ UNCHANGED condition
      /\ UNCHANGED << tail, disk, head, enqHistory, deqHistory, terminated, 
                      phaser, tmp, result, t, h >>

m4 == /\ pc["main"] = "m4"
      /\ TRUE
      /\ tail' = tmp
      /\ pc' = [pc EXCEPT !["main"] = "m5"]
      /\ UNCHANGED << disk, head, enqHistory, deqHistory, terminated, phaser, 
                      condition, tmp, result, t, h >>

m5 == /\ pc["main"] = "m5"
      /\ condition' = TRUE
      /\ pc' = [pc EXCEPT !["main"] = "m0"]
      /\ UNCHANGED << tail, disk, head, enqHistory, deqHistory, terminated, 
                      phaser, tmp, result, t, h >>

ProcName == m0 \/ m1 \/ m2 \/ m3 \/ m4 \/ m5

deq(self) == /\ pc[self] = "deq"
             /\ t' = [t EXCEPT ![self] = tail]
             /\ IF t'[self] = vio
                   THEN /\ pc' = [pc EXCEPT ![self] = "Done"]
                   ELSE /\ IF t'[self] = fin
                              THEN /\ Assert(disk = {}, 
                                             "Failure of assertion at line 304, column 20.")
                                   /\ pc' = [pc EXCEPT ![self] = "Done"]
                              ELSE /\ IF t'[self] = sus
                                         THEN /\ pc' = [pc EXCEPT ![self] = "suspendedA"]
                                         ELSE /\ pc' = [pc EXCEPT ![self] = "casA"]
             /\ UNCHANGED << tail, disk, head, enqHistory, deqHistory, 
                             terminated, phaser, condition, tmp, result, h >>

suspendedA(self) == /\ pc[self] = "suspendedA"
                    /\ phaser' = phaser + 1
                    /\ pc' = [pc EXCEPT ![self] = "suspendedB"]
                    /\ UNCHANGED << tail, disk, head, enqHistory, deqHistory, 
                                    terminated, condition, tmp, result, t, h >>

suspendedB(self) == /\ pc[self] = "suspendedB"
                    /\ condition \/ terminated
                    /\ phaser' = phaser - 1
                    /\ pc' = [pc EXCEPT ![self] = "deq"]
                    /\ UNCHANGED << tail, disk, head, enqHistory, deqHistory, 
                                    terminated, condition, tmp, result, t, h >>

casA(self) == /\ pc[self] = "casA"
              /\ IF tail = t[self]
                    THEN /\ tail' = t[self] + 1
                         /\ result' = [result EXCEPT ![self] = TRUE]
                    ELSE /\ result' = [result EXCEPT ![self] = FALSE]
                         /\ tail' = tail
              /\ IF result'[self]
                    THEN /\ t' = [t EXCEPT ![self] = t[self] + 1]
                         /\ pc' = [pc EXCEPT ![self] = "wt"]
                    ELSE /\ pc' = [pc EXCEPT ![self] = "deq"]
                         /\ t' = t
              /\ UNCHANGED << disk, head, enqHistory, deqHistory, terminated, 
                              phaser, condition, tmp, h >>

wt(self) == /\ pc[self] = "wt"
            /\ IF t[self] \notin disk
                  THEN /\ pc' = [pc EXCEPT ![self] = "wt1"]
                  ELSE /\ pc' = [pc EXCEPT ![self] = "rd"]
            /\ UNCHANGED << tail, disk, head, enqHistory, deqHistory, 
                            terminated, phaser, condition, tmp, result, t, h >>

wt1(self) == /\ pc[self] = "wt1"
             /\ IF tail = vio
                   THEN /\ pc' = [pc EXCEPT ![self] = "Done"]
                        /\ UNCHANGED << disk, enqHistory, h >>
                   ELSE /\ IF tail = fin
                              THEN /\ Assert(h[self] = np /\ disk = {}, 
                                             "Failure of assertion at line 341, column 24.")
                                   /\ pc' = [pc EXCEPT ![self] = "Done"]
                                   /\ UNCHANGED << disk, enqHistory, h >>
                              ELSE /\ IF tail = sus
                                         THEN /\ pc' = [pc EXCEPT ![self] = "suspendedA1"]
                                              /\ UNCHANGED << disk, enqHistory, 
                                                              h >>
                                         ELSE /\ IF head = tail - Cardinality(Workers)
                                                    THEN /\ Assert(h[self] = np, 
                                                                   "Failure of assertion at line 362, column 24.")
                                                         /\ pc' = [pc EXCEPT ![self] = "casB"]
                                                         /\ UNCHANGED << disk, 
                                                                         enqHistory, 
                                                                         h >>
                                                    ELSE /\ IF h[self] # np /\ h[self] = t[self]
                                                               THEN /\ IncrementStats(20, h[self])
                                                                    /\ disk' = (disk \cup {h[self]})
                                                                    /\ Assert(h[self] \notin enqHistory, 
                                                                              "Failure of assertion at line 198, column 11 of macro called at line 379, column 25.")
                                                                    /\ enqHistory' = (enqHistory \cup {h[self]})
                                                                    /\ h' = [h EXCEPT ![self] = np]
                                                                    /\ pc' = [pc EXCEPT ![self] = "wt"]
                                                               ELSE /\ IF h[self] # np /\ h[self] > t[self]
                                                                          THEN /\ IncrementStats(21, h[self])
                                                                               /\ disk' = (disk \cup {h[self]})
                                                                               /\ Assert(h[self] \notin enqHistory, 
                                                                                         "Failure of assertion at line 198, column 11 of macro called at line 390, column 25.")
                                                                               /\ enqHistory' = (enqHistory \cup {h[self]})
                                                                               /\ h' = [h EXCEPT ![self] = np]
                                                                               /\ pc' = [pc EXCEPT ![self] = "wt"]
                                                                          ELSE /\ IF h[self] # np /\ h[self] < t[self] /\ head <= tail
                                                                                     THEN /\ IncrementStats(22, h[self])
                                                                                          /\ disk' = (disk \cup {h[self]})
                                                                                          /\ Assert(h[self] \notin enqHistory, 
                                                                                                    "Failure of assertion at line 198, column 11 of macro called at line 428, column 25.")
                                                                                          /\ enqHistory' = (enqHistory \cup {h[self]})
                                                                                          /\ h' = [h EXCEPT ![self] = np]
                                                                                          /\ pc' = [pc EXCEPT ![self] = "wt"]
                                                                                     ELSE /\ TRUE
                                                                                          /\ pc' = [pc EXCEPT ![self] = "wt"]
                                                                                          /\ UNCHANGED << disk, 
                                                                                                          enqHistory, 
                                                                                                          h >>
             /\ UNCHANGED << tail, head, deqHistory, terminated, phaser, 
                             condition, tmp, result, t >>

suspendedA1(self) == /\ pc[self] = "suspendedA1"
                     /\ phaser' = phaser + 1
                     /\ pc' = [pc EXCEPT ![self] = "suspendedB1"]
                     /\ UNCHANGED << tail, disk, head, enqHistory, deqHistory, 
                                     terminated, condition, tmp, result, t, h >>

suspendedB1(self) == /\ pc[self] = "suspendedB1"
                     /\ condition \/ terminated
                     /\ phaser' = phaser - 1
                     /\ pc' = [pc EXCEPT ![self] = "wt"]
                     /\ UNCHANGED << tail, disk, head, enqHistory, deqHistory, 
                                     terminated, condition, tmp, result, t, h >>

casB(self) == /\ pc[self] = "casB"
              /\ IF tail = t[self]
                    THEN /\ tail' = fin
                         /\ result' = [result EXCEPT ![self] = TRUE]
                    ELSE /\ result' = [result EXCEPT ![self] = FALSE]
                         /\ tail' = tail
              /\ IF result'[self]
                    THEN /\ Assert(disk = {}, 
                                   "Failure of assertion at line 365, column 33.")
                         /\ terminated' = TRUE
                         /\ pc' = [pc EXCEPT ![self] = "Done"]
                    ELSE /\ pc' = [pc EXCEPT ![self] = "wt"]
                         /\ UNCHANGED terminated
              /\ UNCHANGED << disk, head, enqHistory, deqHistory, phaser, 
                              condition, tmp, t, h >>

rd(self) == /\ pc[self] = "rd"
            /\ Assert(t[self] \in disk, 
                      "Failure of assertion at line 439, column 18.")
            /\ disk' = disk \ {t[self]}
            /\ Assert(t[self] \notin deqHistory, 
                      "Failure of assertion at line 191, column 11 of macro called at line 440, column 18.")
            /\ deqHistory' = (deqHistory \cup {t[self]})
            /\ pc' = [pc EXCEPT ![self] = "exp"]
            /\ UNCHANGED << tail, head, enqHistory, terminated, phaser, 
                            condition, tmp, result, t, h >>

exp(self) == /\ pc[self] = "exp"
             /\ IF TotalWork(head, tail)
                   THEN /\ pc' = [pc EXCEPT ![self] = "deq"]
                   ELSE /\ pc' = [pc EXCEPT ![self] = "enq"]
             /\ UNCHANGED << tail, disk, head, enqHistory, deqHistory, 
                             terminated, phaser, condition, tmp, result, t, h >>

enq(self) == /\ pc[self] = "enq"
             /\ IF h[self] = np
                   THEN /\ \E i \in SetOfRandomElement(1..50):
                             \/ /\ i \in 1..1
                                /\ pc' = [pc EXCEPT ![self] = "violation"]
                             \/ /\ i \in 2..50
                                /\ pc' = [pc EXCEPT ![self] = "claim"]
                   ELSE /\ IF h[self] # np
                              THEN /\ \E i \in SetOfRandomElement(1..50):
                                        \/ /\ i \in 1..1
                                           /\ pc' = [pc EXCEPT ![self] = "violation"]
                                        \/ /\ i \in 2..2
                                           /\ pc' = [pc EXCEPT ![self] = "deq"]
                                        \/ /\ i \in 3..50
                                           /\ pc' = [pc EXCEPT ![self] = "wrt"]
                              ELSE /\ pc' = [pc EXCEPT ![self] = "claim"]
             /\ UNCHANGED << tail, disk, head, enqHistory, deqHistory, 
                             terminated, phaser, condition, tmp, result, t, h >>

claim(self) == /\ pc[self] = "claim"
               /\ Assert(h[self] = np, 
                         "Failure of assertion at line 506, column 20.")
               /\ head' = head + 1
               /\ h' = [h EXCEPT ![self] = head']
               /\ \E i \in SetOfRandomElement(2..3):
                    \/ /\ i \in 2..2
                       /\ pc' = [pc EXCEPT ![self] = "deq"]
                    \/ /\ i \in 3..3
                       /\ pc' = [pc EXCEPT ![self] = "wrt"]
               /\ UNCHANGED << tail, disk, enqHistory, deqHistory, terminated, 
                               phaser, condition, tmp, result, t >>

wrt(self) == /\ pc[self] = "wrt"
             /\ disk' = (disk \cup {h[self]})
             /\ Assert(h[self] \notin enqHistory, 
                       "Failure of assertion at line 198, column 11 of macro called at line 530, column 18.")
             /\ enqHistory' = (enqHistory \cup {h[self]})
             /\ h' = [h EXCEPT ![self] = np]
             /\ \E i \in SetOfRandomElement(2..3):
                  \/ /\ i \in 2..2
                     /\ pc' = [pc EXCEPT ![self] = "deq"]
                  \/ /\ i \in 3..3
                     /\ pc' = [pc EXCEPT ![self] = "exp"]
             /\ UNCHANGED << tail, head, deqHistory, terminated, phaser, 
                             condition, tmp, result, t >>

violation(self) == /\ pc[self] = "violation"
                   /\ IF tail = t[self]
                         THEN /\ tail' = vio
                              /\ result' = [result EXCEPT ![self] = TRUE]
                         ELSE /\ result' = [result EXCEPT ![self] = FALSE]
                              /\ tail' = tail
                   /\ IF result'[self]
                         THEN /\ terminated' = TRUE
                              /\ pc' = [pc EXCEPT ![self] = "Done"]
                         ELSE /\ pc' = [pc EXCEPT ![self] = "retry"]
                              /\ UNCHANGED terminated
                   /\ UNCHANGED << disk, head, enqHistory, deqHistory, phaser, 
                                   condition, tmp, t, h >>

retry(self) == /\ pc[self] = "retry"
               /\ t' = [t EXCEPT ![self] = tail]
               /\ pc' = [pc EXCEPT ![self] = "violation"]
               /\ UNCHANGED << tail, disk, head, enqHistory, deqHistory, 
                               terminated, phaser, condition, tmp, result, h >>

worker(self) == deq(self) \/ suspendedA(self) \/ suspendedB(self)
                   \/ casA(self) \/ wt(self) \/ wt1(self)
                   \/ suspendedA1(self) \/ suspendedB1(self) \/ casB(self)
                   \/ rd(self) \/ exp(self) \/ enq(self) \/ claim(self)
                   \/ wrt(self) \/ violation(self) \/ retry(self)

(* Allow infinite stuttering to prevent deadlock on termination. *)
Terminating == /\ \A self \in ProcSet: pc[self] = "Done"
               /\ UNCHANGED vars

Next == ProcName
           \/ (\E self \in Workers: worker(self))
           \/ Terminating

Spec == /\ Init /\ [][Next]_vars
        /\ WF_vars(ProcName)
        /\ \A self \in Workers : WF_vars(worker(self))

Termination == <>(\A self \in ProcSet: pc[self] = "Done")
=============================================================================
```

```tla
---- MODULE MC ----
EXTENDS PageQueue, TLC

\* MV CONSTANT declarations@modelParameterConstants
CONSTANTS
w1, w2, w3, w4, w5, w6, w7, w8, w9, w10, w11, w12, w13, w14, w15, w16, w17, w18, w19
----

\* MV CONSTANT definitions Workers
const_1602804924497168000 == 
{w1, w2, w3, w4, w5, w6, w7, w8, w9, w10, w11, w12, w13, w14, w15, w16, w17, w18, w19}
----

\* CONSTANT definitions @modelParameterConstants:1Pages
const_1602804924498169000 == 
3
----

\* CONSTANT definition @modelParameterDefinitions:3
def_ov_1602804924498173000(n, i) ==
TRUE
----
\* CONSTANT definition @modelParameterDefinitions:4
def_ov_1602804924498174000(S) ==
{1,2,3}
----
\* CONSTANT definition @modelParameterDefinitions:6
def_ov_1602804924498176000 ==
NoSuspension
----
\* ACTION_CONSTRAINT definition @modelParameterActionConstraint:0
action_constr_1602804924498177000 ==
~Terminating
----
=============================================================================
\* Modification History
\* Created Thu Oct 15 16:35:24 PDT 2020 by markus
markus@avocado:~/src/TLA/_specs/models/mine/PageQueue/PageQueue.toolbox/w19(master)$ cat MC.cfg
\* MV CONSTANT declarations
CONSTANTS
w1 = w1
w2 = w2
w3 = w3
w4 = w4
w5 = w5
w6 = w6
w7 = w7
w8 = w8
w9 = w9
w10 = w10
w11 = w11
w12 = w12
w13 = w13
w14 = w14
w15 = w15
w16 = w16
w17 = w17
w18 = w18
w19 = w19
\* MV CONSTANT definitions
CONSTANT
Workers <- const_1602804924497168000
\* CONSTANT definitions
CONSTANT
Pages <- const_1602804924498169000
\* CONSTANT definition
CONSTANT
fin = fin
vio = vio
np = np
IncrementStats <- def_ov_1602804924498173000
SetOfRandomElement <- def_ov_1602804924498174000
sus = sus
ProcName <- def_ov_1602804924498176000
\* ACTION_CONSTRAINT definition
ACTION_CONSTRAINT
action_constr_1602804924498177000
\* SPECIFICATION definition
SPECIFICATION
Spec
```

**Comment by konnov** [comment]
From what I can see, there is something going about LAMBDAs, since all have the same name LAMBDA. I will have a closer look later today.

**Comment by konnov** [comment]
After all the bugfixing, the model checker complains about the unsupported expression:

```tla
PageQueue.tla:88:17-89:69: Input error (see the manual): CASE without other, see: [docs/preprocessing.md]
```

Basically, we only know how to translate `CASE` with the default `OTHER` arm.

Let me know whether you like to continue with this issue.

**Comment by lemmy** [comment]
FWIW: A `CASE` without `OTHER` is what the PlusCal translator generates for an algorithm with two or more processes:

```tla
----- Foo -----
(***************************************************************************
--algorithm AlgorithmName {
  
  process (P = "A") {
      p: skip;
  }

  process (Q = "B") {
       q: skip;
  }
}
***************************************************************************)
\* BEGIN TRANSLATION (chksum(pcal) = "35d81b1b" /\ chksum(tla) = "6984dff1")
VARIABLE pc

vars == << pc >>

ProcSet == {"A"} \cup {"B"}

Init == /\ pc = [self \in ProcSet |-> CASE self = "A" -> "p"
                                        [] self = "B" -> "q"]
...

\* END TRANSLATION 
```

**Comment by konnov** [comment]
In your example, it is basically a partial function. We could probably treat it similar to function application. However, there is another case, in which `CASE` should be treated as a disjunction.

**Comment by konnov** [comment]
Once we have the new type checker #350 in place, we should come to this question. When preprocessing has access to types, it should be quite easy to introduce the default arm for `OTHER`.
