### ISSUE TITLE
[BUG] IllegalArgumentException: requirement failed: unexpected arity 5 in rec-fun-def

### ISSUE THREAD

**Issue by lemmy** [informalsystems/apalache#297]
```bash
markus@avocado:~/src/TLA/_specs/models/realworld/AsyncGameOfLife/AsyncGameOfLifeDistributed.toolbox/BlinkerN3(master)$ /opt/apalache/bin/apalache-mc check MC
# Tool home: /opt/apalache
# Package:   /opt/apalache/mod-distribution/target/apalache-pkg-0.7.2-RELEASE-full.jar
# JVM args: -Xmx4096m -Djava.library.path=/usr/lib/x86_64-linux-gnu/jni/  -DTLA-Library=
#
# APALACHE version 0.7.2-RELEASE build v0.7.1-5-g5b85083
#
# WARNING: This tool is in the experimental stage.
#          Please report bugs at: [https://github.com/informalsystems/apalache/issues]

Checker options: filename=MC, init=, next=, inv=                  I@09:57:35.536
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.inject.internal.cglib.core.$ReflectUtils$1 (file:/opt/apalache/mod-distribution/target/apalache-pkg-0.7.2-RELEASE-full.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of com.google.inject.internal.cglib.core.$ReflectUtils$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
PASS #0: SanyParser                                               I@09:57:35.899
Parsing file /home/markus/src/TLA/_specs/models/realworld/AsyncGameOfLife/AsyncGameOfLifeDistributed.toolbox/BlinkerN3/MC.tla
Parsing file /home/markus/src/TLA/_specs/models/realworld/AsyncGameOfLife/AsyncGameOfLifeDistributed.toolbox/BlinkerN3/AsyncGameOfLifeDistributed.tla
Parsing file /tmp/TLC.tla
Parsing file /tmp/Integers.tla
Parsing file /tmp/FiniteSets.tla
Parsing file /tmp/Sequences.tla
Parsing file /tmp/Naturals.tla
Parsing file /home/markus/src/TLA/_specs/models/realworld/AsyncGameOfLife/AsyncGameOfLifeDistributed.toolbox/BlinkerN3/Messaging.tla
Parsing file /home/markus/src/TLA/_specs/models/realworld/AsyncGameOfLife/AsyncGameOfLifeDistributed.toolbox/BlinkerN3/AsyncGameOfLife.tla
(Please report an issue at: [https://github.com/informalsystems/apalache/issues],java.lang.IllegalArgumentException: requirement failed: unexpected arity 5 in rec-fun-def applied to IF (msgs = {}) THEN intf ELSE LET m ≜ CHOOSE m ∈ msgs : TRUE IN doSend[<<[intf EXCEPT ![<<m()[1]>>] = LET Append(s, e) ≜ s ∘ <<e>> IN Append(intf[m()[1]], m()[2])], msgs ∖ {m()}>>], intf, [Processes → LET Seq(S) ≜ UNION ({[LET ..(a, b) ≜ {a, b} IN ..(1, n) → S] : n ∈ LET Nat ≜ {} IN Nat()}) IN Seq(Message)], msgs, SUBSET ({<<proc, msg>> : proc ∈ Processes, msg ∈ Message}))
Unhandled exception                                               E@09:57:36.219
java.lang.IllegalArgumentException: requirement failed: unexpected arity 5 in rec-fun-def applied to IF (msgs = {}) THEN intf ELSE LET m ≜ CHOOSE m ∈ msgs : TRUE IN doSend[<<[intf EXCEPT ![<<m()[1]>>] = LET Append(s, e) ≜ s ∘ <<e>> IN Append(intf[m()[1]], m()[2])], msgs ∖ {m()}>>], intf, [Processes → LET Seq(S) ≜ UNION ({[LET ..(a, b) ≜ {a, b} IN ..(1, n) → S] : n ∈ LET Nat ≜ {} IN Nat()}) IN Seq(Message)], msgs, SUBSET ({<<proc, msg>> : proc ∈ Processes, msg ∈ Message})
	at scala.Predef$.require(Predef.scala:277)
	at at.forsyte.apalache.tla.lir.OperEx.<init>(package.scala:146)
	at at.forsyte.apalache.tla.imp.OpApplTranslator.mkBoundCtorBuiltin(OpApplTranslator.scala:365)
	at at.forsyte.apalache.tla.imp.OpApplTranslator.translateBuiltin(OpApplTranslator.scala:219)
	at at.forsyte.apalache.tla.imp.OpApplTranslator.translate(OpApplTranslator.scala:45)
	at at.forsyte.apalache.tla.imp.ExprOrOpArgNodeTranslator.translate(ExprOrOpArgNodeTranslator.scala:33)
	at at.forsyte.apalache.tla.imp.OpDefTranslator.translate(OpDefTranslator.scala:26)
	at at.forsyte.apalache.tla.imp.ModuleTranslator.$anonfun$translate$4(ModuleTranslator.scala:56)
	at at.forsyte.apalache.tla.imp.ModuleTranslator.$anonfun$translate$4$adapted(ModuleTranslator.scala:49)
	at scala.collection.immutable.List.foreach(List.scala:378)
	at at.forsyte.apalache.tla.imp.ModuleTranslator.translate(ModuleTranslator.scala:49)
	at at.forsyte.apalache.tla.imp.SanyImporter.$anonfun$loadFromFile$1(SanyImporter.scala:39)
	at scala.collection.mutable.ArrayOps$ofRef.foldLeft(ArrayOps.scala:193)
	at at.forsyte.apalache.tla.imp.SanyImporter.loadFromFile(SanyImporter.scala:38)
	at at.forsyte.apalache.tla.imp.passes.SanyParserPassImpl.execute(SanyParserPassImpl.scala:54)
	at at.forsyte.apalache.infra.passes.PassChainExecutor.exec$1(PassChainExecutor.scala:23)
	at at.forsyte.apalache.infra.passes.PassChainExecutor.run(PassChainExecutor.scala:38)
	at at.forsyte.apalache.tla.Tool$.runCheck(Tool.scala:147)
	at at.forsyte.apalache.tla.Tool$.$anonfun$run$2(Tool.scala:81)
	at at.forsyte.apalache.tla.Tool$.$anonfun$run$2$adapted(Tool.scala:81)
	at at.forsyte.apalache.tla.Tool$.handleExceptions(Tool.scala:196)
	at at.forsyte.apalache.tla.Tool$.run(Tool.scala:81)
	at at.forsyte.apalache.tla.Tool$.main(Tool.scala:42)
	at at.forsyte.apalache.tla.Tool.main(Tool.scala)
It took me 0 days  0 hours  0 min  0 sec                          I@09:57:36.220
Total time: 0.741 sec                                             I@09:57:36.220
EXITCODE: ERROR (99)
```

```tla
--------------------- MODULE AsyncGameOfLifeDistributed ---------------------
EXTENDS Integers,
        FiniteSets

CONSTANT N \* Size of the *square* grid.
ASSUME N \in Nat /\ N > 1

null == CHOOSE x : x \notin Nat

R == 
  {0,1,2}


Pos ==
  {<<x, y>> : x, y \in 1..N}

nbhd(v) ==
  LET moore == {x \in {-1, 0, 1} \X {-1, 0, 1} : x /= <<0, 0>>}
      points == {<<v[1] + m[1], v[2] + m[2]>> : m \in moore}
  IN { p \in points : /\ p[1] # 0 /\ p[2] # 0  
                      /\ p[1]<= N /\ p[2]<= N }

CONSTANT P  \* Some initial pattern (blinker, glider, block, ...).
ASSUME P \in [Pos -> (BOOLEAN \X BOOLEAN \X R)]

-------------------------------------------------------------------------------

VARIABLES grid, msgs, mi
vars == <<grid, msgs, mi>>

\* Network related (type of messages, payload, ...).
Message == [ src: Pos, state: (BOOLEAN \X BOOLEAN \X R) ]
Network == INSTANCE Messaging WITH Processes <- Pos

-------------------------------------------------------------------------------

TypeOK ==
  /\ grid \in [Pos -> (BOOLEAN \X BOOLEAN \X R)]
  /\ \A pos \in Pos : 
              /\ DOMAIN msgs[pos] = nbhd(pos)
              /\ \A n \in nbhd(pos):
                   msgs[pos][n] \in ((BOOLEAN \X BOOLEAN \X R) \cup {null})
  \* Variable "mi" is not ours but the Network's responsibility.

-------------------------------------------------------------------------------

Init ==
    /\ grid = P
    /\ grid \in [ Pos -> (BOOLEAN \X BOOLEAN \X R) ]
    /\ msgs = [ pos \in Pos |->
                    [ v \in nbhd(pos) |-> <<grid[v][1], grid[v][2], grid[v][3]>> ] ]
    /\ Network!Init

-------------------------------------------------------------------------------

Deliver(p, m) ==
   \/ /\ m.src \in nbhd(p)
      /\ msgs' = [ msgs EXCEPT ![p][m.src] = m.state ]
      /\ UNCHANGED <<grid>>
   \/ /\ m.src \notin nbhd(p)
      /\ UNCHANGED <<msgs, grid>>    

-------------------------------------------------------------------------------

ready(r, Messages) ==
  /\ \A w \in DOMAIN Messages: IF Messages[w] = null
                               THEN FALSE 
                               ELSE Messages[w][3] # (r + 2) % 3 \* (0 :> 2 @@ 1 :> 0 @@ 2 :> 1)

delta(b, liveNbgrs) ==
  \/  (b /\ Cardinality(liveNbgrs) \in {2, 3})
  \/ (~b /\ Cardinality(liveNbgrs) = 3)

qPP(qw, qwP, rw) == 
  CASE rw = 0 -> qw
    [] rw = 1 -> qwP

-------------------------------------------------------------------------------

Next == 
  /\ \E v \in Pos: \/ LET q  == grid[v][1]
                          qP == grid[v][2]
                          r  == grid[v][3]
                      IN
                         /\ ready(r, msgs[v])
                         /\ \/ /\ r = 0
                               /\ grid' = [ grid EXCEPT ![v] = <<delta(q, 
                                    {m \in DOMAIN msgs[v]: qPP(msgs[v][m][1], msgs[v][m][2], msgs[v][m][3])}),
                                      q, 1>> ]    
                            \/ /\ r \in {1,2}
                               /\ grid' = [ grid EXCEPT ![v] = <<q, qP, (r + 1) % 3>> ]
                         /\ msgs' = [ pos \in Pos |-> 
                                       IF pos = v
                                       THEN [ n \in DOMAIN msgs[v] |-> null ]
                                       ELSE msgs[pos] ]
                         /\ Network!Send(
                                {<<w, [ src |-> v, state |-> <<grid[v][1]', grid[v][2]', grid[v][3]'>> ]>> : w \in nbhd(v) })
                   \/ Network!Receive(v, Deliver)

Spec == Init /\ [][Next]_vars
====
```

```tla
------------------------ MODULE Messaging ------------------------
\* This module specifies a reliable FIFO point-to-point messaging
\* interface between a set of processes

LOCAL INSTANCE Naturals
LOCAL INSTANCE Sequences
CONSTANT Processes, Message
VARIABLE mi

\*++:SPEC

\* mi contains the state of the messaging interface.
\* It is a map of processes to queues of undelivered messages
LOCAL TypeInvariant == mi \in [Processes -> Seq(Message)]

LOCAL InitialState(procs) == [ p \in procs |-> <<>> ]

\* Initially no messages are undelivered
Init == mi = InitialState(Processes)

\* Function takes intf, the state of the messaging interface, and msgs, a
\* set of << destination, message >> pairs, and updates the state by adding
\* the message to the right (destination) queue of undelivered messages.
LOCAL doSend[intf \in [Processes -> Seq(Message)],
             msgs \in SUBSET 
                 {<<proc, msg>> : proc \in Processes, msg \in Message}] ==
    IF msgs = {} THEN intf
    ELSE
        LET m == CHOOSE m \in msgs : TRUE
        IN doSend[[intf EXCEPT ![m[1]] = Append(@, m[2])], msgs \ {m}]

\* Helper operator for Send()
LOCAL SendAll(intf, msgs) == doSend[intf, msgs]

\* msgs is a set of << destination, payload >> pairs.  The intention
\* is to deliver each payload to the given destination process.
Send(msgs) == mi' = SendAll(mi, msgs)

\* Helper operators for Receive()
LOCAL WaitForMessage(intf, p)   == intf[p] /= <<>>
LOCAL NextMessage(intf, p)      == Head(intf[p])
LOCAL DeliveredMessage(intf, p) == [ intf EXCEPT ![p] = Tail(@) ]

\* Process p is trying to receive a message.  If its queue of undelivered
\* messages is non-empty, invoke Deliver(p, m) with m being the first
\* message on its queue.  Deliver should return TRUE if successful.
\* If so, remove the message from the queue.
Receive(p, Deliver(_, _)) ==
    /\ WaitForMessage(mi, p)
    /\ Deliver(p, NextMessage(mi, p))
    /\ mi' = DeliveredMessage(mi, p)
=========================================================================
```

Messaging.tla from https://github.com/tlaplus/PlusPy/blob/master/modules/lib/Messaging.tla

**Comment by konnov** [comment]
Also noticed in #144

**Comment by konnov** [comment]
PR #312 fixes the parsing issue. However, Apalache fails later at the following expression in line 19:

```tla
points == {<<v[1] + m[1], v[2] + m[2]>> : m \in moore}
```

I don't think this is even syntactically correct. Why was not it rejected by SANY?

Btw, our new type checker would have found the mismatch here. Cannot wait until it is integrated :-)

**Comment by konnov** [comment]
ok, my bad, I always confuse maps with filters. Will have a look once again.

**Comment by konnov** [comment]
NVM, this is our bug in #313

**Comment by lemmy** [comment]
Good company: https://github.com/tlaplus/tlapm/issues/11

**Comment by konnov** [comment]
Yeah, we support tuples in set comprehensions by desugaring them. It just stopped working, as the global/recursive functions came into picture.
