### ISSUE TITLE
[BUG] Syntactically invalid type annotations on operators results in uncaught MatchError

### ISSUE THREAD

**Issue by shonfeder** [informalsystems/apalache#332]
I'll fix this.  Just creating an issue to document and organize my work.

---

**Describe the bug**

Etc type checker parser crashes on some syntactically incorrect type signatures.

This turned up when working on #329 

**To Reproduce**

Any operator annotated with a syntactically incorrect target type seems to suffice for reproduction E.g.,

```tlaplus
move(p, d) == "() => <<))" ## 
    ...
```

**Expected behavior**

We should get a helpful error indicating, at least, the location at which the parsing error arose. 

**Log files**

From a failing integration test:

```
--- /home/sf/Sync/informal-systems/apalache/apalache-core/target/test/tla/cli-integration-tests.md.corrected	2020-11-17 16:49:19.161046589 -0500
+++ /home/sf/Sync/informal-systems/apalache/apalache-core/test/tla/cli-integration-tests.md	2020-11-17 16:17:16.194558624 -0500
@@ -682,38 +682,13 @@
 ...
 PASS #1: TypeChecker
  > running ETC: Embarrassingly simple Type Checker
    ^_^
-Unhandled exception
-scala.MatchError: (List(<<Int, Int>>, <<Int, Int>>)~None) (of class scala.util.parsing.combinator.Parsers$$tilde)
-	at at.forsyte.apalache.tla.typecheck.parser.DefaultType1Parser$.$anonfun$typeExpr$5(DefaultType1Parser.scala:55)
-	at scala.util.parsing.combinator.Parsers$Success.map(Parsers.scala:140)
-	at scala.util.parsing.combinator.Parsers$Success.map(Parsers.scala:139)
-	at scala.util.parsing.combinator.Parsers$Parser.$anonfun$map$1(Parsers.scala:235)
-	at scala.util.parsing.combinator.Parsers$$anon$1.apply(Parsers.scala:215)
-	at scala.util.parsing.combinator.Parsers$$anon$5.apply(Parsers.scala:919)
-	at scala.util.parsing.combinator.Parsers$Parser.$anonfun$map$1(Parsers.scala:235)
-	at scala.util.parsing.combinator.Parsers$$anon$1.apply(Parsers.scala:215)
-	at at.forsyte.apalache.tla.typecheck.parser.DefaultType1Parser$.apply(DefaultType1Parser.scala:42)
-	at at.forsyte.apalache.tla.typecheck.parser.DefaultType1Parser$.apply(DefaultType1Parser.scala:33)
-	at at.forsyte.apalache.tla.typecheck.etc.ToEtcExpr.apply(ToEtcExpr.scala:45)
-	at at.forsyte.apalache.tla.typecheck.TypeCheckerTool.$anonfun$check$1(TypeCheckerTool.scala:24)
-	at scala.collection.immutable.List.$anonfun$foldRight$1(List.scala:447)
-	at scala.collection.immutable.List.foldRight(List.scala:91)
-	at at.forsyte.apalache.tla.typecheck.TypeCheckerTool.check(TypeCheckerTool.scala:23)
-	at at.forsyte.apalache.tla.typecheck.passes.EtcTypeCheckerPassImpl.execute(EtcTypeCheckerPassImpl.scala:31)
-	at at.forsyte.apalache.infra.passes.PassChainExecutor.exec$1(PassChainExecutor.scala:23)
-	at at.forsyte.apalache.infra.passes.PassChainExecutor.run(PassChainExecutor.scala:38)
-	at at.forsyte.apalache.tla.Tool$.runTypeCheck(Tool.scala:168)
-	at at.forsyte.apalache.tla.Tool$.$anonfun$run$3(Tool.scala:88)
-	at at.forsyte.apalache.tla.Tool$.$anonfun$run$3$adapted(Tool.scala:88)
-	at at.forsyte.apalache.tla.Tool$.handleExceptions(Tool.scala:216)
-	at at.forsyte.apalache.tla.Tool$.run(Tool.scala:88)
-	at at.forsyte.apalache.tla.Tool$.main(Tool.scala:43)
-	at at.forsyte.apalache.tla.Tool.main(Tool.scala)
-It took me 0 days  0 hours  0 min  1 sec
-Total time: 1.557 sec
-EXITCODE: ERROR (99)
+  =^_^=
+PASS #2: Terminal
+Type checker [OK]
+...
+EXITCODE: OK
 ```

**Comment by shonfeder** [comment]
The fix will include a suite of tests to check against syntactic errors.

**Comment by konnov** [comment]
I am picking this one. This is a good case for PBT.

**Comment by konnov** [comment]
That's fun. Scalacheck immediately produced an error. That's really a big omission in the type parser.
