### ISSUE TITLE
[BUG] Typecheck command fails

### ISSUE THREAD

**Issue by andrey-kuprianov** [informalsystems/apalache#501]
**Describe the bug**

The `typecheck` command fails on this [LightClient spec](https://github.com/informalsystems/tendermint-rs/blob/v0.17.1/light-client/tests/support/model_based/Lightclient_003_draft.tla)

**To Reproduce**

```
/apalache-v0/bin/apalache-mc typecheck Lightclient_003_draft.tla
```

produces

```
PASS #1: TypeChecker                                              I@10:29:58.074
 > running ETC: Embarrassingly simple Type Checker                I@10:29:58.075
   ^_^                                                            I@10:29:58.075
(Please report an issue at: [https://github.com/informalsystems/apalache/issues],java.lang.IllegalArgumentException: Unknown TlaEx expression BMC!<:(S, {BC!NT()}))
Unhandled exception                                               E@10:29:58.128
java.lang.IllegalArgumentException: Unknown TlaEx expression BMC!<:(S, {BC!NT()})
	at at.forsyte.apalache.tla.typecheck.etc.ToEtcExpr.apply(ToEtcExpr.scala:766)
	at at.forsyte.apalache.tla.typecheck.etc.ToEtcExpr.apply(ToEtcExpr.scala:60)
	at at.forsyte.apalache.tla.typecheck.TypeCheckerTool.$anonfun$check$1(TypeCheckerTool.scala:24)
	at scala.collection.immutable.List.$anonfun$foldRight$1(List.scala:447)
	at scala.collection.immutable.List.foldRight(List.scala:91)
	at at.forsyte.apalache.tla.typecheck.TypeCheckerTool.check(TypeCheckerTool.scala:23)
	at at.forsyte.apalache.tla.typecheck.passes.EtcTypeCheckerPassImpl.execute(EtcTypeCheckerPassImpl.scala:31)
	at at.forsyte.apalache.infra.passes.PassChainExecutor.exec$1(PassChainExecutor.scala:23)
	at at.forsyte.apalache.infra.passes.PassChainExecutor.run(PassChainExecutor.scala:38)
	at at.forsyte.apalache.tla.Tool$.runTypeCheck(Tool.scala:186)
	at at.forsyte.apalache.tla.Tool$.$anonfun$run$3(Tool.scala:100)
	at at.forsyte.apalache.tla.Tool$.$anonfun$run$3$adapted(Tool.scala:100)
	at at.forsyte.apalache.tla.Tool$.handleExceptions(Tool.scala:234)
	at at.forsyte.apalache.tla.Tool$.run(Tool.scala:100)
	at at.forsyte.apalache.tla.Tool$.main(Tool.scala:46)
	at at.forsyte.apalache.tla.Tool.main(Tool.scala)

```

**Log files**

See [detailed.log](https://github.com/informalsystems/apalache/files/5886173/detailed.log)

**Desktop**
 - OS: Mac OS
 - JDK version 
   - openjdk 11.0.10 2021-01-19 LTS
   - OpenJDK Runtime Environment Zulu11.45+27-CA (build 11.0.10+9-LTS)
   - OpenJDK 64-Bit Server VM Zulu11.45+27-CA (build 11.0.10+9-LTS, mixed mode)
 - Version: 0.8.2

**Comment by konnov** [comment]
Yes, the new type checker is incompatible with the old type annotations. We are integrating the new type annotations right now. Once it is done, Apalache will complain about the old type annotations and tell the user what to do.

**Comment by konnov** [comment]
In PR #519, the tool warns the user about integration. There is also a page in the manual now.
