### ISSUE TITLE
[BUG] at.forsyte.apalache.tla.bmcmt.TypeException: Unexpected type annotation

### ISSUE THREAD

**Issue by vitorenesduarte** [informalsystems/apalache#533]
**To Reproduce**

```tla
NullActionType == [
    type |-> STRING
]
CreateClientActionType == [
    type |-> STRING,
    height |-> Int   
]
UpdateClientActionType == [
    type |-> STRING,
    clientId |-> Int,
    height |-> Int   
]
ActionType == NullActionType \union CreateClientActionType \union UpdateClientActionType
```

I imagine that the above type does not make sense but with it and `x <: ActionType` I get the following error:

```
# APALACHE version 0.9.0 build 5fce1e5
#
# WARNING: This tool is in the experimental stage.
#          Please report bugs at: [https://github.com/informalsystems/apalache/issues]
# 
# Usage statistics is OFF. We care about your privacy.
# If you want to help our project, consider enabling statistics with config --enable-stats=true.

Checker options: filename=ICS02.tla, init=, next=, inv=           I@14:46:31.190
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.inject.internal.cglib.core.$ReflectUtils$1 (file:/home/vitor.enes/bin/apalache-pkg-0.9.0-full.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of com.google.inject.internal.cglib.core.$ReflectUtils$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Tuning:                                                           I@14:46:31.406
PASS #0: SanyParser                                               I@14:46:31.407
Parsing file /home/vitor.enes/ibc-rs/docs/spec/tla/ics02/ICS02.tla
Parsing file /tmp/Integers.tla
Parsing file /tmp/FiniteSets.tla
Parsing file /tmp/Naturals.tla
Parsing file /tmp/Sequences.tla
PASS #1: ConfigurationPass                                        I@14:46:31.684
  > ICS02.cfg: Loading TLC configuration                          I@14:46:31.685
  > Using the init predicate Init from the TLC config             I@14:46:31.738
  > Using the next predicate Next from the TLC config             I@14:46:31.738
  > ICS02.cfg: found INVARIANTS: TypeOK, ModelNeverErrors         I@14:46:31.738
  > Set the initialization predicate to Init                      I@14:46:31.741
  > Set the transition predicate to Next                          I@14:46:31.742
  > Set an invariant to TypeOK                                    I@14:46:31.742
  > Set an invariant to ModelNeverErrors                          I@14:46:31.742
  > Replaced CONSTANT MaxHeight with 5                            I@14:46:31.743
  > Replaced CONSTANT MaxClientId with 5                          I@14:46:31.743
PASS #2: UnrollPass                                               I@14:46:31.770
  > Unroller                                                      I@14:46:31.788
PASS #3: PrimingPass                                              I@14:46:31.803
  > Introducing InitPrimed for Init'                              I@14:46:31.805
PASS #4: CoverAnalysisPass                                        I@14:46:31.819
PASS #5: InlinePass                                               I@14:46:31.819
  > InlinerOfUserOper                                             I@14:46:31.823
  > LetInExpander                                                 I@14:46:31.833
  > InlinerOfUserOper                                             I@14:46:31.835
Leaving only relevant operators: CInitPrimed, Init, InitPrimed, ModelNeverErrors, Next, TypeOK I@14:46:31.837
PASS #6: VCGen                                                    I@14:46:31.844
  > Producing verification conditions from the invariant TypeOK   I@14:46:31.844
  > VCGen produced 4 verification condition(s)                    I@14:46:31.845
  > Producing verification conditions from the invariant ModelNeverErrors I@14:46:31.846
  > VCGen produced 1 verification condition(s)                    I@14:46:31.846
PASS #7: PreprocessingPass                                        I@14:46:31.854
  > Before preprocessing: unique renaming                         I@14:46:31.855
 > Applying standard transformations:                             I@14:46:31.859
  > Desugarer                                                     I@14:46:31.860
  > PrimePropagation                                              I@14:46:31.875
  > UniqueRenamer                                                 I@14:46:31.884
  > Normalizer                                                    I@14:46:31.899
  > Keramelizer                                                   I@14:46:31.910
  > After preprocessing: UniqueRenamer                            I@14:46:31.930
PASS #8: TransitionFinderPass                                     I@14:46:31.944
  > Found 1 initializing transitions                              I@14:46:31.961
  > Found 6 transitions                                           I@14:46:31.979
  > No constant initializer                                       I@14:46:31.979
  > Applying unique renaming                                      I@14:46:31.980
PASS #9: OptimizationPass                                         I@14:46:31.994
 > Applying optimizations:                                        I@14:46:31.996
  > ConstSimplifier                                               I@14:46:31.997
  > ExprOptimizer                                                 I@14:46:32.001
  > ConstSimplifier                                               I@14:46:32.004
PASS #10: AnalysisPass                                            I@14:46:32.012
 > Marking skolemizable existentials and sets to be expanded...   I@14:46:32.013
  > SkolemizationMarker                                           I@14:46:32.013
  > ExpansionMarker                                               I@14:46:32.014
 > Running analyzers...                                           I@14:46:32.018
  > Introduced expression grades                                  I@14:46:32.027
  > Introduced 4 formula hints                                    I@14:46:32.027
PASS #11: BoundedChecker                                          I@14:46:32.027
(Please report an issue at: [https://github.com/informalsystems/apalache/issues],at.forsyte.apalache.tla.bmcmt.TypeException: Unexpected type annotation: ((["type" ↦ STRING]) ∪ (["type" ↦ STRING, "height" ↦ Int])) ∪ (["type" ↦ STRING, "clientId" ↦ Int, "height" ↦ Int]))
ICS02.tla:132:5-135:29: type error: Unexpected type annotation: ((["type" ↦ STRING]) ∪ (["type" ↦ STRING, "height" ↦ Int])) ∪ (["type" ↦ STRING, "clientId" ↦ Int, "height" ↦ Int]) E@14:46:32.207
at.forsyte.apalache.tla.bmcmt.TypeException: Unexpected type annotation: ((["type" ↦ STRING]) ∪ (["type" ↦ STRING, "height" ↦ Int])) ∪ (["type" ↦ STRING, "clientId" ↦ Int, "height" ↦ Int])
        at at.forsyte.apalache.tla.bmcmt.types.AnnotationParser$.fromTla(AnnotationParser.scala:81)
        at at.forsyte.apalache.tla.bmcmt.types.eager.TrivialTypeFinder.inferAndSave(TrivialTypeFinder.scala:281)
        at at.forsyte.apalache.tla.bmcmt.types.eager.TrivialTypeFinder.inferAndSave(TrivialTypeFinder.scala:155)
        at at.forsyte.apalache.tla.bmcmt.types.eager.TrivialTypeFinder.$anonfun$inferAndSave$8(TrivialTypeFinder.scala:306)
        at scala.collection.immutable.List.map(List.scala:297)
        at at.forsyte.apalache.tla.bmcmt.types.eager.TrivialTypeFinder.inferAndSave(TrivialTypeFinder.scala:306)
        at at.forsyte.apalache.tla.bmcmt.trex.TransitionExecutorImpl.inferTypes(TransitionExecutorImpl.scala:370)
        at at.forsyte.apalache.tla.bmcmt.trex.TransitionExecutorImpl.prepareTransition(TransitionExecutorImpl.scala:94)
        at at.forsyte.apalache.tla.bmcmt.trex.FilteredTransitionExecutor.prepareTransition(FilteredTransitionExecutor.scala:37)
        at at.forsyte.apalache.tla.bmcmt.SeqModelChecker.$anonfun$prepareTransitionsAndCheckInvariants$5(SeqModelChecker.scala:111)
        at at.forsyte.apalache.tla.bmcmt.SeqModelChecker.$anonfun$prepareTransitionsAndCheckInvariants$5$adapted(SeqModelChecker.scala:105)
        at scala.collection.TraversableLike$WithFilter.$anonfun$foreach$1(TraversableLike.scala:924)
        at scala.collection.immutable.List.foreach(List.scala:431)
        at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:923)
        at at.forsyte.apalache.tla.bmcmt.SeqModelChecker.prepareTransitionsAndCheckInvariants(SeqModelChecker.scala:105)
        at at.forsyte.apalache.tla.bmcmt.SeqModelChecker.makeStep(SeqModelChecker.scala:50)
        at at.forsyte.apalache.tla.bmcmt.SeqModelChecker.run(SeqModelChecker.scala:30)
        at at.forsyte.apalache.tla.bmcmt.passes.BoundedCheckerPassImpl.runIncrementalChecker(BoundedCheckerPassImpl.scala:108)
        at at.forsyte.apalache.tla.bmcmt.passes.BoundedCheckerPassImpl.execute(BoundedCheckerPassImpl.scala:83)
        at at.forsyte.apalache.infra.passes.PassChainExecutor.exec$1(PassChainExecutor.scala:23)
        at at.forsyte.apalache.infra.passes.PassChainExecutor.run(PassChainExecutor.scala:38)
        at at.forsyte.apalache.tla.Tool$.runCheck(Tool.scala:173)
        at at.forsyte.apalache.tla.Tool$.$anonfun$run$2(Tool.scala:95)
        at at.forsyte.apalache.tla.Tool$.$anonfun$run$2$adapted(Tool.scala:95)
        at at.forsyte.apalache.tla.Tool$.handleExceptions(Tool.scala:257)
        at at.forsyte.apalache.tla.Tool$.run(Tool.scala:95)
        at at.forsyte.apalache.tla.Tool$.main(Tool.scala:45)
        at at.forsyte.apalache.tla.Tool.main(Tool.scala)
It took me 0 days  0 hours  0 min  1 sec                          I@14:46:32.207
Total time: 1.18 sec                                              I@14:46:32.208
EXITCODE: ERROR (99)
make: *** [Makefile:2: test] Error 99
```

**Desktop (please complete the following information):**
 - Debian GNU/Linux 10
 - openjdk 11.0.9.1 2020-11-04
 - APALACHE version 0.9.0 build 5fce1e5

**Comment by Kukovec** [comment]
While we probably need a nicer exception-report here, the underlying behavior is not a bug, because `ActionType` is not a valid type annotation. The `<:` type annotation syntax does not support union types (or arbitrary TLA+ operators, in general). In fact, the correct annotation to use in place of `ActionType` would actually be `UpdateClientActionType`, since that record type is the common supertype of all three `ActionType` components. 
You can read more about type annotations here: 
https://apalache.informal.systems/docs/apalache/types-and-annotations.html#2-type-annotations (old)
https://apalache.informal.systems/docs/adr/002adr-types.html#2-how-to-write-type-annotations-as-a-user (new)
As a side-remark, `<:` is being phased out and you should consider using code annotations: ` \* @type: ... ;` described in the 2nd link.

**Comment by konnov** [comment]
We have resolved this in the zulip chat. The old annotations are quite confusing, so we are working full speed on integrating the new type checker: https://apalache.informal.systems/docs/apalache/typechecker-snowcat.html
