### ISSUE TITLE
[BUG] Name clash in local instance

### ISSUE THREAD

**Issue by konnov** [informalsystems/apalache#576]
The following example provokes an exception:

```tla
------------------ MODULE localTwice -----------------
------------------ MODULE inst -----------------------
Foo(x) ==
    LET msg == x IN
    msg
======================================================

LOCAL INSTANCE inst

Bar(x) ==
  LET msg == 3 IN
  Foo(x)

======================================================
```

The exception is as follows:

```
Unhandled exception                                               E@21:44:29.698
java.lang.IllegalStateException: Found two different declarations with the same name msg: DeclUnit(TlaOperDecl(msg,List(),3)) and DeclUnit(TlaOperDecl(msg,List(),x))
	at at.forsyte.apalache.tla.imp.Context$ContextImpl$$anonfun$push$1.applyOrElse(Context.scala:134)
	at at.forsyte.apalache.tla.imp.Context$ContextImpl$$anonfun$push$1.applyOrElse(Context.scala:131)
	at scala.PartialFunction$Lifted.apply(PartialFunction.scala:228)
	at scala.PartialFunction$Lifted.apply(PartialFunction.scala:224)
	at scala.Option.collect(Option.scala:432)
	at at.forsyte.apalache.tla.imp.Context$ContextImpl.push(Context.scala:131)
	at at.forsyte.apalache.tla.imp.ExprOrOpArgNodeTranslator.$anonfun$translateLetIn$1(ExprOrOpArgNodeTranslator.scala:113)
	at at.forsyte.apalache.tla.imp.ExprOrOpArgNodeTranslator.$anonfun$translateLetIn$1$adapted(ExprOrOpArgNodeTranslator.scala:107)
	at scala.collection.immutable.List.foreach(List.scala:431)
```

**Comment by konnov** [comment]
This one works now
