### ISSUE TITLE
[BUG] java.lang.IllegalStateException: Found two different declarations with the same name

### ISSUE THREAD

**Issue by vitorenesduarte** [informalsystems/apalache#593]
**To Reproduce**
- `IBC.tla`
```tla
--------------------------------- MODULE IBC ----------------------------------

EXTENDS Integers, FiniteSets, ICS02

VARIABLE action

Init ==
    /\ action = AsAction([type |-> "None"])

Next ==
    LET result == ICS02_CreateClient IN
    UNCHANGED <<action>>

===============================================================================
```

- `ICS02.tla`
```tla
------------------------------- MODULE ICS02 ----------------------------------

EXTENDS Integers, FiniteSets

(********************** TYPE ANNOTATIONS FOR APALACHE ************************)
\* operator for type annotations
a <: b == a

ActionType == [
    type |-> STRING
]
AsAction(a) == a <: ActionType
(******************* END OF TYPE ANNOTATIONS FOR APALACHE ********************)

ICS02_CreateClient ==
    LET action == AsAction([
        type |-> "ICS02CreateClient"
    ]) IN
    "X"

===============================================================================
```

The error should appear with the following:
```bash
$ apalache-mc check IBC.tla
```

**Log files**
```
# APALACHE version 0.10.1-SNAPSHOT build v0.10.0-21-ge2b7e41-dirty
#
# WARNING: This tool is in the experimental stage.
#          Please report bugs at: [https://github.com/informalsystems/apalache/issues]
# 
# Usage statistics is OFF. We care about your privacy.
# If you want to help our project, consider enabling statistics with config --enable-stats=true.

Checker options: filename=IBC.tla, init=, next=, inv=             I@12:07:34.072
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.inject.internal.cglib.core.$ReflectUtils$1 (file:/home/vitor.enes/bin/apalache-pkg-0.10.1-SNAPSHOT-full.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of com.google.inject.internal.cglib.core.$ReflectUtils$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Tuning:                                                           I@12:07:34.295
PASS #0: SanyParser                                               I@12:07:34.296
Parsing file /home/vitor.enes/ibc-rs/modules/tests/support/model_based/IBC.tla
Parsing file /tmp/Integers.tla
Parsing file /tmp/FiniteSets.tla
Parsing file /home/vitor.enes/ibc-rs/modules/tests/support/model_based/ICS02.tla
Parsing file /tmp/Naturals.tla
Parsing file /tmp/Sequences.tla
(Please report an issue at: [https://github.com/informalsystems/apalache/issues],java.lang.IllegalStateException: Found two different declarations with the same name action: DeclUnit(TlaVarDecl(action)) and DeclUnit(TlaOperDecl(action,List(),AsAction(["type" ↦ "ICS02CreateClient"]))))
Unhandled exception                                               E@12:07:34.482
java.lang.IllegalStateException: Found two different declarations with the same name action: DeclUnit(TlaVarDecl(action)) and DeclUnit(TlaOperDecl(action,List(),AsAction(["type" ↦ "ICS02CreateClient"])))
        at at.forsyte.apalache.tla.imp.Context$ContextImpl$$anonfun$push$1.applyOrElse(Context.scala:167)
        at at.forsyte.apalache.tla.imp.Context$ContextImpl$$anonfun$push$1.applyOrElse(Context.scala:164)
        at scala.PartialFunction$Lifted.apply(PartialFunction.scala:228)
        at scala.PartialFunction$Lifted.apply(PartialFunction.scala:224)
        at scala.Option.collect(Option.scala:432)
        at at.forsyte.apalache.tla.imp.Context$ContextImpl.push(Context.scala:164)
        at at.forsyte.apalache.tla.imp.ExprOrOpArgNodeTranslator.$anonfun$translateLetIn$1(ExprOrOpArgNodeTranslator.scala:113)
        at at.forsyte.apalache.tla.imp.ExprOrOpArgNodeTranslator.$anonfun$translateLetIn$1$adapted(ExprOrOpArgNodeTranslator.scala:107)
        at scala.collection.immutable.List.foreach(List.scala:431)
        at at.forsyte.apalache.tla.imp.ExprOrOpArgNodeTranslator.translateLetIn(ExprOrOpArgNodeTranslator.scala:107)
        at at.forsyte.apalache.tla.imp.ExprOrOpArgNodeTranslator.translate(ExprOrOpArgNodeTranslator.scala:52)
        at at.forsyte.apalache.tla.imp.OpDefTranslator.translate(OpDefTranslator.scala:69)
        at at.forsyte.apalache.tla.imp.ModuleTranslator.$anonfun$translate$4(ModuleTranslator.scala:69)
        at at.forsyte.apalache.tla.imp.ModuleTranslator.$anonfun$translate$4$adapted(ModuleTranslator.scala:61)
        at scala.collection.immutable.List.foreach(List.scala:431)
        at at.forsyte.apalache.tla.imp.ModuleTranslator.translate(ModuleTranslator.scala:61)
        at at.forsyte.apalache.tla.imp.SanyImporter.$anonfun$loadFromFile$1(SanyImporter.scala:46)
        at scala.collection.IndexedSeqOptimized.foldLeft(IndexedSeqOptimized.scala:60)
        at scala.collection.IndexedSeqOptimized.foldLeft$(IndexedSeqOptimized.scala:68)
        at scala.collection.mutable.ArrayOps$ofRef.foldLeft(ArrayOps.scala:198)
        at at.forsyte.apalache.tla.imp.SanyImporter.loadFromFile(SanyImporter.scala:44)
        at at.forsyte.apalache.tla.imp.passes.SanyParserPassImpl.execute(SanyParserPassImpl.scala:56)
        at at.forsyte.apalache.infra.passes.PassChainExecutor.exec$1(PassChainExecutor.scala:22)
        at at.forsyte.apalache.infra.passes.PassChainExecutor.run(PassChainExecutor.scala:37)
        at at.forsyte.apalache.tla.Tool$.runCheck(Tool.scala:173)
        at at.forsyte.apalache.tla.Tool$.$anonfun$run$2(Tool.scala:95)
        at at.forsyte.apalache.tla.Tool$.$anonfun$run$2$adapted(Tool.scala:95)
        at at.forsyte.apalache.tla.Tool$.handleExceptions(Tool.scala:258)
        at at.forsyte.apalache.tla.Tool$.run(Tool.scala:95)
        at at.forsyte.apalache.tla.Tool$.main(Tool.scala:45)
        at at.forsyte.apalache.tla.Tool.main(Tool.scala)
It took me 0 days  0 hours  0 min  0 sec                          I@12:07:34.483
Total time: 0.412 sec                                             I@12:07:34.483
EXITCODE: ERROR (99)
```

**Desktop (please complete the following information):**
 - Debian GNU/Linux 10
 - openjdk 11.0.9.1 2020-11-04
 - APALACHE version 0.10.1-SNAPSHOT build v0.10.0-21-ge2b7e41-dirty

**Comment by vitorenesduarte** [comment]
If `LET action` in `ICS02.tla` is replaced by e.g. `LET action2`, the error does not show up.

**Comment by konnov** [comment]
I can see that your spec does not violate the declaration rules, the way they are described in "Specifying Systems". That is why SANY does not complain. It's kind of hard for us to achieve the same scoping of declarations, as we can move declaration around. Please use your solution with `action2` for the time being.

We should add better error reporting for this case. However, I believe that we will keep stricter naming rules in comparison to SANY.

**Comment by vitorenesduarte** [comment]
That makes sense. Maybe some prefixing scheme could be used here to avoid clashing.

**Comment by konnov** [comment]
Do you think of adding a prefix to the names of LET-IN declarations? We are actually doing that for `LOCAL` operators. That could fix your problem.

**Comment by vitorenesduarte** [comment]
> Do you think of adding a prefix to the names of LET-IN declarations?

Yes. I was thinking something like `MODULE_DEFINITION_VARIABLE` (although I don't know if this is enough to remove all ambiguity). In the example above we would get `IBC_Next_action` and `ICS02_ICS02_CreateClient_action`.

I was now remembering that when the two `LET action` were within the same module, the error was not occurring (I think).
Is this what you meant by

> We are actually doing that for `LOCAL` operators.

?

**Comment by konnov** [comment]
Well, we should not rename variables names and the names of the operators. However, we could probably rename all operators that are declared with 'LET action == ... IN ...`.
