### ISSUE TITLE
[BUG] NoSuchFileException when checking a spec in a folder without write permissions

### ISSUE THREAD

**Issue by lemmy** [informalsystems/apalache#644]
User `markus` lacks write permissions for folder `/mnt/lamport/Documents/ProtoBakeryPCal.toolbox/3procs`.

```
markus@ll:/mnt/lamport/Documents/ProtoBakeryPCal.toolbox/3procs$ /home/markus/apalache/bin/apalache-mc check MC
# Tool home: /home/markus/apalache
# Package:   /home/markus/apalache/mod-distribution/target/apalache-pkg-0.11.1-SNAPSHOT-full.jar
# JVM args: -Xmx4096m -DTLA-Library=/home/markus/apalache/src/tla
#
# APALACHE version 0.11.1-SNAPSHOT build v0.11.0-22-g5237650
#
# WARNING: This tool is in the experimental stage.
#          Please report bugs at: [https://github.com/informalsystems/apalache/issues]
# 
# Usage statistics is ON. Thank you!
# If you have changed your mind, disable the statistics with config --enable-stats=false.

Checker options: filename=MC, init=, next=, inv=                  I@22:14:45.313
(Please report an issue at: [https://github.com/informalsystems/apalache/issues],java.nio.file.NoSuchFileException: /mnt/lamport/Documents/ProtoBakeryPCal.toolbox/3procs/x/22.14-11.03.2021-1280428529954293221)
Unhandled exception                                               E@22:14:45.905
java.nio.file.NoSuchFileException: /mnt/lamport/Documents/ProtoBakeryPCal.toolbox/3procs/x/22.14-11.03.2021-1280428529954293221
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:388)
	at java.base/java.nio.file.Files.createDirectory(Files.java:694)
	at java.base/java.nio.file.TempFileHelper.create(TempFileHelper.java:135)
	at java.base/java.nio.file.TempFileHelper.createTempDirectory(TempFileHelper.java:172)
	at java.base/java.nio.file.Files.createTempDirectory(Files.java:970)
	at at.forsyte.apalache.tla.Tool$.createOutputDir(Tool.scala:248)
	at at.forsyte.apalache.tla.Tool$.runCheck(Tool.scala:147)
	at at.forsyte.apalache.tla.Tool$.$anonfun$run$2(Tool.scala:95)
	at at.forsyte.apalache.tla.Tool$.$anonfun$run$2$adapted(Tool.scala:95)
	at at.forsyte.apalache.tla.Tool$.handleExceptions(Tool.scala:264)
	at at.forsyte.apalache.tla.Tool$.run(Tool.scala:95)
	at at.forsyte.apalache.tla.Tool$.main(Tool.scala:45)
	at at.forsyte.apalache.tla.Tool.main(Tool.scala)
It took me 0 days  0 hours  0 min  0 sec                          I@22:14:45.907
Total time: 0.594 sec                                             I@22:14:45.908
EXITCODE: ERROR (99)
```

**Comment by konnov** [comment]
We should handle the exception. Apart from that, it is clear what is happening here. We should not tell the users to report this issue though.
