### ISSUE TITLE
[BUG] Config file silently ignored

### ISSUE THREAD

**Issue by lemmy** [informalsystems/apalache#651]
Perhaps, my interpretation of https://twitter.com/k0nn0v/status/1369927378374426625 is wrong, and Apalache does not automatically pick up a config file like TLC if the file's name matches that of the spec being checked.  However that may be, this bug shows that Apalache's current convention to default to `Init` and `Next` is quite dangerous.

----

With spec from: https://github.com/tlaplus/Examples/tree/master/specifications/EinsteinRiddle

Ignores `FindSolution`
```shell
markus@avocado:/tmp/Examples/specifications/EinsteinRiddle(master)$ apalache check Einstein
# Tool home: /home/markus/src/TLA/_community/apalache
# Package:   /home/markus/src/TLA/_community/apalache/mod-distribution/target/apalache-pkg-0.11.1-SNAPSHOT-full.jar
# JVM args: -Xmx4096m -DTLA-Library=/home/markus/src/TLA/_community/apalache/src/tla
#
# APALACHE version 0.11.1-SNAPSHOT build v0.11.0-17-gf55663c
#
# WARNING: This tool is in the experimental stage.
#          Please report bugs at: [https://github.com/informalsystems/apalache/issues]
# 
# Usage statistics is ON. Thank you!
# If you have changed your mind, disable the statistics with config --enable-stats=false.

Checker options: filename=Einstein, init=, next=, inv=            I@10:17:17.856
Tuning:                                                           I@10:17:18.397
PASS #0: SanyParser                                               I@10:17:18.398
Parsing file /tmp/Examples/specifications/EinsteinRiddle/Einstein.tla
Parsing file /tmp/Naturals.tla
Parsing file /tmp/FiniteSets.tla
Parsing file /tmp/Sequences.tla
PASS #1: ConfigurationPass                                        I@10:17:19.105
  > Einstein: Loading TLC configuration                           I@10:17:19.108
  > No TLC configuration found. Skipping.                         I@10:17:19.117
  > Command line option --init is not set. Using Init             I@10:17:19.117
  > Command line option --next is not set. Using Next             I@10:17:19.117
  > Set the initialization predicate to Init                      I@10:17:19.117
  > Set the transition predicate to Next                          I@10:17:19.119
PASS #2: DesugarerPass                                            I@10:17:19.171
  > Desugaring...                                                 I@10:17:19.171
PASS #3: UnrollPass                                               I@10:17:19.219
  > Unroller                                                      I@10:17:19.286
PASS #4: PrimingPass                                              I@10:17:19.343
  > Introducing InitPrimed for Init'                              I@10:17:19.348
PASS #5: CoverAnalysisPass                                        I@10:17:19.418
PASS #6: InlinePass                                               I@10:17:19.419
  > InlinerOfUserOper                                             I@10:17:19.428
  > LetInExpander                                                 I@10:17:19.472
  > InlinerOfUserOper                                             I@10:17:19.483
Leaving only relevant operators: CInitPrimed, Init, InitPrimed, Next I@10:17:19.490
PASS #7: VCGen                                                    I@10:17:19.535
  > No invariant given. Only deadlocks will be checked            I@10:17:19.536
PASS #8: PreprocessingPass                                        I@10:17:19.569
  > Before preprocessing: unique renaming                         I@10:17:19.570
 > Applying standard transformations:                             I@10:17:19.581
  > PrimePropagation                                              I@10:17:19.583
  > Desugarer                                                     I@10:17:19.617
  > UniqueRenamer                                                 I@10:17:19.659
  > Normalizer                                                    I@10:17:19.726
  > Keramelizer                                                   I@10:17:19.770
  > After preprocessing: UniqueRenamer                            I@10:17:19.842
PASS #9: TransitionFinderPass                                     I@10:17:19.908
  > Found 1 initializing transitions                              I@10:17:19.977
  > Found 1 transitions                                           I@10:17:19.987
  > No constant initializer                                       I@10:17:19.989
  > Applying unique renaming                                      I@10:17:19.994
PASS #10: OptimizationPass                                        I@10:17:20.031
 > Applying optimizations:                                        I@10:17:20.037
  > ConstSimplifier                                               I@10:17:20.038
  > ExprOptimizer                                                 I@10:17:20.052
  > ConstSimplifier                                               I@10:17:20.064
PASS #11: AnalysisPass                                            I@10:17:20.101
 > Marking skolemizable existentials and sets to be expanded...   I@10:17:20.103
  > SkolemizationMarker                                           I@10:17:20.105
  > ExpansionMarker                                               I@10:17:20.107
 > Running analyzers...                                           I@10:17:20.119
  > Introduced expression grades                                  I@10:17:20.166
  > Introduced 2 formula hints                                    I@10:17:20.167
PASS #12: BoundedChecker                                          I@10:17:20.167
Step 0: picking a transition out of 1 transition(s)               I@10:17:21.350
Step 1: picking a transition out of 1 transition(s)               I@10:17:21.361
Step 2: picking a transition out of 1 transition(s)               I@10:17:21.373
Step 3: picking a transition out of 1 transition(s)               I@10:17:21.393
Step 4: picking a transition out of 1 transition(s)               I@10:17:21.408
Step 5: picking a transition out of 1 transition(s)               I@10:17:21.416
Step 6: picking a transition out of 1 transition(s)               I@10:17:21.431
Step 7: picking a transition out of 1 transition(s)               I@10:17:21.440
Step 8: picking a transition out of 1 transition(s)               I@10:17:21.447
Step 9: picking a transition out of 1 transition(s)               I@10:17:21.460
Step 10: picking a transition out of 1 transition(s)              I@10:17:21.470
The outcome is: NoError                                           I@10:17:21.475
PASS #13: Terminal                                                I@10:17:21.476
Checker reports no error up to computation length 10              I@10:17:21.477
It took me 0 days  0 hours  0 min  3 sec                          I@10:17:21.477
Total time: 3.625 sec                                             I@10:17:21.477
EXITCODE: OK
```

Works when explicitly set:
```shell
markus@avocado:/tmp/Examples/specifications/EinsteinRiddle(master)$ apalache check --inv=FindSolution Einstein
# Tool home: /home/markus/src/TLA/_community/apalache
# Package:   /home/markus/src/TLA/_community/apalache/mod-distribution/target/apalache-pkg-0.11.1-SNAPSHOT-full.jar
# JVM args: -Xmx4096m -DTLA-Library=/home/markus/src/TLA/_community/apalache/src/tla
#
# APALACHE version 0.11.1-SNAPSHOT build v0.11.0-17-gf55663c
#
# WARNING: This tool is in the experimental stage.
#          Please report bugs at: [https://github.com/informalsystems/apalache/issues]
# 
# Usage statistics is ON. Thank you!
# If you have changed your mind, disable the statistics with config --enable-stats=false.

Checker options: filename=Einstein, init=, next=, inv=FindSolution I@10:18:12.096
Tuning:                                                           I@10:18:12.632
PASS #0: SanyParser                                               I@10:18:12.634
Parsing file /tmp/Examples/specifications/EinsteinRiddle/Einstein.tla
Parsing file /tmp/Naturals.tla
Parsing file /tmp/FiniteSets.tla
Parsing file /tmp/Sequences.tla
PASS #1: ConfigurationPass                                        I@10:18:13.727
  > Einstein: Loading TLC configuration                           I@10:18:13.730
  > No TLC configuration found. Skipping.                         I@10:18:13.737
  > Command line option --init is not set. Using Init             I@10:18:13.737
  > Command line option --next is not set. Using Next             I@10:18:13.737
  > Set the initialization predicate to Init                      I@10:18:13.738
  > Set the transition predicate to Next                          I@10:18:13.739
  > Set an invariant to FindSolution                              I@10:18:13.740
PASS #2: DesugarerPass                                            I@10:18:13.820
  > Desugaring...                                                 I@10:18:13.821
PASS #3: UnrollPass                                               I@10:18:13.906
  > Unroller                                                      I@10:18:13.977
PASS #4: PrimingPass                                              I@10:18:14.037
  > Introducing InitPrimed for Init'                              I@10:18:14.052
PASS #5: CoverAnalysisPass                                        I@10:18:14.238
PASS #6: InlinePass                                               I@10:18:14.241
  > InlinerOfUserOper                                             I@10:18:14.258
  > LetInExpander                                                 I@10:18:14.323
  > InlinerOfUserOper                                             I@10:18:14.344
Leaving only relevant operators: CInitPrimed, FindSolution, Init, InitPrimed, Next I@10:18:14.365
PASS #7: VCGen                                                    I@10:18:14.486
  > Producing verification conditions from the invariant FindSolution I@10:18:14.490
  > VCGen produced 1 verification condition(s)                    I@10:18:14.499
PASS #8: PreprocessingPass                                        I@10:18:14.589
  > Before preprocessing: unique renaming                         I@10:18:14.590
 > Applying standard transformations:                             I@10:18:14.622
  > PrimePropagation                                              I@10:18:14.624
  > Desugarer                                                     I@10:18:14.748
  > UniqueRenamer                                                 I@10:18:14.877
  > Normalizer                                                    I@10:18:15.005
  > Keramelizer                                                   I@10:18:15.103
  > After preprocessing: UniqueRenamer                            I@10:18:15.227
PASS #9: TransitionFinderPass                                     I@10:18:15.371
  > Found 1 initializing transitions                              I@10:18:15.444
  > Found 1 transitions                                           I@10:18:15.458
  > No constant initializer                                       I@10:18:15.458
  > Applying unique renaming                                      I@10:18:15.460
PASS #10: OptimizationPass                                        I@10:18:15.519
 > Applying optimizations:                                        I@10:18:15.524
  > ConstSimplifier                                               I@10:18:15.525
  > ExprOptimizer                                                 I@10:18:15.551
  > ConstSimplifier                                               I@10:18:15.570
PASS #11: AnalysisPass                                            I@10:18:15.620
 > Marking skolemizable existentials and sets to be expanded...   I@10:18:15.624
  > SkolemizationMarker                                           I@10:18:15.627
  > ExpansionMarker                                               I@10:18:15.630
 > Running analyzers...                                           I@10:18:15.658
  > Introduced expression grades                                  I@10:18:15.729
  > Introduced 3 formula hints                                    I@10:18:15.730
PASS #12: BoundedChecker                                          I@10:18:15.732
State 0: Checking 1 invariants                                    I@10:18:17.084
State 0: Invariant 0 violated. Check the counterexample in: counterexample.tla, MC.out, counterexample.json E@10:18:17.307
The outcome is: Error                                             I@10:18:17.312
Checker has found an error                                        I@10:18:17.313
It took me 0 days  0 hours  0 min  5 sec                          I@10:18:17.313
Total time: 5.220 sec                                             I@10:18:17.313
EXITCODE: OK
```

**Comment by konnov** [comment]
For some reason, it did not find the config file:

> Einstein: Loading TLC configuration
> No TLC configuration found. Skipping.

**Comment by lemmy** [comment]
Yes, that clearly the root cause.  In addition, I suggest showing something like this at the end (and reconsider the `Init` and `Next` convention):

```
The outcome is: NoError (FOR NO INVARIANT)
```


About Apalache's convention, does `Spec` or `Init` and `Next` take precedence?

**Comment by konnov** [comment]
`Init` and `Next` are default names. A `Spec` can be only specified in a config file.

**Comment by lemmy** [comment]
This bug is also confusing in the light of Snowcat (works with `apalache check --config=EWD840.cfg EWD840` but crashes with an exception with `apalache check EWD840`):

```tla
------------------------------- MODULE EWD840 -------------------------------
EXTENDS Naturals

CONSTANT
    \* @type: Int;
    N

ASSUME NAssumption == N \in (Nat \ {0})

Node == 0 .. N-1

black == "black"
white == "white"
Color == {black, white}

VARIABLES 
    \* @type: Int -> Bool;
    active,
    \* @type: Int -> Str;
    color, 
    \* @type: Int;
    tpos, 
    \* @type: Str;
    tcolor
vars == <<active, color, tpos, tcolor>>

TypeOK ==
  /\ active \in [Node -> BOOLEAN]
  /\ color \in [Node -> Color]
  /\ tpos \in Node
  /\ tcolor \in Color

Init ==
  /\ active \in [Node -> BOOLEAN]
  /\ color \in [Node -> Color]
  /\ tpos \in Node
  /\ tcolor = black

InitiateProbe ==
  /\ tpos = 0
  /\ \/ tcolor = black
     \/ color[0] = black
  /\ tpos' = N-1
  /\ tcolor' = white
  /\ color' = [color EXCEPT ![0] = white]
  /\ UNCHANGED <<active>>

PassToken(i) ==
    /\  \/ ~active[i]
        \* There is no need to wait for this node to terminate if a
        \* higher-numbered node has already marked this round inconclusive.
        \* Instead, the initiator may start a new round (upon receipt of
        \* the token) in the meantime.
        \/ tcolor = black
        \* Likewise, don't wait for this node to terminate, if it is
        \* going to cause an inconclusive round.
        \/ color[i] = black
    /\ tpos = i
    /\ tpos' = i-1
    \* Passing along the token transfers the taint
    \* from the node to the token.
    /\ tcolor' = IF color[i] = black THEN black ELSE tcolor
    /\ color' = [color EXCEPT ![i] = white]
    /\ UNCHANGED <<active>>

System == InitiateProbe \/ \E i \in Node \ {0} : PassToken(i)

-----------------------------------------------------------------------------

Deactivate(i) ==
    /\ active[i]
    /\ active' = [active EXCEPT ![i] = FALSE]
    /\ UNCHANGED <<color, tpos, tcolor>>

SendMsg(i) ==
    /\ active[i]
    /\ \E j \in Node:
            /\ active' = [active EXCEPT ![j] = TRUE]
            \* If the message activates a lower-numbered node, there is
            \* no need to taint the token to mark the round inconclusive.
            \* This is because the lower numbered node has not yet received
            \* the token for this round and, thus, can taint it itself.
            \* Thus, this is an optimization to avoid another round in the
            \* case that the recipient node deactivates between receiving
            \* the message and the token.
            /\ color' = [color EXCEPT ![i] = IF j>i THEN black ELSE @]
    /\ UNCHANGED <<tpos, tcolor>>

Environment ==
    \E i \in Node:
        \/ Deactivate(i)
        \/ SendMsg(i)

Next == System \/ Environment

Spec == Init /\ [][Next]_vars /\ WF_vars(System)

-----------------------------------------------------------------------------

terminationDetected ==
    /\ ~active[0]
    /\ color[0] = white
    /\ tpos = 0
    /\ tcolor = white

terminated ==
    \A n \in Node: ~active[n]

\* If termination has been detected, all nodes are
\* indeed inactive.
Inv == 
    terminationDetected => terminated

THEOREM Spec => []Inv

-----------------------------------------------------------------------------

\* Dijkstra's (inductive) invariant.
IInv ==
    \/ P0:: \A i \in Node : tpos < i => ~ active[i]
    \/ P1:: \E j \in 0 .. tpos : color[j] = black
    \/ P2:: tcolor = black

THEOREM Spec => []IInv

-----------------------------------------------------------------------------

\* Termination of nodes leads to termination being detected.
Prop ==
    terminated ~> terminationDetected

THEOREM Spec => Prop

-----------------------------------------------------------------------------

SpecWFEnv ==
    Spec /\ WF_vars(Environment)

AlwaysTerminates ==    
    <>[](terminationDetected)

THEOREM SpecWFEnv => AlwaysTerminates

=============================================================================
```

```
CONSTANTS
    N = 5

SPECIFICATION 
    Spec

INVARIANT
    TypeOK
    Inv
    \* IInv

PROPERTY 
    Prop
```

```shell
arkus@avocado:~/src/TLA/_specs/models/tutorials/ewd840(main)$ apalache check EWD840
# Tool home: /home/markus/src/TLA/_community/apalache
# Package:   /home/markus/src/TLA/_community/apalache/mod-distribution/target/apalache-pkg-0.15.2-SNAPSHOT-full.jar
# JVM args: -Xmx4096m -DTLA-Library=/home/markus/src/TLA/_community/apalache/src/tla
#
# APALACHE version 0.15.2-SNAPSHOT build v0.15.1-4-gb68618c
#
# WARNING: This tool is in the experimental stage.
#          Please report bugs at: [https://github.com/informalsystems/apalache/issues]
# 
# Usage statistics is ON. Thank you!
# If you have changed your mind, disable the statistics with config --enable-stats=false.

Checker options: filename=EWD840, init=, next=, inv=              I@17:44:44.125
Tuning:                                                           I@17:44:44.571
PASS #0: SanyParser                                               I@17:44:44.572
Parsing file /home/markus/src/TLA/_specs/models/tutorials/ewd840/EWD840.tla
Parsing file /tmp/Naturals.tla
PASS #1: TypeCheckerSnowcat                                       I@17:44:45.292
 > Running Snowcat .::.                                           I@17:44:45.292
 > Your types are great!                                          I@17:44:45.610
 > All expressions are typed                                      I@17:44:45.610
PASS #2: ConfigurationPass                                        I@17:44:45.641
  > EWD840: Loading TLC configuration                             I@17:44:45.645
  > No TLC configuration found. Skipping.                         I@17:44:45.654
  > Command line option --init is not set. Using Init             I@17:44:45.655
  > Command line option --next is not set. Using Next             I@17:44:45.656
  > Set the initialization predicate to Init                      I@17:44:45.657
  > Set the transition predicate to Next                          I@17:44:45.660
PASS #3: DesugarerPass                                            I@17:44:45.697
  > Desugaring...                                                 I@17:44:45.697
PASS #4: UnrollPass                                               I@17:44:45.735
  > Unroller                                                      I@17:44:45.777
PASS #5: PrimingPass                                              I@17:44:45.814
  > Introducing InitPrimed for Init'                              I@17:44:45.819
PASS #6: CoverAnalysisPass                                        I@17:44:45.842
PASS #7: InlinePass                                               I@17:44:45.844
  > InlinerOfUserOper                                             I@17:44:45.845
  > LetInExpander                                                 I@17:44:45.874
  > InlinerOfUserOper                                             I@17:44:45.879
Leaving only relevant operators: CInitPrimed, Init, InitPrimed, Next I@17:44:45.884
PASS #8: VCGen                                                    I@17:44:45.894
  > No invariant given. Only deadlocks will be checked            I@17:44:45.894
PASS #9: PreprocessingPass                                        I@17:44:45.908
  > Before preprocessing: unique renaming                         I@17:44:45.908
 > Applying standard transformations:                             I@17:44:45.916
  > PrimePropagation                                              I@17:44:45.917
  > Desugarer                                                     I@17:44:45.930
  > UniqueRenamer                                                 I@17:44:45.947
  > Normalizer                                                    I@17:44:45.962
  > Keramelizer                                                   I@17:44:45.983
  > After preprocessing: UniqueRenamer                            I@17:44:46.009
PASS #10: TransitionFinderPass                                    I@17:44:46.032
  > Found 1 initializing transitions                              I@17:44:46.080
  > Found 4 transitions                                           I@17:44:46.105
  > No constant initializer                                       I@17:44:46.105
  > Applying unique renaming                                      I@17:44:46.106
PASS #11: OptimizationPass                                        I@17:44:46.130
 > Applying optimizations:                                        I@17:44:46.136
  > ConstSimplifier                                               I@17:44:46.137
  > ExprOptimizer                                                 I@17:44:46.150
  > ConstSimplifier                                               I@17:44:46.157
PASS #12: AnalysisPass                                            I@17:44:46.171
 > Marking skolemizable existentials and sets to be expanded...   I@17:44:46.180
  > SkolemizationMarker                                           I@17:44:46.181
  > ExpansionMarker                                               I@17:44:46.183
 > Running analyzers...                                           I@17:44:46.197
  > Introduced expression grades                                  I@17:44:46.212
  > Introduced 2 formula hints                                    I@17:44:46.212
PASS #13: PostTypeCheckerSnowcat                                  I@17:44:46.213
 > Running Snowcat .::.                                           I@17:44:46.213
 > Your types are great!                                          I@17:44:46.374
 > All expressions are typed                                      I@17:44:46.375
PASS #14: BoundedChecker                                          I@17:44:46.390
(Please report an issue at: [https://github.com/informalsystems/apalache/issues],at.forsyte.apalache.tla.bmcmt.RewriterException: Expected a constant integer range in .., found 0..N - 1)
EWD840.tla:34:18-34:21: rewriter error: Expected a constant integer range in .., found 0..N - 1 E@17:44:46.681
at.forsyte.apalache.tla.bmcmt.RewriterException: Expected a constant integer range in .., found 0..N - 1
	at at.forsyte.apalache.tla.bmcmt.rules.IntDotDotRule.getRange(IntDotDotRule.scala:52)
	at at.forsyte.apalache.tla.bmcmt.rules.IntDotDotRule.apply(IntDotDotRule.scala:31)
	at at.forsyte.apalache.tla.bmcmt.SymbStateRewriterImpl.rewriteOnce(SymbStateRewriterImpl.scala:329)
	at at.forsyte.apalache.tla.bmcmt.SymbStateRewriterImpl.doRecursive$1(SymbStateRewriterImpl.scala:360)
	at at.forsyte.apalache.tla.bmcmt.SymbStateRewriterImpl.rewriteUntilDone(SymbStateRewriterImpl.scala:394)
	at at.forsyte.apalache.tla.bmcmt.rules.FunSetCtorRule.apply(FunSetCtorRule.scala:26)
	at at.forsyte.apalache.tla.bmcmt.SymbStateRewriterImpl.rewriteOnce(SymbStateRewriterImpl.scala:329)
	at at.forsyte.apalache.tla.bmcmt.SymbStateRewriterImpl.doRecursive$1(SymbStateRewriterImpl.scala:360)
	at at.forsyte.apalache.tla.bmcmt.SymbStateRewriterImpl.rewriteUntilDone(SymbStateRewriterImpl.scala:394)
	at at.forsyte.apalache.tla.bmcmt.rules.QuantRule.apply(QuantRule.scala:46)
	at at.forsyte.apalache.tla.bmcmt.SymbStateRewriterImpl.rewriteOnce(SymbStateRewriterImpl.scala:329)
	at at.forsyte.apalache.tla.bmcmt.SymbStateRewriterImpl.doRecursive$1(SymbStateRewriterImpl.scala:360)
	at at.forsyte.apalache.tla.bmcmt.SymbStateRewriterImpl.rewriteUntilDone(SymbStateRewriterImpl.scala:394)
	at at.forsyte.apalache.tla.bmcmt.rules.AndRule.mapArg$1(AndRule.scala:82)
	at at.forsyte.apalache.tla.bmcmt.rules.AndRule.$anonfun$apply$2(AndRule.scala:86)
	at scala.collection.immutable.List.map(List.scala:293)
	at at.forsyte.apalache.tla.bmcmt.rules.AndRule.apply(AndRule.scala:86)
	at at.forsyte.apalache.tla.bmcmt.SymbStateRewriterImpl.rewriteOnce(SymbStateRewriterImpl.scala:329)
	at at.forsyte.apalache.tla.bmcmt.SymbStateRewriterImpl.doRecursive$1(SymbStateRewriterImpl.scala:360)
	at at.forsyte.apalache.tla.bmcmt.SymbStateRewriterImpl.rewriteUntilDone(SymbStateRewriterImpl.scala:394)
	at at.forsyte.apalache.tla.bmcmt.trex.TransitionExecutorImpl.prepareTransition(TransitionExecutorImpl.scala:98)
	at at.forsyte.apalache.tla.bmcmt.trex.FilteredTransitionExecutor.prepareTransition(FilteredTransitionExecutor.scala:34)
	at at.forsyte.apalache.tla.bmcmt.SeqModelChecker.$anonfun$prepareTransitionsAndCheckInvariants$5(SeqModelChecker.scala:112)
	at at.forsyte.apalache.tla.bmcmt.SeqModelChecker.$anonfun$prepareTransitionsAndCheckInvariants$5$adapted(SeqModelChecker.scala:106)
	at scala.collection.TraversableLike$WithFilter.$anonfun$foreach$1(TraversableLike.scala:924)
	at scala.collection.immutable.List.foreach(List.scala:431)
	at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:923)
	at at.forsyte.apalache.tla.bmcmt.SeqModelChecker.prepareTransitionsAndCheckInvariants(SeqModelChecker.scala:106)
	at at.forsyte.apalache.tla.bmcmt.SeqModelChecker.makeStep(SeqModelChecker.scala:51)
	at at.forsyte.apalache.tla.bmcmt.SeqModelChecker.run(SeqModelChecker.scala:31)
	at at.forsyte.apalache.tla.bmcmt.passes.BoundedCheckerPassImpl.runIncrementalChecker(BoundedCheckerPassImpl.scala:120)
	at at.forsyte.apalache.tla.bmcmt.passes.BoundedCheckerPassImpl.execute(BoundedCheckerPassImpl.scala:87)
	at at.forsyte.apalache.infra.passes.PassChainExecutor.exec$1(PassChainExecutor.scala:22)
	at at.forsyte.apalache.infra.passes.PassChainExecutor.run(PassChainExecutor.scala:37)
	at at.forsyte.apalache.tla.Tool$.runCheck(Tool.scala:175)
	at at.forsyte.apalache.tla.Tool$.$anonfun$run$2(Tool.scala:95)
	at at.forsyte.apalache.tla.Tool$.$anonfun$run$2$adapted(Tool.scala:95)
	at at.forsyte.apalache.tla.Tool$.handleExceptions(Tool.scala:260)
	at at.forsyte.apalache.tla.Tool$.run(Tool.scala:95)
	at at.forsyte.apalache.tla.Tool$.main(Tool.scala:45)
	at at.forsyte.apalache.tla.Tool.main(Tool.scala)
It took me 0 days  0 hours  0 min  2 sec                          I@17:44:46.682
Total time: 2.559 sec                                             I@17:44:46.682
EXITCODE: ERROR (99)
```

**Comment by konnov** [comment]
As for the last error, we are pointing the user to the known issues right now: https://apalache.informal.systems/docs/apalache/known-issues.html#integer-ranges-with-non-constant-bounds
