### ISSUE TITLE
[BUG] Unhandled exception - Scala MatchError

### ISSUE THREAD

**Issue by Isaac-DeFrain** [informalsystems/apalache#748]
## Description

I have successfully verified the inductive invariant `IndInv` for a [smaller model](https://github.com/tezedge/model-p2p/tree/handshaking/handshaking/blacklist_timeouts/apalache/2good_3bad) of this spec. However, when I attempt to verify `IndInv` on a [larger model](https://github.com/tezedge/model-p2p/tree/handshaking/handshaking/blacklist_timeouts/apalache/5good_5bad) I get the error:
```
PASS #11: OptimizationPass                                        I@20:50:59.125
 > Applying optimizations:                                        I@20:50:59.128
  > ConstSimplifier                                               I@20:50:59.129
  > ExprOptimizer                                                 I@20:50:59.159
(Please report an issue at: [https://github.com/informalsystems/apalache/issues],scala.MatchError: Cardinality(5 .. 9) ≥ 4 (of class at.forsyte.apalache.tla.lir.OperEx))
Unhandled exception                                               E@20:50:59.162
scala.MatchError: Cardinality(5 .. 9) ≥ 4 (of class at.forsyte.apalache.tla.lir.OperEx)
        at scala.PartialFunction$$anon$1.apply(PartialFunction.scala:259)
        at scala.PartialFunction$$anon$1.apply(PartialFunction.scala:257)
        at at.forsyte.apalache.tla.pp.ExprOptimizer$$anonfun$at$forsyte$apalache$tla$pp$ExprOptimizer$$transformCard$1.applyOrElse(ExprOptimizer.scala:69)
        at at.forsyte.apalache.tla.pp.ExprOptimizer$$anonfun$at$forsyte$apalache$tla$pp$ExprOptimizer$$transformCard$1.applyOrElse(ExprOptimizer.scala:69)
        at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:38)
        at at.forsyte.apalache.tla.pp.ExprOptimizer$$anonfun$at$forsyte$apalache$tla$pp$ExprOptimizer$$transformCard$1.applyOrElse(ExprOptimizer.scala:130)
        at at.forsyte.apalache.tla.pp.ExprOptimizer$$anonfun$at$forsyte$apalache$tla$pp$ExprOptimizer$$transformCard$1.applyOrElse(ExprOptimizer.scala:69)
        at scala.PartialFunction$OrElse.apply(PartialFunction.scala:172)
        at at.forsyte.apalache.tla.pp.ExprOptimizer$$anonfun$transformSets$1.applyOrElse(ExprOptimizer.scala:55)
        at at.forsyte.apalache.tla.pp.ExprOptimizer$$anonfun$transformSets$1.applyOrElse(ExprOptimizer.scala:55)
        at scala.PartialFunction$OrElse.apply(PartialFunction.scala:172)
        at at.forsyte.apalache.tla.pp.ExprOptimizer$$anonfun$transformFuns$1.applyOrElse(ExprOptimizer.scala:38)
        at at.forsyte.apalache.tla.pp.ExprOptimizer$$anonfun$transformFuns$1.applyOrElse(ExprOptimizer.scala:38)
        at scala.PartialFunction$OrElse.apply(PartialFunction.scala:172)
        at at.forsyte.apalache.tla.lir.transformations.impl.TrackerWithListeners.$anonfun$trackEx$1(TrackerWithListeners.scala:16)
        at at.forsyte.apalache.tla.pp.AbstractTransformer.$anonfun$transform$1(AbstractTransformer.scala:36)
        at at.forsyte.apalache.tla.lir.transformations.impl.TrackerWithListeners.$anonfun$trackEx$1(TrackerWithListeners.scala:16)
        at at.forsyte.apalache.tla.pp.ExprOptimizer.apply(ExprOptimizer.scala:30)
        at at.forsyte.apalache.tla.pp.ExprOptimizer.apply(ExprOptimizer.scala:20)
        at at.forsyte.apalache.tla.lir.transformations.standard.ModuleByExTransformer.$anonfun$apply$1(ModuleByExTransformer.scala:25)
        at at.forsyte.apalache.tla.lir.transformations.standard.ModuleByExTransformer.mapIfIncluded$1(ModuleByExTransformer.scala:37)
        at at.forsyte.apalache.tla.lir.transformations.standard.ModuleByExTransformer.$anonfun$apply$2(ModuleByExTransformer.scala:43)
        at scala.collection.immutable.List.map(List.scala:297)
        at at.forsyte.apalache.tla.lir.transformations.standard.ModuleByExTransformer.apply(ModuleByExTransformer.scala:43)
        at at.forsyte.apalache.tla.pp.passes.OptPassImpl.$anonfun$execute$1(OptPassImpl.scala:55)
        at scala.collection.LinearSeqOptimized.foldLeft(LinearSeqOptimized.scala:126)
        at scala.collection.LinearSeqOptimized.foldLeft$(LinearSeqOptimized.scala:122)
        at scala.collection.immutable.List.foldLeft(List.scala:91)
        at at.forsyte.apalache.tla.pp.passes.OptPassImpl.execute(OptPassImpl.scala:53)
        at at.forsyte.apalache.infra.passes.PassChainExecutor.exec$1(PassChainExecutor.scala:22)
        at at.forsyte.apalache.infra.passes.PassChainExecutor.run(PassChainExecutor.scala:37)
        at at.forsyte.apalache.tla.Tool$.runCheck(Tool.scala:183)
        at at.forsyte.apalache.tla.Tool$.$anonfun$run$3(Tool.scala:95)
        at at.forsyte.apalache.tla.Tool$.handleExceptions(Tool.scala:309)
        at at.forsyte.apalache.tla.Tool$.run(Tool.scala:95)
        at at.forsyte.apalache.tla.Tool$.main(Tool.scala:45)
        at at.forsyte.apalache.tla.Tool.main(Tool.scala)
```

## Input specification

[The spec and larger model](https://github.com/tezedge/model-p2p/tree/handshaking/handshaking/blacklist_timeouts/apalache/5good_5bad)

## The command line parameters used to run the tool

`apalache check --init=Init --inv=IndInv --length=0 MC_safety_5good_5bad.tla`

## Expected behavior

Another successful verification of `IndInv`

## Log files

[detailed.log](https://github.com/tezedge/model-p2p/blob/handshaking/handshaking/blacklist_timeouts/apalache/5good_5bad/detailed.log)
[command line output](https://github.com/tezedge/model-p2p/blob/handshaking/handshaking/blacklist_timeouts/apalache/5good_5bad/MC_safety_5good_5bad.out)

## System information

- Apalache version [`apalache-mc version`]: `0.15.3-SNAPSHOT build v0.15.1-33-g80cf914`
- OS [e.g. Ubuntu Linux or Mac OS, and the current version]: Debian 10
- JDK version [e.g. OpenJDK 0.8.0]:
```
openjdk version "11.0.9.1" 2020-11-04
OpenJDK Runtime Environment (build 11.0.9.1+1-post-Debian-1deb10u2)
OpenJDK 64-Bit Server VM (build 11.0.9.1+1-post-Debian-1deb10u2, mixed mode, sharing)
```

**Comment by konnov** [comment]
That was an uncareful call to a partial function. I will fix it today.

**Comment by Isaac-DeFrain** [comment]
When will this change be available in unstable?

**Comment by konnov** [comment]
I think it has been just released: https://github.com/informalsystems/apalache/releases/tag/v0.15.3

**Comment by Isaac-DeFrain** [comment]
When will that release be made the unstable Docker image?

**Comment by konnov** [comment]
I guess, the unstable version is actually the most recent one: https://hub.docker.com/r/apalache/mc/tags?page=1&ordering=last_updated

We are trying to figure out how the tags are assigned.

**Comment by shonfeder** [comment]
The docker hub build queue is just a bit backed up. I cancelled some pending builds we don't care about, and it's now working its way through the latest release (Currently building the 0.15.3 release). I also reconfigured the builds rules so that we should have less pressure on the build queue in the future.
