### ISSUE TITLE
[BUG] How to replace z3-turnkey with z3 installed via a package manager?

### ISSUE THREAD

**Issue by lemmy** [informalsystems/apalache#849]
Note that "aarch64" = "arm64".

```shell
(Please report an issue at: [https://github.com/informalsystems/apalache/issues],java.lang.UnsatisfiedLinkError: Unsupported CPU architecture: aarch64)
Unhandled exception                                               E@18:44:42.428
java.lang.UnsatisfiedLinkError: Unsupported CPU architecture: aarch64
	at com.microsoft.z3.Z3Loader$CPUArchitecture.identify(Z3Loader.java:183)
	at com.microsoft.z3.Z3Loader.loadZ3(Z3Loader.java:57)
	at com.microsoft.z3.Native.<clinit>(Native.java:36)
	at com.microsoft.z3.Global.setParameter(Global.java:47)
	at at.forsyte.apalache.tla.bmcmt.smt.Z3SolverContext.$anonfun$new$1(Z3SolverContext.scala:41)
	at at.forsyte.apalache.tla.bmcmt.smt.Z3SolverContext.$anonfun$new$1$adapted(Z3SolverContext.scala:40)
	at scala.collection.immutable.List.foreach(List.scala:431)
	at at.forsyte.apalache.tla.bmcmt.smt.Z3SolverContext.<init>(Z3SolverContext.scala:40)
	at at.forsyte.apalache.tla.bmcmt.smt.RecordingSolverContext$.createZ3(RecordingSolverContext.scala:20)
	at at.forsyte.apalache.tla.bmcmt.passes.BoundedCheckerPassImpl.runIncrementalChecker(BoundedCheckerPassImpl.scala:105)
	at at.forsyte.apalache.tla.bmcmt.passes.BoundedCheckerPassImpl.execute(BoundedCheckerPassImpl.scala:96)
	at at.forsyte.apalache.infra.passes.PassChainExecutor.exec$1(PassChainExecutor.scala:22)
	at at.forsyte.apalache.infra.passes.PassChainExecutor.run(PassChainExecutor.scala:37)
	at at.forsyte.apalache.tla.Tool$.runCheck(Tool.scala:184)
	at at.forsyte.apalache.tla.Tool$.$anonfun$run$3(Tool.scala:95)
	at at.forsyte.apalache.tla.Tool$.handleExceptions(Tool.scala:319)
	at at.forsyte.apalache.tla.Tool$.run(Tool.scala:95)
	at at.forsyte.apalache.tla.Tool$.main(Tool.scala:45)
	at at.forsyte.apalache.tla.Tool.main(Tool.scala)
```

```shell
root@sv-c2-large-arm-01:~/ewd998# dpkg -l|grep z3
ii  libz3-4:arm64                        4.8.7-4build1                     arm64        theorem prover from Microsoft Research - runtime libraries
ii  libz3-dev:arm64                      4.8.7-4build1                     arm64        theorem prover from Microsoft Research - development files
ii  libz3-java                           4.8.7-4build1                     arm64        theorem prover from Microsoft Research - java bindings
ii  libz3-jni:arm64                      4.8.7-4build1                     arm64        theorem prover from Microsoft Research - JNI library
ii  z3                                   4.8.7-4build1                     arm64        theorem prover from Microsoft Research
```

**Comment by konnov** [comment]
> Fundamentally, I don't care where z3 is coming from.

We have to care, as the z3 team is breaking their APIs from time to time.

**Comment by konnov** [comment]
I am not sure what to do about it. It does not look like a high priority issue. Do you need it for an installation in an AWS instance?

**Comment by lemmy** [comment]
The z3 loader doesn't know about `aarch64` but seems to [just copy the libraries](https://github.com/tudo-aqua/z3-turnkey/blob/master/src/main/java/com/microsoft/z3/Z3Loader.java) to some location from where Java picks it up.  For those that run into this problem: I would assume one could load ("linear classpath") a custom implementation of `com.microsoft.z3.Z3Loader` that does the right thing on aarch64.

**Comment by thpani** [comment]
I've requested support for `aarch64` from upstream in https://github.com/tudo-aqua/z3-turnkey/issues/12. See also https://github.com/informalsystems/apalache/issues/751.

**Comment by shonfeder** [comment]
We've also just discussed internally about the possibility of adding an option to our build configuration that would allow using the system Z3 instead of z3-turnkey. I'll plan to investigate.

**Comment by thpani** [comment]
#1718 introduced support for `aarch64`

Given our heavy reliance on Z3, targeting an arbitrary-version, system-level Z3 is difficult and currently not planned.
