### ISSUE TITLE
[BUG] Snowcat unhandled scala.MatchError exception

### ISSUE THREAD

**Issue by andrey-kuprianov** [informalsystems/apalache#860]
## Description

Unhandled exception thrown when type-checking a spec:

```sh
Type checking snowcat_bug.tla                                     I@07:19:31.708
PASS #0: SanyParser                                               I@07:19:31.946
Parsing file /root/agoric/snowcat_bug.tla
PASS #1: TypeCheckerSnowcat                                       I@07:19:32.394
 > Running Snowcat .::.                                           I@07:19:32.394
(Please report an issue at: [https://github.com/informalsystems/apalache/issues],scala.MatchError: (List(VAT_ID, KERNEL_SLOT)~Some((->~MESSAGE))) (of class scala.util.parsing.combinator.Parsers$$tilde))
Unhandled exception                                               E@07:19:32.503
scala.MatchError: (List(VAT_ID, KERNEL_SLOT)~Some((->~MESSAGE))) (of class scala.util.parsing.combinator.Parsers$$tilde)
	at at.forsyte.apalache.io.typecheck.parser.DefaultType1Parser$.$anonfun$typeExpr$5(DefaultType1Parser.scala:68)
	at scala.util.parsing.combinator.Parsers$Success.map(Parsers.scala:138)
	at scala.util.parsing.combinator.Parsers$Parser.$anonfun$map$1(Parsers.scala:258)
	at scala.util.parsing.combinator.Parsers$$anon$1.apply(Parsers.scala:225)
	at scala.util.parsing.combinator.Parsers$$anon$6.apply(Parsers.scala:986)
	at scala.util.parsing.combinator.Parsers$Parser.$anonfun$map$1(Parsers.scala:258)
	at scala.util.parsing.combinator.Parsers$$anon$1.apply(Parsers.scala:225)
	at at.forsyte.apalache.io.typecheck.parser.DefaultType1Parser$.parseType(DefaultType1Parser.scala:31)
	at at.forsyte.apalache.tla.typecheck.etc.ToEtcExpr.parseType(ToEtcExpr.scala:100)
	at at.forsyte.apalache.tla.typecheck.etc.ToEtcExpr.$anonfun$findTypeFromTagOrAnnotation$1(ToEtcExpr.scala:120)
	at scala.Option.map(Option.scala:230)
	at at.forsyte.apalache.tla.typecheck.etc.ToEtcExpr.findTypeFromTagOrAnnotation(ToEtcExpr.scala:118)
	at at.forsyte.apalache.tla.typecheck.etc.ToEtcExpr.operDefToDecl(ToEtcExpr.scala:75)
	at at.forsyte.apalache.tla.typecheck.etc.ToEtcExpr.apply(ToEtcExpr.scala:49)
	at at.forsyte.apalache.tla.typecheck.TypeCheckerTool.$anonfun$check$1(TypeCheckerTool.scala:39)
	at scala.collection.immutable.List.$anonfun$foldRight$1(List.scala:447)
	at scala.collection.immutable.List.foldRight(List.scala:91)
	at at.forsyte.apalache.tla.typecheck.TypeCheckerTool.check(TypeCheckerTool.scala:38)
	at at.forsyte.apalache.tla.typecheck.TypeCheckerTool.checkAndTag(TypeCheckerTool.scala:68)
	at at.forsyte.apalache.tla.typecheck.passes.EtcTypeCheckerPassImpl.execute(EtcTypeCheckerPassImpl.scala:63)
	at at.forsyte.apalache.infra.passes.PassChainExecutor.exec$1(PassChainExecutor.scala:22)
	at at.forsyte.apalache.infra.passes.PassChainExecutor.run(PassChainExecutor.scala:37)
	at at.forsyte.apalache.tla.Tool$.runTypeCheck(Tool.scala:246)
	at at.forsyte.apalache.tla.Tool$.$anonfun$run$7(Tool.scala:109)
	at at.forsyte.apalache.tla.Tool$.handleExceptions(Tool.scala:322)
	at at.forsyte.apalache.tla.Tool$.run(Tool.scala:109)
	at at.forsyte.apalache.tla.Tool$.main(Tool.scala:45)
	at at.forsyte.apalache.tla.Tool.main(Tool.scala)
It took me 0 days  0 hours  0 min  0 sec                          I@07:19:32.504
Total time: 0.798 sec                                             I@07:19:32.505
EXITCODE: ERROR (255)
```

## Input specification

Here is the MWE:

```tla
------------------------------------ MODULE snowcat_bug -----------------------------

\* @typeAlias: VAT_ID = Str;
\* @typeAlias: KERNEL_T = Str;
\* @typeAlias: KERNEL_SLOT = [ type: KERNEL_T, id: Int ];
\* @typeAlias: MESSAGE = [ type: Str, vatID: VAT_ID, enablePipelining: Bool, kpid: KERNEL_SLOT, target: KERNEL_SLOT, msg: Str];

\* @typeAlias: MSG_TYPE = Str;
\* @type: () => MSG_TYPE;
NOTIFY == "notify"
  
\* @type: (VAT_ID, KERNEL_SLOT) -> MESSAGE;
NotifyMessage(vatID, kpid) == [ type |-> NOTIFY, vatID |-> vatID, kpid |-> kpid ]

===============================================================================
```

## The command line parameters used to run the tool

```sh
apalache typecheck snowcat_bug.tla
```

## Log files

[detailed.log](https://github.com/informalsystems/apalache/files/6668183/detailed.log)

## System information

- Apalache version : 0.15.7 build e6eda01
- OS: Ubuntu 20.04.2 LTS
- JDK version: openjdk version "15.0.2" 2021-01-19

**Comment by andrey-kuprianov** [comment]
Sorry, my bad: should have used `=>` instead of `->` :D 

```tla
\* @type: (VAT_ID, KERNEL_SLOT) -> MESSAGE;
```

Having said that, it's still probably a bug?

**Comment by konnov** [comment]
Sure it's a bug. Nice that you have found that right solution :D
