### ISSUE TITLE
[BUG] Uncaught exception: java.lang.IllegalArgumentException: Access to non-existent record field

### ISSUE THREAD

**Issue by andrey-kuprianov** [informalsystems/apalache#874]
## Description

I was trying to write a default initialisation operator. I have many variables, say 10. I want to write tests, and each test touches 1 or 2 from 10. Initializing all 10 variables in every test is not a viable solution; so I want to factor out the defaults into one operator, and in each test to set only the values for the variables I am interested in. The solution I came with is probably not a type-correct one, but it passes the type-checking phase, and then triggers an unhandled exception:

```sh
PASS #11: OptimizationPass                                        I@11:54:29.855
 > Applying optimizations:                                        I@11:54:29.859
  > ConstSimplifier                                               I@11:54:29.859
  > ExprOptimizer                                                 I@11:54:29.862
(Please report an issue at: [https://github.com/informalsystems/apalache/issues],java.lang.IllegalArgumentException: Access to non-existent record field b)
Unhandled exception                                               E@11:54:29.865
java.lang.IllegalArgumentException: Access to non-existent record field b
	at at.forsyte.apalache.tla.pp.ExprOptimizer$$anonfun$transformFuns$1.applyOrElse(ExprOptimizer.scala:46)
	at at.forsyte.apalache.tla.pp.ExprOptimizer$$anonfun$transformFuns$1.applyOrElse(ExprOptimizer.scala:38)
	at scala.PartialFunction$OrElse.apply(PartialFunction.scala:172)
	at at.forsyte.apalache.tla.lir.transformations.impl.TrackerWithListeners.$anonfun$trackEx$1(TrackerWithListeners.scala:16)
	at at.forsyte.apalache.tla.pp.AbstractTransformer.$anonfun$transform$1(AbstractTransformer.scala:36)
	at at.forsyte.apalache.tla.lir.transformations.impl.TrackerWithListeners.$anonfun$trackEx$1(TrackerWithListeners.scala:16)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:286)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
	at scala.collection.TraversableLike.map(TraversableLike.scala:286)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:279)
	at scala.collection.AbstractTraversable.map(Traversable.scala:108)
...
```

## Input specification

Here is the MWE:

```tla
------------------------------------ MODULE expr_bug -----------------------------

EXTENDS Integers

VARIABLE 
\* @type: Int;
a
,
\* @type: Int;
b

\* @type: (Str -> [a: Int, b: Int]) => Bool;
InitDefaultsExcept(vars) ==
  /\ a = IF "a" \in DOMAIN vars THEN vars.a ELSE 0
  /\ b = IF "b" \in DOMAIN vars THEN vars.b ELSE 0

Init == 
  InitDefaultsExcept([
    a |-> 1
  ])

Next == 
  UNCHANGED <<a,b>>

===============================================================================
```

## The command line parameters used to run the tool

```sh
apalache check expr_bug.tla
```

## System information

- Apalache version : 0.15.9-SNAPSHOT build v0.15.8-10-g73fd704
- OS: Ubuntu 20.04.2 LTS
- JDK version: openjdk version "15.0.2" 2021-01-19

## More problem context

Just for the context: while the example above is very simplistic, the problem I am trying to solve is a real one, with default initialisation for unneeded variables. Here is a larger example:

```tla
\* @type: ([ vats: VAT_TABLE, await: MESSAGE, runQueue: Seq(MESSAGE), koNextId: Int, kpNextId: Int, 
\*   kernelToVat: KERNEL_TO_VAT, vatToKernel: VAT_TO_KERNEL,
\*   kernelObjects: OBJECT_TABLE, kernelPromises: PROMISE_TABLE]) => Bool;
InitDefaultsExcept(vars) ==
  /\ vats = IF "vats" \in DOMAIN vars THEN vars.vats ELSE EMPTY_VAT_TABLE
  /\ await = IF "await" \in DOMAIN vars THEN vars.await ELSE NoMessage
  /\ runQueue = IF "runQueue" \in DOMAIN vars THEN vars.runQueue ELSE <<>>
  /\ koNextId = IF "koNextId" \in DOMAIN vars THEN vars.koNextId ELSE 1
  /\ kpNextId = IF "kpNextId" \in DOMAIN vars THEN vars.kpNextId ELSE 1
  /\ kernelToVat = IF "kernelToVat" \in DOMAIN vars THEN vars.kernelToVat ELSE EMPTY_KERNEL_TO_VAT
  /\ vatToKernel = IF "vatToKernel" \in DOMAIN vars THEN vars.vatToKernel ELSE EMPTY_VAT_TO_KERNEL
  /\ kernelObjects = IF "kernelObjects" \in DOMAIN vars THEN vars.kernelObjects ELSE EMPTY_OBJECT_TABLE
  /\ kernelPromises = IF "kernelPromises" \in DOMAIN vars THEN vars.kernelPromises ELSE EMPTY_PROMISE_TABLE

TestCreateUnknownVatBefore ==
  InitDefaultsExcept([
    vats |-> [ id \in {"a", "b"} |-> NEW_VAT(FALSE)]
  ])
```

**Comment by konnov** [comment]
Right, that is the effect of the non-standard record unification rule, which was designed to accommodate unions in Paxos. We should implement #789 and this issue will go away.

**Comment by andrey-kuprianov** [comment]
FYI, I’ve managed to trick Apalache by introducing a local definition; this

```tla
------------------------------------ MODULE expr_bug -----------------------------

EXTENDS Integers

VARIABLE 
\* @type: Int;
a
,
\* @type: Int;
b

\* @type: ([a: Int, b: Int]) => Bool;
InitDefaultsExcept(update) ==
  LET vars == update IN
  /\ a = IF "a" \in DOMAIN vars THEN vars.a ELSE 0
  /\ b = IF "b" \in DOMAIN vars THEN vars.b ELSE 0

Init == 
  InitDefaultsExcept([
    a |-> 1
  ])

Next == 
  UNCHANGED <<a,b>>

Inv == a = 1

===============================================================================
```
bypasses the type-checker completely, sets the initial state as I wanted, and satisfies `Inv`.

**Comment by konnov** [comment]
It's not really a bug, as it works according to the docs. This is a mismatch between user expectations and how the type checker is working. I agree that we should change this behavior as soon as possible. Most likely, in July.

**Comment by shonfeder** [comment]
As I've suggested elsewhere, it seems to me that an uncaught exception is a bug per se. A fix for the current behavior, would be a proper user error, reporting on the problem and how to fix it. All the better if the type checking makes this kinds of error impossible at run time, but presenting stack traces to users is broken behavior, imo.

**Comment by shonfeder** [comment]
Ah, but the bug part here does not fit the title of the issue. That's the bit that pertains to user expectations colliding with our unsound typing on records :)
