### ISSUE TITLE
[BUG] Type-checking fails with named subexpressions

### ISSUE THREAD

**Issue by lemmy** [informalsystems/apalache#876]
See `IInv` below:

```shell
markus@avocado:~/src/TLA/_specs/models/tutorials/BlockingQueueTLA(master)$ apalache check --cinit=ConstInit --length=42 --inv=Invariant BlockingQueue
# Tool home: /home/markus/src/TLA/_community/apalache
# Package:   /home/markus/src/TLA/_community/apalache/mod-distribution/target/apalache-pkg-0.15.9-SNAPSHOT-full.jar
# JVM args:  -Xmx4096m -DTLA-Library=/home/markus/src/TLA/_community/apalache/src/tla
#
# APALACHE version 0.15.9-SNAPSHOT build v0.15.8-3-g6a26844
#
# WARNING: This tool is in the experimental stage.
#          Please report bugs at: [https://github.com/informalsystems/apalache/issues]
# 
# Usage statistics is ON. Thank you!
# If you have changed your mind, disable the statistics with config --enable-stats=false.

Checker options: filename=BlockingQueue, init=, next=, inv=Invariant I@12:43:02.915
Tuning:                                                           I@12:43:03.340
PASS #0: SanyParser                                               I@12:43:03.341
Parsing file /home/markus/src/TLA/_specs/models/tutorials/BlockingQueueTLA/BlockingQueue.tla
Parsing file /tmp/Naturals.tla
Parsing file /tmp/Sequences.tla
Parsing file /tmp/FiniteSets.tla
PASS #1: TypeCheckerSnowcat                                       I@12:43:04.179
 > Running Snowcat .::.                                           I@12:43:04.179
(Please report an issue at: [https://github.com/informalsystems/apalache/issues],java.lang.IllegalArgumentException: Unsupported expression: <[NULL]>)
Unhandled exception                                               E@12:43:04.254
java.lang.IllegalArgumentException: Unsupported expression: <[NULL]>
	at at.forsyte.apalache.tla.typecheck.etc.ToEtcExpr.transform(ToEtcExpr.scala:851)
	at at.forsyte.apalache.tla.typecheck.etc.ToEtcExpr.apply(ToEtcExpr.scala:171)
	at at.forsyte.apalache.tla.typecheck.etc.ToEtcExpr.$anonfun$transform$1(ToEtcExpr.scala:192)
	at scala.collection.immutable.List.map(List.scala:293)
	at at.forsyte.apalache.tla.typecheck.etc.ToEtcExpr.mkExRefApp$1(ToEtcExpr.scala:192)
	at at.forsyte.apalache.tla.typecheck.etc.ToEtcExpr.transform(ToEtcExpr.scala:272)
	at at.forsyte.apalache.tla.typecheck.etc.ToEtcExpr.apply(ToEtcExpr.scala:171)
	at at.forsyte.apalache.tla.typecheck.etc.ToEtcExpr.operDefToDecl(ToEtcExpr.scala:84)
	at at.forsyte.apalache.tla.typecheck.etc.ToEtcExpr.apply(ToEtcExpr.scala:49)
	at at.forsyte.apalache.tla.typecheck.TypeCheckerTool.$anonfun$check$1(TypeCheckerTool.scala:39)
	at scala.collection.immutable.List.$anonfun$foldRight$1(List.scala:447)
	at scala.collection.immutable.List.foldRight(List.scala:91)
	at at.forsyte.apalache.tla.typecheck.TypeCheckerTool.check(TypeCheckerTool.scala:38)
	at at.forsyte.apalache.tla.typecheck.TypeCheckerTool.checkAndTag(TypeCheckerTool.scala:68)
	at at.forsyte.apalache.tla.typecheck.passes.EtcTypeCheckerPassImpl.execute(EtcTypeCheckerPassImpl.scala:63)
	at at.forsyte.apalache.infra.passes.PassChainExecutor.exec$1(PassChainExecutor.scala:22)
	at at.forsyte.apalache.infra.passes.PassChainExecutor.run(PassChainExecutor.scala:37)
	at at.forsyte.apalache.tla.Tool$.runCheck(Tool.scala:187)
	at at.forsyte.apalache.tla.Tool$.$anonfun$run$3(Tool.scala:95)
	at at.forsyte.apalache.tla.Tool$.handleExceptions(Tool.scala:322)
	at at.forsyte.apalache.tla.Tool$.run(Tool.scala:95)
	at at.forsyte.apalache.tla.Tool$.main(Tool.scala:45)
	at at.forsyte.apalache.tla.Tool.main(Tool.scala)
It took me 0 days  0 hours  0 min  1 sec                          I@12:43:04.259
Total time: 1.432 sec                                             I@12:43:04.259
EXITCODE: ERROR (255)
```

```tla
--------------------------- MODULE BlockingQueue ---------------------------
EXTENDS Naturals, Sequences, FiniteSets

CONSTANTS 
    \* @type: Set(Str);
    Producers,   (* the (nonempty) set of producers                       *)
    \* @type: Set(Str);
    Consumers,   (* the (nonempty) set of consumers                       *)
    \* @type: Int;
    BufCapacity  (* the maximum number of messages in the bounded buffer  *)
       
ConstInit ==
  /\ Producers = {"p1","p2","p3","p4"} 
  /\ Consumers = {"c1","c2","c3"}
  /\ BufCapacity = 3\*1

-----------------------------------------------------------------------------

VARIABLES 
    \* @type: Seq(Str);
    buffer,
    \* @type: Set(Str);
    waitSet

vars == <<buffer, waitSet>>

RunningThreads == (Producers \cup Consumers) \ waitSet

NotifyOther(t) == 
          LET S == IF t \in Producers THEN waitSet \ Producers ELSE waitSet \ Consumers
          IN IF S # {}
             THEN \E x \in S : waitSet' = waitSet \ {x}
             ELSE UNCHANGED waitSet

(* @see java.lang.Object#wait *)
Wait(t) == /\ waitSet' = waitSet \cup {t}
           /\ UNCHANGED <<buffer>>
           
-----------------------------------------------------------------------------

Put(t, d) ==
/\ t \notin waitSet
/\ \/ /\ Len(buffer) < BufCapacity
      /\ buffer' = Append(buffer, d)
      /\ NotifyOther(t)
   \/ /\ Len(buffer) = BufCapacity
      /\ Wait(t)
      
Get(t) ==
/\ t \notin waitSet
/\ \/ /\ buffer # <<>>
      /\ buffer' = Tail(buffer)
      /\ NotifyOther(t)
   \/ /\ buffer = <<>>
      /\ Wait(t)

-----------------------------------------------------------------------------

(* Initially, the buffer is empty and no thread is waiting. *)
Init == /\ buffer = <<>>
        /\ waitSet = {}

(* Then, pick a thread out of all running threads and have it do its thing. *)
Next == \/ \E p \in Producers: Put(p, p) \* Add some data to buffer
        \/ \E c \in Consumers: Get(c)

-----------------------------------------------------------------------------
TypeInv == /\ buffer \in Seq(Producers)
           /\ Len(buffer) \in 0..BufCapacity
           /\ waitSet \in SUBSET (Producers \cup Consumers)

(* No Deadlock *)
Invariant == waitSet # (Producers \cup Consumers)

Spec == Init /\ [][Next]_vars

IInv == /\ TypeInv!2
        /\ TypeInv!3
        /\ Invariant
        \* When the buffer is empty, a consumer will be added to the waitSet.
        \* However, this does not crate a deadlock, because at least one producer
        \* will not be in the waitSet.
        /\ buffer = <<>> => \E p \in Producers : p \notin waitSet
        \* Vice versa, when buffer is full, a producer will be added to waitSet,
        \* but at least one consumer won't be in waitSet.
        /\ Len(buffer) = BufCapacity => \E c \in Consumers : c \notin waitSet

=============================================================================
```

**Comment by konnov** [comment]
Good point. We should produce a normal error on `TypeInv!2`

**Comment by lemmy** [comment]
From my perspective, this is a useful enough language feature and used by a large enough number of users to make it worth supporting.

**Comment by Kukovec** [comment]
Where are `TypeInv` and `Invariant` defined?

**Comment by lemmy** [comment]
Was a copy&paste error! Spec above now has `TypeInv` and `Invariant`.

**Comment by konnov** [comment]
Well, apparently the importer works fine, as `TypeInv!2` is application of the operator `$Nop`. I will add a parse error right away.

**Comment by konnov** [comment]
Here is an example of what one can write with `!`:

```tla
------------------------------ MODULE FormulaRefs -----------------------------
\* tests of the subformula syntax e.g., A!2
EXTENDS Integers

VARIABLES
    \* @type: Int;
    x

A ==
    /\ x > 3
    /\ x > 2

B(y) ==
    /\ y > 3
    /\ y > 2

Init ==
    x = 2

Next ==
    x' = x

Inv1 ==
    A!1

Inv2 ==
    A!2

Inv4 ==
    B(x)!1

Inv5 ==
    B(x)!2

===============================================================================
```

I can imagine how to translate `Inv1` and `Inv2`, but `Inv3` and `Inv4` would require too much work. In any case, this is the syntax for writing TLAPS proofs.
