### ISSUE TITLE
[BUG] No rewriting rule applies to expression: x ∈ ({t_2$1 ∈ Apalache!Expand(SUBSET {1, 2}): ¬t_2$1 ∈ {{}}})

### ISSUE THREAD

**Issue by lemmy** [informalsystems/apalache#877]
```tla
------- MODULE Foo -------
EXTENDS Integers

VARIABLE 
    \* @type: Set(Int);
    x

ConstInit ==
    x \in ((SUBSET {1,2}) \ {{}})

Init ==
    x = {1,2}

Next ==
    UNCHANGED x

Inv ==
    x # {}
==========================

markus@avocado:~/$ tlc -config Foo.tla Foo
TLC2 Version 2.16 of Day Month 20?? (rev: c465d0d)
Running breadth-first search Model-Checking with fp 29 and seed -8574176126989200942 with 1 worker on 4 cores with 5291MB heap and 64MB offheap memory [pid: 205206] (Linux 5.4.0-74-generic amd64, Ubuntu 11.0.11 x86_64, MSBDiskFPSet, DiskStateQueue).
Parsing file Foo.tla
Parsing file /tmp/Integers.tla (jar:file:/opt/toolbox/tla2tools.jar!/tla2sany/StandardModules/Integers.tla)
Parsing file /tmp/Naturals.tla (jar:file:/opt/toolbox/tla2tools.jar!/tla2sany/StandardModules/Naturals.tla)
Semantic processing of module Naturals
Semantic processing of module Integers
Semantic processing of module Foo
Starting... (2021-06-23 13:11:22)
Computing initial states...
Computed 2 initial states...
Finished computing initial states: 3 distinct states generated at 2021-06-23 13:11:23.
Model checking completed. No error has been found.
  Estimates of the probability that TLC did not check all reachable states
  because two distinct states had the same fingerprint:
  calculated (optimistic):  val = 4.9E-19
6 states generated, 3 distinct states found, 0 states left on queue.
The depth of the complete state graph search is 1.
The average outdegree of the complete state graph is 0 (minimum is 0, the maximum 0 and the 95th percentile is 0).
Finished in 00s at (2021-06-23 13:11:23)

----- CONFIG Foo -----
INIT ConstInit
NEXT Next
INVARIANT Inv
====
```

```shell
markus@avocado:~$ apalache check --inv=Inv --cinit=ConstInit Foo.tla 
# Tool home: /home/markus/src/TLA/_community/apalache
# Package:   /home/markus/src/TLA/_community/apalache/mod-distribution/target/apalache-pkg-0.15.9-SNAPSHOT-full.jar
# JVM args:  -Xmx4096m -DTLA-Library=/home/markus/src/TLA/_community/apalache/src/tla
#
# APALACHE version 0.15.9-SNAPSHOT build v0.15.8-3-g6a26844
#
# WARNING: This tool is in the experimental stage.
#          Please report bugs at: [https://github.com/informalsystems/apalache/issues]
# 
# Usage statistics is ON. Thank you!
# If you have changed your mind, disable the statistics with config --enable-stats=false.

Checker options: filename=Foo.tla, init=, next=, inv=Inv          I@13:12:07.604
Tuning:                                                           I@13:12:08.061
PASS #0: SanyParser                                               I@13:12:08.062
Parsing file /home/markus/src/TLA/_specs/models/tutorials/BlockingQueueTLA/Foo.tla
Parsing file /tmp/Integers.tla
Parsing file /tmp/Naturals.tla
PASS #1: TypeCheckerSnowcat                                       I@13:12:08.695
 > Running Snowcat .::.                                           I@13:12:08.695
 > Your types are great!                                          I@13:12:08.799
 > All expressions are typed                                      I@13:12:08.799
PASS #2: ConfigurationPass                                        I@13:12:08.832
  > Foo.cfg: Loading TLC configuration                            I@13:12:08.836
  > No TLC configuration found. Skipping.                         I@13:12:08.845
  > Command line option --init is not set. Using Init             I@13:12:08.845
  > Command line option --next is not set. Using Next             I@13:12:08.845
  > Set the initialization predicate to Init                      I@13:12:08.845
  > Set the constant initialization predicate to ConstInit        I@13:12:08.846
  > Set the transition predicate to Next                          I@13:12:08.846
  > Set an invariant to Inv                                       I@13:12:08.847
PASS #3: DesugarerPass                                            I@13:12:08.868
  > Desugaring...                                                 I@13:12:08.868
PASS #4: UnrollPass                                               I@13:12:08.893
  > Unroller                                                      I@13:12:08.910
PASS #5: PrimingPass                                              I@13:12:08.940
  > Introducing ConstInitPrimed for ConstInit'                    I@13:12:08.944
  > Introducing InitPrimed for Init'                              I@13:12:08.948
PASS #6: CoverAnalysisPass                                        I@13:12:08.983
PASS #7: InlinePass                                               I@13:12:08.984
  > InlinerOfUserOper                                             I@13:12:08.997
  > LetInExpander                                                 I@13:12:08.998
  > FoldOperLetinizer                                             I@13:12:08.999
  > InlinerOfUserOper                                             I@13:12:09.000
Leaving only relevant operators: ConstInit, ConstInitPrimed, Init, InitPrimed, Inv, Next I@13:12:09.002
PASS #8: VCGen                                                    I@13:12:09.058
  > Producing verification conditions from the invariant Inv      I@13:12:09.061
  > VCGen produced 1 verification condition(s)                    I@13:12:09.099
PASS #9: PreprocessingPass                                        I@13:12:09.120
  > Before preprocessing: unique renaming                         I@13:12:09.121
 > Applying standard transformations:                             I@13:12:09.128
  > PrimePropagation                                              I@13:12:09.129
  > Desugarer                                                     I@13:12:09.170
  > UniqueRenamer                                                 I@13:12:09.202
  > Normalizer                                                    I@13:12:09.223
  > Keramelizer                                                   I@13:12:09.245
  > After preprocessing: UniqueRenamer                            I@13:12:09.274
PASS #10: TransitionFinderPass                                    I@13:12:09.301
  > Found 1 initializing transitions                              I@13:12:09.340
  > Found 1 transitions                                           I@13:12:09.343
  > Found constant initializer ConstInit                          I@13:12:09.344
  > Applying unique renaming                                      I@13:12:09.347
PASS #11: OptimizationPass                                        I@13:12:09.373
 > Applying optimizations:                                        I@13:12:09.385
  > ConstSimplifier                                               I@13:12:09.386
  > ExprOptimizer                                                 I@13:12:09.394
  > ConstSimplifier                                               I@13:12:09.401
PASS #12: AnalysisPass                                            I@13:12:09.423
 > Marking skolemizable existentials and sets to be expanded...   I@13:12:09.427
  > SkolemizationMarker                                           I@13:12:09.429
  > ExpansionMarker                                               I@13:12:09.430
The set SUBSET {1, 2} will be expanded. This will blow up the solver. W@13:12:09.433
 > Running analyzers...                                           I@13:12:09.449
  > Introduced expression grades                                  I@13:12:09.486
  > Introduced 0 formula hints                                    I@13:12:09.487
PASS #13: PostTypeCheckerSnowcat                                  I@13:12:09.487
 > Running Snowcat .::.                                           I@13:12:09.488
 > Your types are great!                                          I@13:12:09.638
 > All expressions are typed                                      I@13:12:09.640
PASS #14: BoundedChecker                                          I@13:12:09.687
(Please report an issue at: [https://github.com/informalsystems/apalache/issues],at.forsyte.apalache.tla.bmcmt.RewriterException: No rewriting rule applies to expression: x ∈ ({t_2$1 ∈ Apalache!Expand(SUBSET {1, 2}): ¬t_2$1 ∈ {{}}}))
Foo.tla:9:5-9:33: rewriter error: No rewriting rule applies to expression: x ∈ ({t_2$1 ∈ Apalache!Expand(SUBSET {1, 2}): ¬t_2$1 ∈ {{}}}) E@13:12:10.283
at.forsyte.apalache.tla.bmcmt.RewriterException: No rewriting rule applies to expression: x ∈ ({t_2$1 ∈ Apalache!Expand(SUBSET {1, 2}): ¬t_2$1 ∈ {{}}})
	at at.forsyte.apalache.tla.bmcmt.SymbStateRewriterImpl.doRecursive$1(SymbStateRewriterImpl.scala:382)
	at at.forsyte.apalache.tla.bmcmt.SymbStateRewriterImpl.rewriteUntilDone(SymbStateRewriterImpl.scala:401)
	at at.forsyte.apalache.tla.bmcmt.trex.TransitionExecutorImpl.initializeConstants(TransitionExecutorImpl.scala:60)
	at at.forsyte.apalache.tla.bmcmt.trex.FilteredTransitionExecutor.initializeConstants(FilteredTransitionExecutor.scala:96)
	at at.forsyte.apalache.tla.bmcmt.trex.ConstrainedTransitionExecutor.initializeConstants(ConstrainedTransitionExecutor.scala:90)
	at at.forsyte.apalache.tla.bmcmt.SeqModelChecker.run(SeqModelChecker.scala:44)
	at at.forsyte.apalache.tla.bmcmt.passes.BoundedCheckerPassImpl.runIncrementalChecker(BoundedCheckerPassImpl.scala:131)
	at at.forsyte.apalache.tla.bmcmt.passes.BoundedCheckerPassImpl.execute(BoundedCheckerPassImpl.scala:98)
	at at.forsyte.apalache.infra.passes.PassChainExecutor.exec$1(PassChainExecutor.scala:22)
	at at.forsyte.apalache.infra.passes.PassChainExecutor.run(PassChainExecutor.scala:37)
	at at.forsyte.apalache.tla.Tool$.runCheck(Tool.scala:187)
	at at.forsyte.apalache.tla.Tool$.$anonfun$run$3(Tool.scala:95)
	at at.forsyte.apalache.tla.Tool$.handleExceptions(Tool.scala:322)
	at at.forsyte.apalache.tla.Tool$.run(Tool.scala:95)
	at at.forsyte.apalache.tla.Tool$.main(Tool.scala:45)
	at at.forsyte.apalache.tla.Tool.main(Tool.scala)
It took me 0 days  0 hours  0 min  2 sec                          I@13:12:10.285
Total time: 2.747 sec                                             I@13:12:10.286
EXITCODE: ERROR (255)
```

**Comment by konnov** [comment]
We are talking about `ConstInit` here. It should have complained about `x` being a variable, right?
