### ISSUE TITLE
[BUG] java.util.NoSuchElementException: key not found: 34) Unhandled exception

### ISSUE THREAD

**Issue by lemmy** [informalsystems/apalache#879]
```tla
markus@avocado:~$ apalache check Bar
# Tool home: /home/markus/src/TLA/_community/apalache
# Package:   /home/markus/src/TLA/_community/apalache/mod-distribution/target/apalache-pkg-0.15.9-SNAPSHOT-full.jar
# JVM args:  -Xmx4096m -DTLA-Library=/home/markus/src/TLA/_community/apalache/src/tla
#
# APALACHE version 0.15.9-SNAPSHOT build v0.15.8-3-g6a26844
#
# WARNING: This tool is in the experimental stage.
#          Please report bugs at: [https://github.com/informalsystems/apalache/issues]
# 
# Usage statistics is ON. Thank you!
# If you have changed your mind, disable the statistics with config --enable-stats=false.

Checker options: filename=Bar, init=, next=, inv=                 I@15:50:22.462
Tuning:                                                           I@15:50:22.931
PASS #0: SanyParser                                               I@15:50:22.932
Parsing file /home/markus/src/TLA/_specs/models/tutorials/BlockingQueueTLA/Bar.tla
PASS #1: TypeCheckerSnowcat                                       I@15:50:23.511
 > Running Snowcat .::.                                           I@15:50:23.511
 > Your types are great!                                          I@15:50:23.643
 > All expressions are typed                                      I@15:50:23.643
PASS #2: ConfigurationPass                                        I@15:50:23.664
  > Bar: Loading TLC configuration                                I@15:50:23.668
  > No TLC configuration found. Skipping.                         I@15:50:23.673
  > Command line option --init is not set. Using Init             I@15:50:23.674
  > Command line option --next is not set. Using Next             I@15:50:23.675
  > Set the initialization predicate to Init                      I@15:50:23.675
  > Set the transition predicate to Next                          I@15:50:23.676
PASS #3: DesugarerPass                                            I@15:50:23.698
  > Desugaring...                                                 I@15:50:23.699
PASS #4: UnrollPass                                               I@15:50:23.718
  > Unroller                                                      I@15:50:23.728
PASS #5: PrimingPass                                              I@15:50:23.746
  > Introducing InitPrimed for Init'                              I@15:50:23.750
PASS #6: CoverAnalysisPass                                        I@15:50:23.761
PASS #7: InlinePass                                               I@15:50:23.763
  > InlinerOfUserOper                                             I@15:50:23.765
  > LetInExpander                                                 I@15:50:23.766
  > FoldOperLetinizer                                             I@15:50:23.766
  > InlinerOfUserOper                                             I@15:50:23.767
Leaving only relevant operators: CInitPrimed, Init, InitPrimed, Next I@15:50:23.770
PASS #8: VCGen                                                    I@15:50:23.781
  > No invariant given. Only deadlocks will be checked            I@15:50:23.781
PASS #9: PreprocessingPass                                        I@15:50:23.789
  > Before preprocessing: unique renaming                         I@15:50:23.790
 > Applying standard transformations:                             I@15:50:23.798
  > PrimePropagation                                              I@15:50:23.798
  > Desugarer                                                     I@15:50:23.806
  > UniqueRenamer                                                 I@15:50:23.813
  > Normalizer                                                    I@15:50:23.824
  > Keramelizer                                                   I@15:50:23.837
  > After preprocessing: UniqueRenamer                            I@15:50:23.847
PASS #10: TransitionFinderPass                                    I@15:50:23.856
(Please report an issue at: [https://github.com/informalsystems/apalache/issues],java.util.NoSuchElementException: key not found: 34)
Unhandled exception                                               E@15:50:23.870
java.util.NoSuchElementException: key not found: 34
	at scala.collection.immutable.Map$EmptyMap$.apply(Map.scala:107)
	at scala.collection.immutable.Map$EmptyMap$.apply(Map.scala:105)
	at at.forsyte.apalache.tla.assignments.SymbTransGenerator.apply(SymbTransGenerator.scala:307)
	at at.forsyte.apalache.tla.assignments.SmtFreeSymbolicTransitionExtractor.apply(SmtFreeSymbolicTransitionExtractor.scala:184)
	at at.forsyte.apalache.tla.assignments.passes.TransitionPassImpl.extractTransitions(TransitionPassImpl.scala:95)
	at at.forsyte.apalache.tla.assignments.passes.TransitionPassImpl.execute(TransitionPassImpl.scala:46)
	at at.forsyte.apalache.infra.passes.PassChainExecutor.exec$1(PassChainExecutor.scala:22)
	at at.forsyte.apalache.infra.passes.PassChainExecutor.run(PassChainExecutor.scala:37)
	at at.forsyte.apalache.tla.Tool$.runCheck(Tool.scala:187)
	at at.forsyte.apalache.tla.Tool$.$anonfun$run$3(Tool.scala:95)
	at at.forsyte.apalache.tla.Tool$.handleExceptions(Tool.scala:322)
	at at.forsyte.apalache.tla.Tool$.run(Tool.scala:95)
	at at.forsyte.apalache.tla.Tool$.main(Tool.scala:45)
	at at.forsyte.apalache.tla.Tool.main(Tool.scala)
It took me 0 days  0 hours  0 min  1 sec                          I@15:50:23.871
Total time: 1.491 sec                                             I@15:50:23.872
EXITCODE: ERROR (255)
```

```shell
----- MODULE Bar ----
Init ==
    TRUE

Next ==
    TRUE
=====
```

**Comment by lemmy** [comment]
Duplicate of #871
