### ISSUE TITLE
[BUG] RewriterException when running recursive definition

### ISSUE THREAD

**Issue by svalaskevicius** [informalsystems/apalache#923]
## Description

got this error when trying to run it:

```
(Please report an issue at: [https://github.com/informalsystems/apalache/issues],at.forsyte.apalache.tla.bmcmt.RewriterException: Expected a constant integer range in .., found 1..len_s$1())
MessageTransmission.tla:246:12-246:75: rewriter error: Expected a constant integer range in .., found 1..len_s$1() E@15:49:24.288
at.forsyte.apalache.tla.bmcmt.RewriterException: Expected a constant integer range in .., found 1..len_s$1()
        at at.forsyte.apalache.tla.bmcmt.rules.IntDotDotRule.getRange(IntDotDotRule.scala:52)
        at at.forsyte.apalache.tla.bmcmt.rules.IntDotDotRule.apply(IntDotDotRule.scala:31)
        at at.forsyte.apalache.tla.bmcmt.SymbStateRewriterImpl.rewriteOnce(SymbStateRewriterImpl.scala:336)
        at at.forsyte.apalache.tla.bmcmt.SymbStateRewriterImpl.doRecursive$1(SymbStateRewriterImpl.scala:367)
        at at.forsyte.apalache.tla.bmcmt.SymbStateRewriterImpl.rewriteUntilDone(SymbStateRewriterImpl.scala:401)
        at at.forsyte.apalache.tla.bmcmt.rules.RecFunDefAndRefRule.rewriteFunCtor(RecFunDefAndRefRule.scala:54)
        at at.forsyte.apalache.tla.bmcmt.rules.RecFunDefAndRefRule.apply(RecFunDefAndRefRule.scala:35)
        at at.forsyte.apalache.tla.bmcmt.SymbStateRewriterImpl.rewriteOnce(SymbStateRewriterImpl.scala:336)
        at at.forsyte.apalache.tla.bmcmt.SymbStateRewriterImpl.doRecursive$1(SymbStateRewriterImpl.scala:367)
        at at.forsyte.apalache.tla.bmcmt.SymbStateRewriterImpl.rewriteUntilDone(SymbStateRewriterImpl.scala:401)
        at at.forsyte.apalache.tla.bmcmt.rules.LetInRule.bindOperator(LetInRule.scala:44)
        at at.forsyte.apalache.tla.bmcmt.rules.LetInRule.$anonfun$apply$1(LetInRule.scala:25)
```

## Input specification

the only place where `.. len_s` is used:

```
\* Helper function, dropWhile(!Test(_))
SelectSeqFrom(s, Test(_)) == 
  LET
    len_s == Len(s) 
    F[i \in 1..len_s] == 
        IF i > 1 /\ F[i-1] /= <<>>  THEN F[i-1]
        ELSE IF Test(s[i]) THEN SubSeq(s, i, len_s)
                           ELSE <<>>
  IN F[len_s]
```

## System information

```
0.15.12-SNAPSHOT build v0.15.11-6-gce8dcf8
```
(official docker image)

**Comment by svalaskevicius** [comment]
hmm if I change the range to `DOMAIN s` I get  the following:

```
(Please report an issue at: [https://github.com/informalsystems/apalache/issues],at.forsyte.apalache.tla.bmcmt.RewriterException: A result of a recursive function must belong to Int or BOOLEAN. Found: Seq([cp: Str, robot: Str, robotSeq: Int, sec: Int, seq: Int]))
MessageTransmission.tla:246:12-246:75: rewriter error: A result of a recursive function must belong to Int or BOOLEAN. Found: Seq([cp: Str, robot: Str, robotSeq: Int, sec: Int, seq: Int]) E@16:25:52.376
at.forsyte.apalache.tla.bmcmt.RewriterException: A result of a recursive function must belong to Int or BOOLEAN. Found: Seq([cp: Str, robot: Str, robotSeq: Int, sec: Int, seq: Int])
```

**Comment by svalaskevicius** [comment]
update.. so far this one doesn't complain, still testing if correct though:

```
\* Helper function, dropWhile(!Test(_))
\* @type: (Seq(a), a => Bool) => Seq(a);
SelectSeqFrom(s, Test(_)) == 
  LET
    len_s == Len(s) 
    len_s_1 == len_s + 1
    min_i == CHOOSE x \in DOMAIN s \cup {len_s_1}: (\A i \in {xx \in DOMAIN s : xx<x}: ~Test(s[i])) /\ (x = len_s_1 \/ Test(s[x]))
  IN SubSeq(s, min_i, len_s)
```

**Comment by Kukovec** [comment]
If I understand correctly, you want to drop all elements of a sequence before the 1st element satisfying `Test`. 
I would recommend you try the following:
```
SelectSeqFrom(s, Test(_)) ==
  LET FromFirstThatTests(seqAndFound,si) == 
    \* seqAndFound[1] is the partial sequence, 
    \* seqAndFound[2] is the flag that tells us if we have found a witness already  
    \* si is the current sequence element being tested
    IF seqAndFound[2] \/ Test(si) \* If we have found the witness at a smaller index already, or if si is the head of the result sequence, start collecting
    THEN << Append(seqAndFound[1], si), TRUE >>
    ELSE seqAndFound \* otherwise, do nothing, should be << <<>>, FALSE >> 
  IN FoldSeq( FromFirstThatTests, << <<>>, FALSE >>, s)[1]
```

**Comment by Kukovec** [comment]
I've removed the `bug` label, because the behavior is expected, but this is definitely a case where UX improvements should be made (non-const bounds should be found in a static analysis pass and exit cleanly).

**Comment by svalaskevicius** [comment]
Thanks!

**Comment by shonfeder** [comment]
@Kukovec I think any uncaught exception counts as a bug. There are other issues discussed here, but at the least, I think addressing this issue should involve catching the rewrite exception and giving a proper user error.

**Comment by konnov** [comment]
We definitely should improve error reporting here. The issue about `a..b` is popping up quite often, see #425. This is a left over from the early prototype, where we wanted to "fail fast".
